const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||10000;
const SB='https://jjdsajiwoqanefmnikls.supabase.co/functions/v1';
const API=SB+'/jana-api',OPS=SB+'/jana-ops-extra',CRITICAL=SB+'/jana-critical',root=__dirname;
const PH_KEY=process.env.POSTHOG_PROJECT_KEY||'',PH_HOST=(process.env.POSTHOG_HOST||'https://us.i.posthog.com').replace(/\/$/,'');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.txt':'text/plain; charset=utf-8'};
function base(res,type='text/html; charset=utf-8'){res.setHeader('content-type',type);res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','same-origin');res.setHeader('x-frame-options','DENY');res.setHeader('permissions-policy','camera=(), microphone=(), geolocation=(self)');res.setHeader('cache-control','no-store')}
function body(req){return ['GET','HEAD'].includes(req.method)?Promise.resolve(undefined):new Promise((ok,bad)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>1024*1024){bad(new Error('body_too_large'));req.destroy();return}a.push(c)});req.on('end',()=>ok(Buffer.concat(a)));req.on('error',bad)})}
function setCookies(res,r){let all=[];if(typeof r.headers.getSetCookie==='function')all=r.headers.getSetCookie();else{const v=r.headers.get('set-cookie');if(v)all=[v]}all=all.flatMap(v=>String(v).split(/,(?=\s*[^;,]+=)/)).map(v=>v.trim()).filter(Boolean);if(all.length)res.setHeader('set-cookie',all)}
function anonId(req){const a=req.headers.authorization||'',c=req.headers.cookie||'';const seed=a||c;if(!seed)return'jana-anonymous';return'jana-'+crypto.createHash('sha256').update(seed).digest('hex').slice(0,24)}
function eventName(method,p,status){if(status>=500)return'jana_api_error';if(status>=400)return'jana_api_rejected';if(method==='POST'&&p==='/api/auth/register')return'jana_account_created';if(method==='POST'&&p==='/api/auth/login')return'jana_login_succeeded';if(method==='POST'&&p==='/api/quotes')return'jana_quote_created';if(method==='POST'&&p==='/api/orders')return'jana_order_created';if(/\/refunds$/.test(p)&&method==='POST')return'jana_refund_requested';if(/\/review$/.test(p)&&method==='POST')return'jana_review_submitted';if(/^\/api\/tickets/.test(p)&&method==='POST')return'jana_support_activity';if(/^\/api\/favorites/.test(p)&&['POST','DELETE'].includes(method))return'jana_favorite_changed';if(/^\/api\/substitutions\/.+\/decision$/.test(p)&&method==='POST')return'jana_substitution_decided';if(/^\/api\/ops\//.test(p)&&!['GET','HEAD'].includes(method))return'jana_ops_change';return'jana_api_request'}
function track(req,p,status,ms){if(!PH_KEY)return;const payload={api_key:PH_KEY,event:eventName(req.method,p,status),properties:{distinct_id:anonId(req),path:p,method:req.method,status,duration_ms:ms,service:'jana-gateway',environment:'production',$process_person_profile:false}};fetch(PH_HOST+'/capture/',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(2500)}).catch(()=>{})}
async function proxy(req,res,u){const started=Date.now();const ops=/^\/api\/ops\/(catalog|suppliers|coupons|slots|stock|lots|zones|lots\/[^/]+\/(inspect|adjust)|families\/[^/]+\/versions|offerings\/[^/]+\/active|coupons\/[^/]+\/active|slots\/[^/]+\/active|orders\/[^/]+\/(collect|settle))$/.test(u.pathname);const critical=req.method==='POST'&&u.pathname==='/api/quotes';const upstream=(critical?CRITICAL:ops?OPS:API)+u.pathname+u.search;const h={};for(const k of ['content-type','authorization','x-csrf-token','idempotency-key','cookie'])if(req.headers[k])h[k]=req.headers[k];const r=await fetch(upstream,{method:req.method,headers:h,body:await body(req),redirect:'manual'});const out=Buffer.from(await r.arrayBuffer());base(res,r.headers.get('content-type')||'application/json; charset=utf-8');res.statusCode=r.status;setCookies(res,r);for(const k of ['x-request-id','retry-after']){const v=r.headers.get(k);if(v)res.setHeader(k,v)}res.end(out);track(req,u.pathname,r.status,Date.now()-started)}
function sendStatic(res,full){const ext=path.extname(full);base(res,types[ext]||'application/octet-stream');if(['.css','.js','.svg','.png','.webmanifest'].includes(ext))res.setHeader('cache-control','public, max-age=300');fs.createReadStream(full).pipe(res)}
function concat(res,globPrefix,count,type){base(res,type);res.setHeader('cache-control','public, max-age=60');for(let i=1;i<=count;i++){const f=path.join(root,'assets',`${globPrefix}.part${String(i).padStart(2,'0')}${globPrefix==='styles'?'.css':'.js'}`);if(!fs.existsSync(f)){res.statusCode=503;return res.end('asset build incomplete')}res.write(fs.readFileSync(f))}res.end()}
function commonBundle(res){const f=path.join(root,'assets','common.js');if(!fs.existsSync(f)){res.statusCode=503;base(res,'text/javascript; charset=utf-8');return res.end('throw new Error("common asset missing")')}let s=fs.readFileSync(f,'utf8');s=s.replace('new Date(stamp*1000)','new Date(Number(stamp)>1e12?Number(stamp):Number(stamp)*1000)');base(res,'text/javascript; charset=utf-8');res.setHeader('cache-control','public, max-age=60');res.end(s)}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');if(u.pathname==='/health'||u.pathname==='/ready'){const r=await fetch(API+'/health');base(res,'application/json; charset=utf-8');res.statusCode=r.status;return res.end(await r.text())}if(u.pathname==='/robots.txt'){base(res,'text/plain; charset=utf-8');return res.end('User-agent: *\nAllow: /\nDisallow: /admin.html\nDisallow: /picker.html\nDisallow: /courier.html\nDisallow: /api/\n')}if(u.pathname.startsWith('/api/'))return await proxy(req,res,u);if(u.pathname==='/assets/shop.js')return concat(res,'shop',5,'text/javascript; charset=utf-8');if(u.pathname==='/assets/ops.js')return concat(res,'ops',4,'text/javascript; charset=utf-8');if(u.pathname==='/assets/styles.css')return concat(res,'styles',2,'text/css; charset=utf-8');if(u.pathname==='/assets/common.js')return commonBundle(res);let f=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));f=path.normalize(f).replace(/^(\.\.(\/|\\|$))+/,'');const full=path.resolve(root,f);if(!full.startsWith(path.resolve(root)+path.sep)&&full!==path.resolve(root,'index.html')){res.statusCode=403;base(res);return res.end('Forbidden')}if(!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.statusCode=404;base(res);return res.end('Not found')}sendStatic(res,full)}catch(e){res.statusCode=String(e.message)==='body_too_large'?413:502;base(res,'application/json; charset=utf-8');res.end(JSON.stringify({error:{code:res.statusCode===413?'BODY_TOO_LARGE':'GATEWAY_ERROR',message:'تعذر إكمال الطلب عبر بوابة جَنى'}}))}}).listen(PORT,'0.0.0.0',()=>console.log('JANA gateway listening',PORT));