import React,{useEffect,useMemo,useState} from 'react';
import {Alert,FlatList,KeyboardAvoidingView,Modal,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {createApiClient,restoreSession} from './api.mjs';
import CustomerSaved from './CustomerSaved.js';
import CloudCart from './CloudCart.js';
import BasketBuilder from './BasketBuilder.js';
import {loadCatalog} from './catalog.mjs';

const API=process.env.EXPO_PUBLIC_API_BASE||'https://jana-fresh-app.onrender.com';
const request=createApiClient({base:API,storage:SecureStore});
const TOKEN_KEY='jana.mobile.token',CART_KEY='jana.mobile.cart';
const money=v=>Number.isSafeInteger(v)?`${(v/100).toFixed(2)} ر.س`:'غير مسجل';
const statusLabel=v=>({active:'نشط',completed:'مكتمل',cancelled:'ملغى',queued:'بانتظار التجهيز',picking:'قيد التجهيز',awaiting_customer:'بانتظار قرارك',ready:'جاهز للتوصيل',unassigned:'بانتظار الإسناد',assigned:'مسند للمندوب',out_for_delivery:'في الطريق',delivered:'تم التسليم',failed:'تعذر التسليم',awaiting_collection:'بانتظار التحصيل',collected:'تم التحصيل',partially_refunded:'استرداد جزئي',refunded:'مسترد'})[v]||v;
const when=v=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{timeZone:'Asia/Riyadh',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(Number(v)>1e12?Number(v):Number(v)*1000));
const Btn=({title,onPress,kind='primary',disabled=false})=><Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.btn,kind==='outline'&&s.outline,disabled&&{opacity:.45}]}><Text style={[s.btnText,kind==='outline'&&s.outlineText]}>{title}</Text></Pressable>;
const Input=({label,...p})=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} {...p} textAlign="right" placeholderTextColor="#89928d" style={s.input}/></View>;
const Card=({children})=><View style={s.card}>{children}</View>;

export default function App(){
 const [token,setToken]=useState(null),[user,setUser]=useState(null),[screen,setScreen]=useState('shop'),[catalog,setCatalog]=useState([]),[cart,setCart]=useState([]),[orders,setOrders]=useState([]),[addresses,setAddresses]=useState([]),[favorites,setFavorites]=useState(new Set()),[notifications,setNotifications]=useState([]),[tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[quote,setQuote]=useState(null);
 const [catalogRefreshing,setCatalogRefreshing]=useState(false),[catalogError,setCatalogError]=useState('');
 const [cartReady,setCartReady]=useState(false),[savedTab,setSavedTab]=useState('lists');
 const total=useMemo(()=>cart.reduce((n,x)=>n+x.price_halalas*x.quantity,0),[cart]);
 useEffect(()=>{(async()=>{try{
  const saved=await AsyncStorage.getItem(CART_KEY);if(saved){const rows=JSON.parse(saved);if(!Array.isArray(rows))throw Error('تعذر قراءة السلة المحفوظة');setCart(rows)}setCartReady(true);
  const session=await restoreSession({storage:SecureStore,key:TOKEN_KEY,request});setToken(session.token);setUser(session.user);
  if(session.token)await refreshCustomerData(session.token);
 }catch(e){Alert.alert('تعذر تحميل البيانات',e.message)}finally{await reloadCatalog();setLoading(false)}})()},[]);
 useEffect(()=>{if(cartReady)AsyncStorage.setItem(CART_KEY,JSON.stringify(cart)).catch(()=>Alert.alert('السلة','تعذر حفظ السلة على الجهاز'))},[cart,cartReady]);
 async function reloadCatalog(){setCatalogRefreshing(true);setCatalogError('');try{setCatalog(await loadCatalog(request))}catch(e){setCatalogError(e.message||'تعذر تحميل المنتجات')}finally{setCatalogRefreshing(false)}}
 async function refreshCustomerData(t=token){if(!t)return;const [f,a]=await Promise.all([request('/api/favorites',{token:t}),request('/api/addresses',{token:t})]);setFavorites(new Set((f.items||[]).map(x=>x.offering_family_id)));setAddresses(a.items||[])}
 async function authed(fn){if(!token){setModal({type:'auth'});return}return fn()}
 function add(p,d=1){setCart(prev=>{const c=[...prev],i=c.findIndex(x=>x.offering_id===p.id);if(d>0&&((i>=0?c[i].quantity:0)>=Math.min(20,p.available_units||0)||i<0&&c.length>=40))return c;if(i<0&&d>0)c.push({offering_id:p.id,family_id:p.family_id,quantity:1,name:p.name,price_halalas:p.price_halalas,emoji:p.emoji||'🥬'});else if(i>=0){c[i]={...c[i],quantity:c[i].quantity+d};if(c[i].quantity<=0)c.splice(i,1)}return c})}
 async function login(email,password){const r=await request('/api/auth/login',{method:'POST',body:{email,password,mode:'mobile'}});await SecureStore.setItemAsync(TOKEN_KEY,r.access_token);setToken(r.access_token);setUser(r.user);await refreshCustomerData(r.access_token);setModal(null)}
 async function register(name,email,password,phone){await request('/api/auth/register',{method:'POST',body:{name,email,password,phone}});return login(email||phone,password)}
 async function logout(){if(token)await request('/api/auth/logout',{method:'POST',token});await SecureStore.deleteItemAsync(TOKEN_KEY);setToken(null);setUser(null);setFavorites(new Set());setOrders([]);setAddresses([]);setNotifications([]);setTickets([]);setQuote(null);setModal(null);setScreen('shop')}
 async function toggleFavorite(p){return authed(async()=>{const on=favorites.has(p.family_id);await request('/api/favorites'+(on?'/'+p.family_id:''),{method:on?'DELETE':'POST',token,body:on?undefined:{offering_family_id:p.family_id}});setFavorites(prev=>{const n=new Set(prev);on?n.delete(p.family_id):n.add(p.family_id);return n})})}
 async function loadOrders(){return authed(async()=>{const r=await request('/api/orders?limit=50',{token});setOrders(r.items||[]);setScreen('orders')})}
 function openSaved(tab){return authed(async()=>{setSavedTab(tab);setScreen('saved')})}
 async function loadNotifications(){return authed(async()=>{const r=await request('/api/notifications',{token});setNotifications(r.items||[]);setScreen('notifications')})}
 async function loadSupport(){return authed(async()=>{const r=await request('/api/tickets',{token});setTickets(r.items||[]);setScreen('support')})}
 async function checkout(){return authed(async()=>{const r=await request('/api/addresses',{token});setAddresses(r.items||[]);setModal({type:'addresses'})})}
 async function chooseAddress(id){const c=await request('/api/coverage/'+id,{token});if(!c.covered)throw Error(c.reason||'العنوان خارج التغطية');if(!(c.slots||[]).length)throw Error('لا توجد مواعيد متاحة');const features=await request('/api/features',{token});setModal({type:'slots',addressId:id,slots:c.slots,coupons:features.coupons===true})}
 async function createQuote(addressId,slotId,coupon_code=''){const q=await request('/api/quotes',{method:'POST',token,body:{address_id:addressId,slot_id:slotId,coupon_code,lines:cart.map(x=>({offering_id:x.offering_id,quantity:x.quantity}))}});setQuote(q);setModal({type:'quote'})}
 async function confirmOrder(){const o=await request('/api/orders',{method:'POST',token,body:{quote_id:quote.id}});setCart([]);setQuote(null);setModal({type:'done',order:o})}
 async function saveAddress(v,id){const body={label:v.label,details:v.details,recipient_name:v.recipient_name,recipient_phone:v.recipient_phone,latitude:String(v.latitude??''),longitude:String(v.longitude??''),city:v.city||'',district:v.district||'',street:v.street||'',building:v.building||'',floor:v.floor||'',apartment:v.apartment||'',notes:v.notes||'',is_default:!!v.is_default};await request('/api/addresses'+(id?'/'+id:''),{method:id?'PATCH':'POST',token,body});await refreshCustomerData();setModal({type:'addresses'})}
 async function deleteAddress(id){await request('/api/addresses/'+id,{method:'DELETE',token});await refreshCustomerData();setModal({type:'addresses'})}
 async function makeDefault(id){await request('/api/addresses/'+id+'/default',{method:'PATCH',token,body:{}});await refreshCustomerData();setModal({type:'addresses'})}
 async function openOrder(id){const o=await request('/api/orders/'+id,{token});setModal({type:'order',order:o})}
 async function decide(id,accept,orderId){await request(`/api/substitutions/${id}/decision`,{method:'POST',token,body:{accept}});return openOrder(orderId)}
 async function tracking(orderId){const t=await request(`/api/orders/${orderId}/tracking`,{token});setModal({type:'tracking',tracking:t})}
 async function refund(orderId,v){await request(`/api/orders/${orderId}/refunds`,{method:'POST',token,body:{component_id:v.component_id||null,amount_halalas:Math.round(Number(v.amount)*100),reason:v.reason}});return openOrder(orderId)}
 async function review(orderId,v){await request(`/api/orders/${orderId}/review`,{method:'POST',token,body:{rating:Number(v.rating),comment:v.comment}});return openOrder(orderId)}
 async function markRead(id){await request(`/api/notifications/${id}/read`,{method:'POST',token});return loadNotifications()}
 async function newTicket(v){await request('/api/tickets',{method:'POST',token,body:{subject:v.subject,message:v.message,category:v.category||'other',order_id:v.order_id||null}});setModal(null);return loadSupport()}
 async function replyTicket(id,message){await request(`/api/tickets/${id}/reply`,{method:'POST',token,body:{message}});setModal(null);return loadSupport()}
 if(loading)return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.center}><Text style={s.logo}>جَنى</Text><Text>جارٍ التحميل…</Text></View></SafeAreaView>;
 const props={modal,setModal,add,login,register,addresses,chooseAddress,createQuote,quote,confirmOrder,saveAddress,deleteAddress,makeDefault,decide,tracking,refund,review,newTicket,replyTicket};
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><View><Text style={s.logo}>جَنى</Text><Text style={s.muted}>خضار وفواكه وسلال</Text></View><Pressable onPress={()=>setScreen('cart')} style={s.cartBadge}><Text>🛍 {cart.reduce((n,x)=>n+x.quantity,0)}</Text></Pressable></View>
 <View style={s.body}>{['shop','favorites'].includes(screen)&&<Shop onCustom={()=>setScreen('builder')} refreshing={catalogRefreshing} onRefresh={reloadCatalog} error={catalogError} catalog={screen==='favorites'?catalog.filter(p=>favorites.has(p.family_id)):catalog} cart={cart} add={add} favorites={favorites} toggleFavorite={toggleFavorite} onProduct={product=>setModal({type:'product',product})}/>} {screen==='saved'&&<CustomerSaved key={savedTab} initialTab={savedTab} call={(path,options)=>request(path,{...options,token})} cart={cart} onCart={(next,catalog)=>{setCart(next);setCatalog(catalog);setScreen('cart')}} onProfile={p=>setUser(old=>({...old,...p}))} ui={{Card,Btn,Input,s,money,when}}/>} {screen==='builder'&&<BasketBuilder catalog={catalog} cart={cart} call={request} onAdd={(next,fresh)=>{setCart(next);setCatalog(fresh);setScreen('cart')}} ui={{Card,Btn,Input,s,money}}/>} {screen==='cloud-cart'&&<CloudCart key={user?.id} call={(path,options)=>request(path,{...options,token})} cart={cart} catalog={catalog} onRestore={(next,fresh)=>{setCart(next);setCatalog(fresh);setScreen('cart')}} ui={{Card,Btn,s,money,when}}/>} {screen==='cart'&&<Cart cart={cart} total={total} add={add} catalog={catalog} checkout={checkout} cloud={()=>authed(async()=>setScreen('cloud-cart'))}/>} {screen==='orders'&&<Orders orders={orders} openOrder={openOrder}/>} {screen==='notifications'&&<Notifications items={notifications} markRead={markRead}/>} {screen==='support'&&<Support items={tickets} setModal={setModal} replyTicket={replyTicket}/>} {screen==='account'&&<Account user={user} addresses={addresses} onAuth={()=>setModal({type:'auth'})} logout={logout} setModal={setModal} loadNotifications={loadNotifications} loadSupport={loadSupport} openSaved={openSaved} openFavorites={()=>authed(async()=>setScreen('favorites'))}/>}</View>
 <View style={s.nav}>{[['shop','المتجر'],['cart','السلة'],['orders','طلباتي'],['account','حسابي']].map(([k,t])=><Pressable key={k} onPress={()=>k==='orders'?loadOrders().catch(e=>Alert.alert('تعذر تحميل الطلبات',e.message)):setScreen(k)} style={s.navItem}><Text style={[s.navText,screen===k&&s.navActive]}>{t}</Text></Pressable>)}</View>
 <AppModal {...props}/></SafeAreaView>
}
function Shop({catalog,cart,add,favorites,toggleFavorite,onProduct,refreshing,onRefresh,error,onCustom}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all');const products=catalog.filter(p=>(category==='all'||p.category===category)&&String(p.name+' '+(p.description||'')).includes(query.trim()));
 return <FlatList refreshing={refreshing} onRefresh={onRefresh} contentContainerStyle={s.list} data={products} keyExtractor={x=>x.id} numColumns={2} columnWrapperStyle={{gap:10}} ListEmptyComponent={<Card><Text>لا توجد أصناف تطابق اختيارك.</Text></Card>} ListHeaderComponent={<View style={s.hero}>{error!==''&&<Card><Text accessibilityRole="alert">{error}</Text><Btn title="إعادة تحميل المنتجات" disabled={refreshing} onPress={onRefresh}/></Card>}<Text style={s.eyebrow}>خير اليوم على بابك</Text><Text style={s.heroTitle}>اختيارات طازجة من جازان</Text><Text style={s.muted}>الدفع عند الاستلام، والبدائل بموافقتك.</Text><Btn title="كوّن سلتك" kind="outline" onPress={onCustom}/><Input label="البحث عن منتج" value={query} onChangeText={setQuery}/><View style={s.row}>{[['all','الكل'],['fruit','فواكه'],['vegetables','خضار'],['baskets','سلال']].map(([k,label])=><Btn key={k} title={label} kind={category===k?'primary':'outline'} onPress={()=>setCategory(k)}/>)}</View></View>} renderItem={({item:p})=>{const line=cart.find(x=>x.offering_id===p.id),fav=favorites.has(p.family_id);return <View style={s.product}><Pressable accessibilityLabel={fav?'إزالة من المفضلة':'إضافة للمفضلة'} onPress={()=>toggleFavorite(p).catch(e=>Alert.alert('تعذر التنفيذ',e.message))}><Text style={s.favorite}>{fav?'♥':'♡'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={'تفاصيل '+p.name} onPress={()=>onProduct(p)}><Text style={s.emoji}>{p.emoji||'🥬'}</Text><Text style={s.productTitle}>{p.name}</Text><Text style={s.muted}>{p.size_label||p.sale_unit||''}</Text></Pressable><Text style={s.price}>{money(p.price_halalas)}</Text><View style={s.row}>{line&&<Btn title="−" kind="outline" onPress={()=>add(p,-1)}/>}<Btn title={line?String(line.quantity):'+'} onPress={()=>add(p,1)} disabled={p.available_units<1}/></View></View>}}/>
}

function Cart({cart,total,add,catalog,checkout,cloud}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>سلتك</Text><Btn title="حفظ السلة لحسابي أو استعادتها" kind="outline" onPress={cloud}/>{cart.map(x=>{const p=catalog.find(p=>p.id===x.offering_id)||{...x,id:x.offering_id,available_units:0};return <Card key={x.offering_id}><View style={s.between}><View><Text style={s.productTitle}>{x.emoji} {x.name}</Text><Text style={s.price}>{money(x.price_halalas*x.quantity)}</Text></View><View style={s.row}><Btn title="−" kind="outline" onPress={()=>add(p,-1)}/><Text>{x.quantity}</Text><Btn title="+" onPress={()=>add(p,1)}/></View></View></Card>})}{!cart.length?<Card><Text>السلة فارغة.</Text></Card>:<><Card><View style={s.between}><Text>الإجمالي المبدئي</Text><Text style={s.price}>{money(total)}</Text></View></Card><Btn title="المتابعة للعنوان والموعد" onPress={()=>checkout().catch(e=>Alert.alert('تعذر المتابعة',e.message))}/></>}</ScrollView>}
function Orders({orders,openOrder}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>طلباتك</Text>{orders.length?orders.map(o=><Pressable key={o.id} onPress={()=>openOrder(o.id).catch(e=>Alert.alert('خطأ',e.message))}><Card><View style={s.between}><Text style={s.productTitle}>{o.number}</Text><Text>{statusLabel(o.status)}</Text></View><Text>{statusLabel(o.fulfillment_state)} · {statusLabel(o.delivery_state)}</Text><Text style={s.price}>{money(o.total_halalas)}</Text></Card></Pressable>):<Card><Text>لا توجد طلبات.</Text></Card>}</ScrollView>}
function Notifications({items,markRead}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>الإشعارات</Text>{items.map(n=><Pressable key={n.id} onPress={()=>markRead(n.id).catch(e=>Alert.alert('تعذر تحديث الإشعار',e.message))}><Card><Text style={s.productTitle}>{n.title||'إشعار'}</Text><Text>{n.message||n.body||''}</Text><Text style={s.muted}>{n.is_read?'مقروء':'جديد'}</Text></Card></Pressable>)}</ScrollView>}
function Support({items,setModal,replyTicket}){return <ScrollView contentContainerStyle={s.list}><View style={s.between}><Text style={s.pageTitle}>الدعم</Text><Btn title="+ تذكرة" onPress={()=>setModal({type:'ticket'})}/></View>{items.map(t=><Card key={t.id}><Text style={s.productTitle}>{t.subject}</Text><Text>{({open:'مفتوحة',pending_customer:'بانتظار ردك',closed:'مغلقة'})[t.state]||t.state}</Text><Text style={s.muted}>{t.messages?.at?.(-1)?.text||''}</Text><Btn title="المحادثة والرد" kind="outline" onPress={()=>setModal({type:'reply',ticket:t})}/></Card>)}</ScrollView>}
function Account({user,addresses,onAuth,logout,setModal,loadNotifications,loadSupport,openSaved,openFavorites}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>حسابي</Text>{user?<><Card><Text style={s.productTitle}>{user.name}</Text><Text>{user.email||user.phone}</Text><Btn title="العناوين" kind="outline" onPress={()=>setModal({type:'addresses'})}/><Btn title="بياناتي وتفضيلاتي" kind="outline" onPress={()=>openSaved('profile').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="قوائم التسوق" kind="outline" onPress={()=>openSaved('lists').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="تذكيرات التسوق" kind="outline" onPress={()=>openSaved('plans').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="المفضلة" kind="outline" onPress={openFavorites}/><Btn title="الإشعارات" kind="outline" onPress={()=>loadNotifications().catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="الدعم" kind="outline" onPress={()=>loadSupport().catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="تسجيل الخروج" kind="outline" onPress={()=>logout().catch(e=>Alert.alert('تعذر الخروج',e.message))}/></Card><Text style={s.muted}>العناوين المحفوظة: {addresses.length}</Text></>:<Card><Text>سجّل الدخول للمتابعة.</Text><Btn title="تسجيل الدخول / حساب جديد" onPress={onAuth}/></Card>}</ScrollView>}
function AppModal(p){const {modal,setModal,add,login,register,addresses,chooseAddress,createQuote,quote,confirmOrder,saveAddress,deleteAddress,makeDefault,decide,tracking,refund,review,newTicket,replyTicket}=p;const [mode,setMode]=useState('login'),[f,setF]=useState({}),[busy,setBusy]=useState(false);useEffect(()=>{setF({});if(modal?.type==='auth')setMode('login')},[modal?.type]);if(!modal)return null;const run=async fn=>{try{setBusy(true);await fn()}catch(e){Alert.alert('تعذر التنفيذ',e.message)}finally{setBusy(false)}};const order=modal.order;return <Modal visible transparent animationType="slide" onRequestClose={()=>setModal(null)}><KeyboardAvoidingView style={s.overlay} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.sheet}><View style={s.between}><Text style={s.pageTitle}>{titles[modal.type]||'جَنى'}</Text><Pressable onPress={()=>setModal(null)}><Text style={s.close}>×</Text></Pressable></View><ScrollView keyboardShouldPersistTaps="handled">
 {modal.type==='product'&&<><Text style={s.emoji}>{modal.product.emoji||'🥬'}</Text><Text style={s.productTitle}>{modal.product.name}</Text><Text>{modal.product.description}</Text><Text>{modal.product.size_label}</Text><Text style={s.price}>{money(modal.product.price_halalas)}</Text>{(modal.product.components||[]).map((c,i)=><Text key={c.stock_id||String(i)}>{c.name} — {c.base_qty} {c.base_unit==='piece'?'قطعة':'جرام'}</Text>)}<Btn title="إضافة للسلة" disabled={modal.product.available_units<1} onPress={()=>{add(modal.product,1);setModal(null)}}/></>}
 {modal.type==='auth'&&<><Text style={s.muted}>{mode==='login'?'أدخل بياناتك.':'أنشئ حساب عميل.'}</Text>{mode==='register'&&<Input label="الاسم" value={f.name||''} onChangeText={v=>setF({...f,name:v})}/>}{mode==='register'&&<Input label="رقم الجوال" keyboardType="phone-pad" value={f.phone||''} onChangeText={v=>setF({...f,phone:v})}/>}<Input label={mode==='register'?'البريد (اختياري عند إدخال الجوال)':'البريد أو رقم الجوال'} autoCapitalize="none" value={f.email||''} onChangeText={v=>setF({...f,email:v})}/><Input label="كلمة المرور" secureTextEntry value={f.password||''} onChangeText={v=>setF({...f,password:v})}/><Btn disabled={busy} title={mode==='login'?'تسجيل الدخول':'إنشاء الحساب'} onPress={()=>run(()=>mode==='login'?login(f.email,f.password):register(f.name,f.email,f.password,f.phone))}/><Pressable onPress={()=>setMode(mode==='login'?'register':'login')}><Text style={s.link}>{mode==='login'?'إنشاء حساب جديد':'لدي حساب'}</Text></Pressable></>}
 {modal.type==='addresses'&&<><Btn title="+ عنوان جديد" onPress={()=>setModal({type:'addressEdit'})}/>{addresses.map(a=><Card key={a.id}><Text style={s.productTitle}>{a.label}{a.is_default?' · افتراضي':''}</Text><Text>{a.details}</Text><View style={s.row}><Btn title="اختيار" onPress={()=>run(()=>chooseAddress(a.id))}/><Btn title="تعديل" kind="outline" onPress={()=>setModal({type:'addressEdit',address:a})}/>{!a.is_default&&<Btn title="افتراضي" kind="outline" onPress={()=>run(()=>makeDefault(a.id))}/>}<Btn title="حذف" kind="outline" onPress={()=>run(()=>deleteAddress(a.id))}/></View></Card>)}</>}
 {modal.type==='addressEdit'&&<AddressEditor address={modal.address} f={f} setF={setF} onSave={()=>run(()=>saveAddress({...modal.address,...f,is_default:f.is_default??modal.address?.is_default},modal.address?.id))}/>} 
 {modal.type==='slots'&&modal.coupons&&<Input label="رمز القسيمة (اختياري)" autoCapitalize="characters" value={f.coupon_code||''} onChangeText={v=>setF({...f,coupon_code:v})}/>}
 {modal.type==='slots'&&modal.slots.map(sl=><Pressable key={sl.id} onPress={()=>run(()=>createQuote(modal.addressId,sl.id,f.coupon_code||''))}><Card><Text style={s.productTitle}>{when(sl.starts_at)}</Text><Text>التوصيل {money(sl.fee_halalas)} · المتاح {sl.available}</Text></Card></Pressable>)}
 {modal.type==='quote'&&quote&&<><Card>{(quote.lines||[]).map(x=><View key={x.offering_id||x.line_id} style={s.between}><Text>{x.name} × {x.qty}</Text><Text>{money(x.line_total_halalas)}</Text></View>)}{quote.discount_halalas>0&&<Text>خصم {quote.coupon?.code}: −{money(quote.discount_halalas)}</Text>}<Text>التوصيل {money(quote.delivery_fee_halalas)}</Text><Text style={s.price}>الإجمالي {money(quote.total_halalas)}</Text></Card><Btn title="تأكيد الطلب COD" onPress={()=>run(confirmOrder)}/></>}
 {modal.type==='done'&&<Card><Text style={s.productTitle}>تم تأكيد {modal.order.number}</Text><Text>{modal.order.delivery_code?`رمز التسليم: ${modal.order.delivery_code}`:'تابع الطلب من صفحة طلباتي.'}</Text></Card>}
 {modal.type==='order'&&order&&<><Card><Text style={s.productTitle}>{order.number}</Text><Text>{statusLabel(order.fulfillment_state)} · {statusLabel(order.delivery_state)} · {statusLabel(order.payment_state)}</Text><Text style={s.price}>{money(order.total_halalas)}</Text></Card>{(order.substitutions||[]).map(x=><Substitution key={x.id} sub={x} onDecision={accept=>run(()=>decide(x.id,accept,order.id))}/>)}<Btn title="تتبع الطلب" kind="outline" onPress={()=>run(()=>tracking(order.id))}/>{(order.refunds||[]).map(r=><Card key={r.id}><Text style={s.productTitle}>{money(r.amount_halalas)} · {({requested:'قيد المراجعة',processing:'قيد المعالجة',completed:'سُجّل إرجاع المبلغ',rejected:'مرفوض',failed:'تعذر الإكمال'})[r.state]||r.state}</Text><Text>{r.reason}</Text>{r.decision_note&&<Text>{r.decision_note}</Text>}</Card>)}{order.delivery_state==='delivered'&&<><Btn title="طلب استرداد" kind="outline" onPress={()=>setModal({type:'refund',order})}/><Btn title="تقييم الطلب" kind="outline" onPress={()=>setModal({type:'review',order})}/></>}<Btn title="الدعم" kind="outline" onPress={()=>setModal({type:'ticket',order_id:order.id})}/></>}
 {modal.type==='tracking'&&<Card><Text style={s.productTitle}>حالة التوصيل</Text><Text>{JSON.stringify(modal.tracking,null,2)}</Text></Card>}
 {modal.type==='refund'&&<><Text>هذا طلب مراجعة. لا يُعد المبلغ مستردًا حتى يؤكد فريق المالية إرجاعه.</Text><Input label="المبلغ بالريال" keyboardType="decimal-pad" value={f.amount||''} onChangeText={v=>setF({...f,amount:v})}/><Input label="السبب" value={f.reason||''} onChangeText={v=>setF({...f,reason:v})}/><Btn title="إرسال طلب الاسترداد" onPress={()=>run(()=>refund(modal.order.id,f))}/></>}
 {modal.type==='review'&&<><Input label="التقييم من 1 إلى 5" keyboardType="number-pad" value={f.rating||''} onChangeText={v=>setF({...f,rating:v})}/><Input label="التعليق" value={f.comment||''} onChangeText={v=>setF({...f,comment:v})}/><Btn title="إرسال التقييم" onPress={()=>run(()=>review(modal.order.id,f))}/></>}
 {modal.type==='ticket'&&<><Text style={s.productTitle}>نوع المساعدة</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[['order','طلب'],['product','منتج'],['delivery','توصيل'],['refund','استرداد'],['account','حساب'],['other','أخرى']].map(([key,label])=><Btn key={key} title={label} kind={(f.category||'other')===key?'primary':'outline'} onPress={()=>setF({...f,category:key})}/>)}</View><Input label="الموضوع" value={f.subject||''} onChangeText={v=>setF({...f,subject:v})}/><Input label="الرسالة" multiline value={f.message||''} onChangeText={v=>setF({...f,message:v})}/><Btn title="فتح التذكرة" onPress={()=>run(()=>newTicket({...f,order_id:modal.order_id}))}/></>}
 {modal.type==='reply'&&<>{(modal.ticket.messages||[]).map((m,i)=><Card key={m.id||String(i)}><Text style={s.productTitle}>{m.actor==='customer'?'أنت':'خدمة العملاء'}</Text><Text>{m.text||m.message||''}</Text></Card>)}{modal.ticket.state==='closed'&&<Text>إرسال رد جديد يعيد فتح التذكرة.</Text>}<Input label="الرد" multiline value={f.message||''} onChangeText={v=>setF({...f,message:v})}/><Btn title="إرسال الرد" onPress={()=>run(()=>replyTicket(modal.ticket.id,f.message))}/></>}
 </ScrollView></View></KeyboardAvoidingView></Modal>}
function AddressEditor({address,f,setF,onSave}){const v=k=>f[k]??address?.[k]??'';return <><Input label="اسم العنوان" value={String(v('label'))} onChangeText={x=>setF({...f,label:x})}/>{[['city','المدينة'],['district','الحي'],['street','الشارع'],['building','المبنى'],['floor','الدور'],['apartment','الشقة'],['notes','ملاحظات التوصيل']].map(([k,label])=><Input key={k} label={label} value={String(v(k))} onChangeText={x=>setF({...f,[k]:x})}/>)}<Input label="تفاصيل العنوان" value={String(v('details'))} onChangeText={x=>setF({...f,details:x})}/><Input label="اسم المستلم" value={String(v('recipient_name'))} onChangeText={x=>setF({...f,recipient_name:x})}/><Input label="رقم الجوال" value={String(v('recipient_phone'))} onChangeText={x=>setF({...f,recipient_phone:x})}/><Input label="خط العرض" keyboardType="decimal-pad" value={String(v('latitude'))} onChangeText={x=>setF({...f,latitude:x})}/><Input label="خط الطول" keyboardType="decimal-pad" value={String(v('longitude'))} onChangeText={x=>setF({...f,longitude:x})}/><Btn title="حفظ العنوان" onPress={onSave}/></>}
const titles={product:'تفاصيل المنتج',auth:'الدخول',addresses:'العناوين',addressEdit:'تعديل العنوان',slots:'موعد التوصيل',quote:'مراجعة الطلب',done:'تم الطلب',order:'تفاصيل الطلب',tracking:'تتبع الطلب',refund:'استرداد',review:'التقييم',ticket:'الدعم',reply:'رد الدعم'};
const s=StyleSheet.create({safe:{flex:1,direction:'rtl',backgroundColor:'#f7f7ef'},body:{flex:1},header:{padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:'#e4e7df'},logo:{fontSize:28,fontWeight:'800',color:'#1b563d'},muted:{color:'#6f7973'},cartBadge:{padding:10,backgroundColor:'#fff',borderRadius:14},list:{padding:16,gap:10},hero:{paddingVertical:12,gap:6},eyebrow:{color:'#1b563d',fontWeight:'700'},heroTitle:{fontSize:28,fontWeight:'800'},product:{flex:1,backgroundColor:'#fff',padding:12,borderRadius:18,marginBottom:10,minHeight:210},favorite:{fontSize:24,color:'#a53737',textAlign:'left'},emoji:{fontSize:42,textAlign:'center'},productTitle:{fontSize:17,fontWeight:'700'},price:{fontWeight:'800',color:'#1b563d',fontSize:17},row:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},card:{backgroundColor:'#fff',padding:14,borderRadius:16,gap:8,marginBottom:8},btn:{backgroundColor:'#1b563d',minHeight:44,minWidth:44,paddingVertical:10,paddingHorizontal:14,borderRadius:12,alignItems:'center'},outline:{backgroundColor:'#fff',borderWidth:1,borderColor:'#1b563d'},btnText:{color:'#fff',fontWeight:'700'},outlineText:{color:'#1b563d'},nav:{flexDirection:'row',borderTopWidth:1,borderColor:'#e4e7df',backgroundColor:'#fff'},navItem:{flex:1,padding:14,alignItems:'center'},navText:{color:'#6f7973'},navActive:{color:'#1b563d',fontWeight:'800'},pageTitle:{fontSize:24,fontWeight:'800'},center:{flex:1,alignItems:'center',justifyContent:'center'},overlay:{flex:1,backgroundColor:'#0005',justifyContent:'flex-end'},sheet:{backgroundColor:'#f7f7ef',padding:18,borderTopLeftRadius:24,borderTopRightRadius:24,maxHeight:'90%'},close:{fontSize:32},field:{gap:6,marginBottom:10},label:{fontWeight:'700'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d9ddd6',borderRadius:12,padding:12},link:{textAlign:'center',padding:14,color:'#1b563d',fontWeight:'700'}});

function Substitution({sub,onDecision}){
 const t=sub.proposed||{},original=t.original_line||{},replacement=t.replacement_line||{},pending=sub.state==='pending'&&Number(sub.expires_at)>Date.now();
 const complete=!!replacement.name&&Number.isSafeInteger(t.total_halalas)&&Number.isSafeInteger(t.price_difference_halalas);
 const amount=v=>Number.isSafeInteger(v)?money(v):'غير مسجل';
 const components=line=>(line.components||[]).map(c=>`${c.name}: ${c.base_qty*line.qty} ${c.base_unit==='piece'?'قطعة':'جرام'}`).join('، ');
 return <Card><Text style={s.productTitle}>اقتراح استبدال · {({pending:'بانتظار قرارك',accepted:'وافقت عليه',rejected:'مرفوض',expired:'انتهت المهلة'})[sub.state]||sub.state}</Text><Text>الأصلي: {original.name||'تفاصيل غير متاحة'} × {original.qty}</Text><Text>{components(original)}</Text><Text>البديل: {replacement.name||'تفاصيل غير متاحة'} × {replacement.qty}</Text><Text>{components(replacement)}</Text><Text>الإجمالي السابق: {amount(t.original_total_halalas)}</Text><Text>فرق الإجمالي: {amount(t.price_difference_halalas)}</Text><Text style={s.price}>الإجمالي عند الموافقة: {amount(t.total_halalas)}</Text>{sub.state==='pending'&&<Text>المهلة: {when(sub.expires_at)}. يُفحص توفر المخزون عند الموافقة. عدم الرد لا يعني الموافقة.</Text>}{pending&&<><Btn title="أوافق على البديل والإجمالي" disabled={!complete} onPress={()=>Alert.alert('تأكيد البديل',`هل توافق على البديل بإجمالي ${amount(t.total_halalas)}؟`,[{text:'رجوع',style:'cancel'},{text:'أوافق',onPress:()=>onDecision(true)}])}/><Btn title="أرفض البديل" kind="outline" onPress={()=>onDecision(false)}/></>}</Card>
}
