import {createCartStore,changeCartQuantity} from './local-cart.mjs';
import {moneyValue,integerValue} from './input.mjs';
import {mergeSavedCart} from './saved-cart.mjs';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,FlatList,KeyboardAvoidingView,Linking,Modal,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import * as SecureStore from 'expo-secure-store';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {createApiClient,restoreSession} from './api.mjs';
import CustomerSaved from './CustomerSaved.js';
import CloudCart from './CloudCart.js';
import BasketBuilder from './BasketBuilder.js';
import {loadCatalog} from './catalog.mjs';
import ProductImage from './ProductImage.js';
import StorePolicies from './StorePolicies.js';
import AddressEditor from './AddressEditor.js';
import OrderDetails from './OrderDetails.js';
import PasswordEditor from './PasswordEditor.js';
import CheckoutReview from './CheckoutReview.js';
import {createCheckoutSession,cartMatchesQuote} from './checkout.mjs';
import {orderFacts,orderPageUrl,appendOrderPage} from './order.mjs';
import {addressPayload,googleMapsLink} from './address.mjs';

const API=process.env.EXPO_PUBLIC_API_BASE||'https://jana-fresh-app.onrender.com';
const request=createApiClient({base:API,storage:SecureStore});
const TOKEN_KEY='jana.mobile.token',CART_KEY='jana.mobile.cart';
const money=v=>Number.isSafeInteger(v)?`${(v/100).toFixed(2)} ر.س`:'غير مسجل';
const statusLabel=v=>({active:'نشط',completed:'مكتمل',cancelled:'ملغى',queued:'بانتظار التجهيز',picking:'قيد التجهيز',awaiting_customer:'بانتظار قرارك',ready:'جاهز للتوصيل',unassigned:'بانتظار الإسناد',assigned:'مسند للمندوب',out_for_delivery:'في الطريق',delivered:'تم التسليم',failed:'تعذر التسليم',awaiting_collection:'بانتظار التحصيل',collected:'تم التحصيل',partially_refunded:'استرداد جزئي',refunded:'مسترد'})[v]||v;
const when=v=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory-nu-latn',{timeZone:'Asia/Riyadh',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(Number(v)>1e12?Number(v):Number(v)*1000));
const Btn=({title,onPress,kind='primary',disabled=false})=><Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[s.btn,kind==='outline'&&s.outline,disabled&&{opacity:.45}]}><Text style={[s.btnText,kind==='outline'&&s.outlineText]}>{title}</Text></Pressable>;
const Input=({label,...p})=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} {...p} textAlign="right" placeholderTextColor="#89928d" style={s.input}/></View>;
const Card=({children})=><View style={s.card}>{children}</View>;

export default function App(){
 const [token,setToken]=useState(null),[user,setUser]=useState(null),[screen,setScreen]=useState('shop'),[catalog,setCatalog]=useState([]),[cart,setCart]=useState([]),[orders,setOrders]=useState([]),[addresses,setAddresses]=useState([]),[favorites,setFavorites]=useState(new Set()),[notifications,setNotifications]=useState([]),[tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[modal,setModal]=useState(null);
 const customerSession=useRef(null);
 const [cartState,setCartState]=useState({ready:false,busy:false,error:null}),cartStoreRef=useRef(null);
 if(!cartStoreRef.current)cartStoreRef.current=createCartStore({storage:AsyncStorage,key:CART_KEY,onChange:snapshot=>{setCart(snapshot.items);setCartState(snapshot)}});
 const cartStore=cartStoreRef.current;
 const [checkoutView,setCheckoutView]=useState({pending:null,quote:null,busy:false,error:''}),checkoutRef=useRef(null);
 if(!checkoutRef.current)checkoutRef.current=createCheckoutSession({storage:{getItem:SecureStore.getItemAsync,setItem:SecureStore.setItemAsync,removeItem:SecureStore.deleteItemAsync},call:request,getSession:()=>customerSession.current,onChange:setCheckoutView});
 const checkoutSession=checkoutRef.current;
 const [catalogRefreshing,setCatalogRefreshing]=useState(false),[catalogError,setCatalogError]=useState('');
 const [storefront,setStorefront]=useState(null);
 const [ordersNext,setOrdersNext]=useState(null),[ordersBusy,setOrdersBusy]=useState(false);
 const ordersRequest=useRef(0),ordersLoading=useRef(false),sessionToken=useRef(token);
 const [savedTab,setSavedTab]=useState('lists'),[accountError,setAccountError]=useState(''),[accountBusy,setAccountBusy]=useState(false),accountLoading=useRef(false),accountGeneration=useRef(0);
 const total=useMemo(()=>cart.reduce((n,x)=>n+x.price_halalas*x.quantity,0),[cart]);
 useEffect(()=>{Promise.allSettled([cartStore.load(),loadAccount(),reloadCatalog()]).finally(()=>setLoading(false))},[]);
 async function loadAccount(){
  if(accountLoading.current)return;accountLoading.current=true;const generation=++accountGeneration.current;setAccountBusy(true);setAccountError('');
  try{
   const session=await restoreSession({storage:SecureStore,key:TOKEN_KEY,request});if(generation!==accountGeneration.current)return;
   sessionToken.current=session.token;customerSession.current=session.token?{owner:session.user.id,token:session.token}:null;setToken(session.token);setUser(session.user);
   if(session.token){await checkoutSession.load();await refreshCustomerData(session.token);}
  }catch(e){if(generation===accountGeneration.current)setAccountError(e.message||'تعذر تحميل الحساب. أعد المحاولة.');}
  finally{if(generation===accountGeneration.current){accountLoading.current=false;setAccountBusy(false);}}
 }
 const saveCart=next=>cartStore.update(()=>next);
 const retryCart=()=>cartStore.load().catch(()=>{});
 const resetCart=()=>Alert.alert('مسح سلة الجهاز','مسح سلة هذا الجهاز فقط؟ لن تُلغى طلباتك أو النسخة المحفوظة في حسابك.',[{text:'رجوع',style:'cancel'},{text:'مسح السلة',style:'destructive',onPress:()=>cartStore.reset().catch(()=>{})}]);
 async function reloadCatalog(){setCatalogRefreshing(true);setCatalogError('');try{const [products,store]=await Promise.all([loadCatalog(request),request('/api/storefront')]);setCatalog(products);setStorefront(store)}catch(e){setCatalogError(e.message||'تعذر تحميل المنتجات')}finally{setCatalogRefreshing(false)}}
 async function refreshCustomerData(t=token){if(!t)return;const [f,a]=await Promise.all([request('/api/favorites',{token:t}),request('/api/addresses',{token:t})]);if(sessionToken.current!==t)return;setFavorites(new Set((f.items||[]).map(x=>x.offering_family_id)));setAddresses(a.items||[])}
 async function authed(fn){if(accountLoading.current||accountError){setScreen('account');throw Error('تعذر إكمال تحميل الحساب. استخدم إعادة تحميل الحساب للمتابعة.')}if(!token){setModal({type:'auth'});return}return fn()}
 async function add(p,delta=1){try{await cartStore.update(items=>changeCartQuantity(items,p,delta));return true;}catch(e){Alert.alert('السلة',e.message);return false;}}
 async function login(email,password){accountGeneration.current++;accountLoading.current=false;setAccountBusy(false);const r=await request('/api/auth/login',{method:'POST',body:{email,password,mode:'mobile'}});await SecureStore.setItemAsync(TOKEN_KEY,r.access_token);sessionToken.current=r.access_token;customerSession.current={owner:r.user.id,token:r.access_token};setToken(r.access_token);setUser(r.user);setAccountError('');setModal(null);try{await checkoutSession.load();await refreshCustomerData(r.access_token)}catch(e){setAccountError(e.message)}}
 async function register(name,email,password,phone){await request('/api/auth/register',{method:'POST',body:{name,email,password,phone}});return login(email||phone,password)}
 async function forgetSession(){
  accountGeneration.current++;accountLoading.current=false;setAccountBusy(false);setAccountError('');customerSession.current=null;const forgottenCheckout=checkoutSession.forget();sessionToken.current=null;ordersRequest.current++;ordersLoading.current=false;setOrdersBusy(false);setOrdersNext(null);setToken(null);setUser(null);setFavorites(new Set());setOrders([]);setAddresses([]);setNotifications([]);setTickets([]);setModal(null);setScreen('account');
  const removed=await Promise.allSettled([forgottenCheckout,SecureStore.deleteItemAsync(TOKEN_KEY),SecureStore.deleteItemAsync('jana.mobile.retry.v1')]);
  if(removed.some(r=>r.status==='rejected'))Alert.alert('تخزين الجهاز','تعذر مسح بعض بيانات الجلسة من تخزين الجهاز. أغلق التطبيق وأعد فتحه للتحقق من الجلسة.');
 }
 async function logout(){let failed=false;try{if(token)await request('/api/auth/logout',{method:'POST',token})}catch(e){failed=e.status!==401}finally{await forgetSession()}if(failed)Alert.alert('تم الخروج من هذا الجهاز','تعذر تأكيد إنهاء جلسة الخادم بسبب الاتصال.');}
 async function changePassword(current_password,new_password){await request('/api/auth/password',{method:'POST',token,body:{current_password,new_password}});await forgetSession();Alert.alert('تم تغيير كلمة المرور','انتهت جلسات حسابك. سجّل الدخول بكلمة المرور الجديدة.');}
 async function toggleFavorite(p){return authed(async()=>{const on=favorites.has(p.family_id);await request('/api/favorites'+(on?'/'+p.family_id:''),{method:on?'DELETE':'POST',token,body:on?undefined:{offering_family_id:p.family_id}});setFavorites(prev=>{const n=new Set(prev);on?n.delete(p.family_id):n.add(p.family_id);return n})})}
 async function loadOrders(more=false){return authed(async()=>{
  if(ordersLoading.current)return;ordersLoading.current=true;setOrdersBusy(true);setScreen('orders');const generation=++ordersRequest.current;
  try{const r=await request(orderPageUrl(more?ordersNext:null),{token});if(generation!==ordersRequest.current||sessionToken.current!==token)return;setOrders(rows=>more?appendOrderPage(rows,r.items||[]):r.items||[]);setOrdersNext(r.next)}
  finally{if(generation===ordersRequest.current){ordersLoading.current=false;setOrdersBusy(false)}}
 })}
 function openSaved(tab){return authed(async()=>{setSavedTab(tab);setScreen('saved')})}
 async function loadNotifications(){return authed(async()=>{const r=await request('/api/notifications',{token});if(sessionToken.current!==token)return;setNotifications(r.items||[]);setScreen('notifications')})}
 async function loadSupport(){return authed(async()=>{const r=await request('/api/tickets',{token});if(sessionToken.current!==token)return;setTickets(r.items||[]);setScreen('support')})}
 async function checkout(){await cartStore.flush();if(checkoutSession.snapshot.pending)return resumeCheckout();const store=await request('/api/storefront');setStorefront(store);if(!store.accepting_orders)throw Error(store.message||'استقبال الطلبات الجديدة متوقف حاليًا');return authed(async()=>{const r=await request('/api/addresses',{token});setAddresses(r.items||[]);setModal({type:'addresses',checkout:true})})}
 async function chooseAddress(id){const c=await request('/api/coverage/'+id,{token});if(!c.covered)throw Error(c.reason||'العنوان خارج التغطية');if(!(c.slots||[]).length)throw Error('لا توجد مواعيد متاحة');const features=await request('/api/features',{token});setModal({type:'slots',addressId:id,slots:c.slots,coupons:features.coupons===true})}
 async function createQuote(addressId,slotId,coupon_code=''){
  try{const current=await cartStore.flush();const q=await checkoutSession.create({address_id:addressId,slot_id:slotId,coupon_code,lines:current.map(x=>({offering_id:x.offering_id,quantity:x.quantity}))});if(q)setModal({type:'quote'})}
  catch(e){if(checkoutSession.snapshot.pending)setModal({type:'quote'});throw e}
 }
 async function resumeCheckout(){setModal({type:'quote'});await checkoutSession.refresh()}
 async function finishCheckout(){
  const session=customerSession.current;let cartKept=false;
  const order=await checkoutSession.acknowledge(q=>cartStore.update(items=>{
   if(customerSession.current!==session)return items;
   if(q.order.status!=='cancelled'&&cartMatchesQuote(items,q))return [];
   cartKept=items.length>0;return items;
  }));
  if(order&&customerSession.current===session){if(order.status==='cancelled')await openOrder(order.id);else setModal({type:'done',order,cartKept})}
 }
 async function saveAddress(v,id,checkout=false){const saved=await request('/api/addresses'+(id?'/'+id:''),{method:id?'PATCH':'POST',token,body:addressPayload(v)});setAddresses(rows=>[...rows.filter(a=>a.id!==saved.id).map(a=>saved.is_default?{...a,is_default:false}:a),saved]);setModal({type:'addresses',checkout});try{await refreshCustomerData()}catch{Alert.alert('تم حفظ العنوان','تعذر تحديث بقية بيانات الحساب الآن. عنوانك محفوظ بالفعل.')}}
 async function deleteAddress(id,checkout=false){await request('/api/addresses/'+id,{method:'DELETE',token});await refreshCustomerData();setModal({type:'addresses',checkout})}
 async function makeDefault(id,checkout=false){await request('/api/addresses/'+id+'/default',{method:'PATCH',token,body:{}});await refreshCustomerData();setModal({type:'addresses',checkout})}
 async function openOrder(id){const o=await request('/api/orders/'+id,{token});if(sessionToken.current!==token)return;setOrders(rows=>rows.map(row=>row.id===o.id?{...row,...o}:row));setModal({type:'order',order:o})}
 async function decide(id,accept,orderId){await request(`/api/substitutions/${id}/decision`,{method:'POST',token,body:{accept}});return openOrder(orderId)}
 async function refund(orderId,v){await request(`/api/orders/${orderId}/refunds`,{method:'POST',token,body:{component_id:v.component_id||null,amount_halalas:moneyValue(v.amount),reason:v.reason}});return openOrder(orderId)}
 async function review(orderId,v){await request(`/api/orders/${orderId}/review`,{method:'POST',token,body:{rating:integerValue(v.rating,{min:1,max:5,label:'التقييم'}),comment:v.comment}});return openOrder(orderId)}
 async function markRead(id){await request(`/api/notifications/${id}/read`,{method:'POST',token});return loadNotifications()}
 async function newTicket(v){await request('/api/tickets',{method:'POST',token,body:{subject:v.subject,message:v.message,category:v.category||'other',order_id:v.order_id||null}});setModal(null);return loadSupport()}
 async function replyTicket(id,message){await request(`/api/tickets/${id}/reply`,{method:'POST',token,body:{message}});setModal(null);return loadSupport()}
 if(loading)return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.center}><Text style={s.logo}>جَنى</Text><Text>جارٍ التحميل…</Text></View></SafeAreaView>;
 const props={user,token,modal,setModal,add,login,register,addresses,chooseAddress,createQuote,checkoutSession,checkoutView,finishCheckout,saveAddress,deleteAddress,makeDefault,decide,openOrder,changePassword,refund,review,newTicket,replyTicket};
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.header}><View><Text style={s.logo}>جَنى</Text><Text style={s.muted}>خضار وفواكه وسلال</Text></View><Pressable onPress={()=>setScreen('cart')} style={s.cartBadge}><Text>🛍 {cart.reduce((n,x)=>n+x.quantity,0)}</Text></Pressable></View>
 {cartState.error&&<View style={{paddingHorizontal:16}}><Card><Text accessibilityRole="alert">{cartState.error.message}</Text><Btn title="إعادة قراءة السلة" disabled={cartState.busy} kind="outline" onPress={retryCart}/><Btn title="مسح سلة هذا الجهاز" disabled={cartState.busy} kind="outline" onPress={resetCart}/></Card></View>}
 {accountError!==''&&<View style={{paddingHorizontal:16}}><Card><Text accessibilityRole="alert">{accountError}</Text><Btn title="إعادة تحميل الحساب" disabled={accountBusy} onPress={loadAccount}/></Card></View>}
 {checkoutView.pending&&<View style={{paddingHorizontal:16}}><Btn title="لديك مراجعة طلب معلّقة — متابعة" kind="outline" disabled={checkoutView.busy} onPress={()=>resumeCheckout().catch(()=>{})}/></View>}
 <View style={s.body}>{['shop','favorites'].includes(screen)&&<Shop storefront={storefront} onStore={()=>setModal({type:'store'})} onCustom={()=>setScreen('builder')} refreshing={catalogRefreshing} onRefresh={reloadCatalog} error={catalogError} catalog={screen==='favorites'?catalog.filter(p=>favorites.has(p.family_id)):catalog} cart={cart} add={add} favorites={favorites} toggleFavorite={toggleFavorite} onProduct={product=>setModal({type:'product',product})}/>} {screen==='saved'&&<CustomerSaved key={savedTab} initialTab={savedTab} call={(path,options)=>request(path,{...options,token})} cart={cart} onCart={async(items,catalog)=>{if(sessionToken.current!==token)return;await cartStore.update(current=>mergeSavedCart(current,items,catalog));if(sessionToken.current===token){setCatalog(catalog);setScreen('cart')}}} onProfile={p=>setUser(old=>({...old,...p}))} ui={{Card,Btn,Input,s,money,when}}/>} {screen==='builder'&&<BasketBuilder catalog={catalog} cart={cart} call={request} onAdd={async(items,fresh)=>{await cartStore.update(current=>mergeSavedCart(current,items,fresh));setCatalog(fresh);setScreen('cart')}} ui={{Card,Btn,Input,s,money}}/>} {screen==='cloud-cart'&&<CloudCart key={user?.id} call={(path,options)=>request(path,{...options,token})} cart={cart} catalog={catalog} onRestore={async(next,fresh)=>{if(sessionToken.current!==token)return;await saveCart(next);if(sessionToken.current===token){setCatalog(fresh);setScreen('cart')}}} ui={{Card,Btn,s,money,when}}/>} {screen==='cart'&&<Cart cart={cart} total={total} add={add} catalog={catalog} checkout={checkout} cloud={()=>authed(async()=>setScreen('cloud-cart'))}/>} {screen==='orders'&&<Orders orders={orders} openOrder={openOrder} more={ordersNext!=null} busy={ordersBusy} loadOrders={loadOrders}/>} {screen==='notifications'&&<Notifications items={notifications} markRead={markRead}/>} {screen==='support'&&<Support items={tickets} setModal={setModal} replyTicket={replyTicket}/>} {screen==='account'&&<Account user={user} addresses={addresses} onAuth={()=>accountError?loadAccount():setModal({type:'auth'})} logout={logout} setModal={setModal} loadNotifications={loadNotifications} loadSupport={loadSupport} openSaved={openSaved} openFavorites={()=>authed(async()=>setScreen('favorites'))}/>}</View>
 <View style={s.nav}>{[['shop','المتجر'],['cart','السلة'],['orders','طلباتي'],['account','حسابي']].map(([k,t])=><Pressable key={k} onPress={()=>k==='orders'?loadOrders().catch(e=>Alert.alert('تعذر تحميل الطلبات',e.message)):setScreen(k)} style={s.navItem}><Text style={[s.navText,screen===k&&s.navActive]}>{t}</Text></Pressable>)}</View>
 <AppModal {...props}/></SafeAreaView>
}
function Shop({catalog,cart,add,favorites,toggleFavorite,onProduct,refreshing,onRefresh,error,onCustom,storefront,onStore}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all');const products=catalog.filter(p=>(category==='all'||p.category===category)&&String(p.name+' '+(p.description||'')).includes(query.trim()));
 return <FlatList refreshing={refreshing} onRefresh={onRefresh} contentContainerStyle={s.list} data={products} keyExtractor={x=>x.id} numColumns={2} columnWrapperStyle={{gap:10}} ListEmptyComponent={<Card><Text>لا توجد أصناف تطابق اختيارك.</Text></Card>} ListHeaderComponent={<View style={s.hero}>{error!==''&&<Card><Text accessibilityRole="alert">{error}</Text><Btn title="إعادة تحميل المنتجات" disabled={refreshing} onPress={onRefresh}/></Card>}<Text style={s.eyebrow}>خير اليوم على بابك</Text><Text style={s.heroTitle}>اختيارات طازجة من جازان</Text><Text style={s.muted}>الدفع عند الاستلام، والبدائل بموافقتك.</Text><Text>{storefront?.message||'جارٍ تجهيز المتجر لاستقبال الطلبات'}</Text><Btn title="المنشأة والتواصل والسياسات" kind="outline" onPress={onStore}/><Btn title="كوّن سلتك" kind="outline" onPress={onCustom}/><Input label="البحث عن منتج" value={query} onChangeText={setQuery}/><View style={s.row}>{[['all','الكل'],['fruit','فواكه'],['vegetables','خضار'],['baskets','سلال']].map(([k,label])=><Btn key={k} title={label} kind={category===k?'primary':'outline'} onPress={()=>setCategory(k)}/>)}</View></View>} renderItem={({item:p})=>{const line=cart.find(x=>x.offering_id===p.id),fav=favorites.has(p.family_id);return <View style={s.product}><Pressable accessibilityLabel={fav?'إزالة من المفضلة':'إضافة للمفضلة'} onPress={()=>toggleFavorite(p).catch(e=>Alert.alert('تعذر التنفيذ',e.message))}><Text style={s.favorite}>{fav?'♥':'♡'}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={'تفاصيل '+p.name} onPress={()=>onProduct(p)}><ProductImage product={p}/><Text style={s.productTitle}>{p.name}</Text><Text style={s.muted}>{p.size_label||p.sale_unit||''}</Text></Pressable><Text style={s.price}>{money(p.price_halalas)}</Text><View style={s.row}>{line&&<Btn title="−" kind="outline" onPress={()=>add(p,-1)}/>}<Btn title={line?String(line.quantity):'+'} onPress={()=>add(p,1)} disabled={p.available_units<1}/></View></View>}}/>
}

function Cart({cart,total,add,catalog,checkout,cloud}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>سلتك</Text><Btn title="حفظ السلة لحسابي أو استعادتها" kind="outline" onPress={cloud}/>{cart.map(x=>{const p=catalog.find(p=>p.id===x.offering_id)||{...x,id:x.offering_id,available_units:0};return <Card key={x.offering_id}><View style={s.between}><View><Text style={s.productTitle}>{x.emoji} {x.name}</Text><Text style={s.price}>{money(x.price_halalas*x.quantity)}</Text></View><View style={s.row}><Btn title="−" kind="outline" onPress={()=>add(p,-1)}/><Text>{x.quantity}</Text><Btn title="+" onPress={()=>add(p,1)}/></View></View></Card>})}{!cart.length?<Card><Text>السلة فارغة.</Text></Card>:<><Card><View style={s.between}><Text>الإجمالي المبدئي</Text><Text style={s.price}>{money(total)}</Text></View></Card><Btn title="المتابعة للعنوان والموعد" onPress={()=>checkout().catch(e=>Alert.alert('تعذر المتابعة',e.message))}/></>}</ScrollView>}
function Orders({orders,openOrder,more,busy,loadOrders}){return <FlatList data={orders} keyExtractor={o=>o.id} refreshing={busy} onRefresh={()=>loadOrders().catch(e=>Alert.alert('تعذر التحديث',e.message))} contentContainerStyle={s.list} ListHeaderComponent={<Text style={s.pageTitle}>طلباتك · {orders.length}</Text>} ListEmptyComponent={<Card><Text>{busy?'جارٍ تحميل الطلبات…':'لا توجد طلبات.'}</Text></Card>} renderItem={({item:o})=><Pressable accessibilityRole="button" onPress={()=>openOrder(o.id).catch(e=>Alert.alert('خطأ',e.message))}><Card><View style={s.between}><Text style={s.productTitle}>{o.number}</Text><Text>{statusLabel(o.status)}</Text></View><Text>{statusLabel(o.fulfillment_state)} · {statusLabel(o.delivery_state)}</Text><Text>{when(o.created_at)}</Text><Text style={s.price}>{money(o.total_halalas)}</Text></Card></Pressable>} ListFooterComponent={more?<Btn title="عرض طلبات أقدم" disabled={busy} kind="outline" onPress={()=>loadOrders(true).catch(e=>Alert.alert('تعذر تحميل المزيد',e.message))}/>:null}/>}

function Notifications({items,markRead}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>الإشعارات</Text>{items.map(n=><Pressable key={n.id} onPress={()=>markRead(n.id).catch(e=>Alert.alert('تعذر تحديث الإشعار',e.message))}><Card><Text style={s.productTitle}>{n.title||'إشعار'}</Text><Text>{n.message||n.body||''}</Text><Text style={s.muted}>{n.is_read?'مقروء':'جديد'}</Text></Card></Pressable>)}</ScrollView>}
function Support({items,setModal,replyTicket}){return <ScrollView contentContainerStyle={s.list}><View style={s.between}><Text style={s.pageTitle}>الدعم</Text><Btn title="+ تذكرة" onPress={()=>setModal({type:'ticket'})}/></View>{items.map(t=><Card key={t.id}><Text style={s.productTitle}>{t.subject}</Text><Text>{({open:'مفتوحة',pending_customer:'بانتظار ردك',closed:'مغلقة'})[t.state]||t.state}</Text><Text style={s.muted}>{t.messages?.at?.(-1)?.text||''}</Text><Btn title="المحادثة والرد" kind="outline" onPress={()=>setModal({type:'reply',ticket:t})}/></Card>)}</ScrollView>}
function Account({user,addresses,onAuth,logout,setModal,loadNotifications,loadSupport,openSaved,openFavorites}){return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>حسابي</Text>{user?<><Card><Text style={s.productTitle}>{user.name}</Text><Text>{user.email||user.phone}</Text><Btn title="العناوين" kind="outline" onPress={()=>setModal({type:'addresses'})}/><Btn title="بياناتي وتفضيلاتي" kind="outline" onPress={()=>openSaved('profile').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="قوائم التسوق" kind="outline" onPress={()=>openSaved('lists').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="تذكيرات التسوق" kind="outline" onPress={()=>openSaved('plans').catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="المفضلة" kind="outline" onPress={()=>openFavorites().catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="الإشعارات" kind="outline" onPress={()=>loadNotifications().catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="الدعم" kind="outline" onPress={()=>loadSupport().catch(e=>Alert.alert('تعذر التحميل',e.message))}/><Btn title="تغيير كلمة المرور" kind="outline" onPress={()=>setModal({type:'password'})}/><Btn title="تسجيل الخروج" kind="outline" onPress={()=>logout().catch(e=>Alert.alert('تعذر الخروج',e.message))}/></Card><Text style={s.muted}>العناوين المحفوظة: {addresses.length}</Text></>:<Card><Text>سجّل الدخول للمتابعة.</Text><Btn title="تسجيل الدخول / حساب جديد" onPress={onAuth}/></Card>}</ScrollView>}
function AppModal(p){const {modal,setModal,add,login,register,addresses,chooseAddress,createQuote,checkoutSession,checkoutView,finishCheckout,saveAddress,deleteAddress,makeDefault,decide,openOrder,changePassword,refund,review,newTicket,replyTicket}=p;const [mode,setMode]=useState('login'),[f,setF]=useState({}),[busy,setBusy]=useState(false),[readyPolicy,setReadyPolicy]=useState(null);useEffect(()=>{setF({});if(modal?.type==='auth')setMode('login')},[modal?.type]);const runLock=useRef(false);if(!modal)return null;const run=async fn=>{if(runLock.current)return;runLock.current=true;try{setBusy(true);await fn()}catch(e){Alert.alert('تعذر التنفيذ',e.message)}finally{runLock.current=false;setBusy(false)}};const order=modal.order;return <Modal visible transparent animationType="slide" onRequestClose={()=>setModal(null)}><KeyboardAvoidingView style={s.overlay} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.sheet}><View style={s.between}><Text style={s.pageTitle}>{titles[modal.type]||'جَنى'}</Text><Pressable onPress={()=>setModal(null)}><Text style={s.close}>×</Text></Pressable></View><ScrollView keyboardShouldPersistTaps="handled">
 {modal.type==='store'&&<StorePolicies call={request} ui={{Card,Btn,s,when}}/>}
 {modal.type==='product'&&<><ProductImage product={modal.product} height={220}/><Text style={s.productTitle}>{modal.product.name}</Text><Text>{modal.product.description}</Text><Text>{modal.product.size_label}</Text><Text style={s.price}>{money(modal.product.price_halalas)}</Text>{(modal.product.components||[]).map((c,i)=><Text key={c.stock_id||String(i)}>{c.name} — {c.base_qty} {c.base_unit==='piece'?'قطعة':'جرام'}</Text>)}<Btn title="إضافة للسلة" disabled={modal.product.available_units<1} onPress={async()=>{if(await add(modal.product,1))setModal(null)}}/></>}
 {modal.type==='auth'&&<><Text style={s.muted}>{mode==='login'?'أدخل بياناتك.':'أنشئ حساب عميل.'}</Text>{mode==='register'&&<Input label="الاسم" value={f.name||''} onChangeText={v=>setF({...f,name:v})}/>}{mode==='register'&&<Input label="رقم الجوال" keyboardType="phone-pad" value={f.phone||''} onChangeText={v=>setF({...f,phone:v})}/>}<Input label={mode==='register'?'البريد (اختياري عند إدخال الجوال)':'البريد أو رقم الجوال'} autoCapitalize="none" value={f.email||''} onChangeText={v=>setF({...f,email:v})}/><Input label="كلمة المرور" secureTextEntry value={f.password||''} onChangeText={v=>setF({...f,password:v})}/><Btn disabled={busy} title={mode==='login'?'تسجيل الدخول':'إنشاء الحساب'} onPress={()=>run(()=>mode==='login'?login(f.email,f.password):register(f.name,f.email,f.password,f.phone))}/><Pressable onPress={()=>setMode(mode==='login'?'register':'login')}><Text style={s.link}>{mode==='login'?'إنشاء حساب جديد':'لدي حساب'}</Text></Pressable></>}
 {modal.type==='addresses'&&<><Btn title="+ عنوان جديد" disabled={busy} onPress={()=>setModal({type:'addressEdit',checkout:modal.checkout})}/>{addresses.map(a=><Card key={a.id}><Text style={s.productTitle}>{a.label}{a.is_default?' · افتراضي':''}</Text><Text>{[a.city,a.district,a.street,a.details].filter(Boolean).join('، ')}</Text><Text>{a.recipient_name} · {a.recipient_phone}</Text><View style={s.row}>
 <Btn title={modal.checkout?'اختيار للتوصيل':'تحقق من التغطية'} disabled={busy} onPress={()=>run(async()=>{if(modal.checkout)return chooseAddress(a.id);const c=await request('/api/coverage/'+a.id,{token:p.token});Alert.alert('تغطية العنوان',c.covered?'عنوانك ضمن نطاق التوصيل'+((c.slots||[]).length?'':'، ولا توجد مواعيد متاحة الآن'):c.reason||'العنوان خارج نطاق التوصيل الحالي');})}/>
 <Btn title="Google Maps" kind="outline" disabled={busy} onPress={()=>run(()=>Linking.openURL(googleMapsLink(a.latitude,a.longitude)))}/><Btn title="تعديل" kind="outline" disabled={busy} onPress={()=>setModal({type:'addressEdit',address:a,checkout:modal.checkout})}/>{!a.is_default&&<Btn title="افتراضي" kind="outline" disabled={busy} onPress={()=>run(()=>makeDefault(a.id,modal.checkout))}/>}<Btn title="حذف" kind="outline" disabled={busy} onPress={()=>Alert.alert('حذف العنوان','حذف هذا العنوان المحفوظ؟',[{text:'إلغاء',style:'cancel'},{text:'حذف',style:'destructive',onPress:()=>run(()=>deleteAddress(a.id,modal.checkout))}])}/></View></Card>)}</>}
 {modal.type==='addressEdit'&&<AddressEditor key={modal.address?.id||'new'} address={modal.address||{is_default:addresses.length===0}} user={p.user} onSave={v=>saveAddress(v,modal.address?.id,modal.checkout)} call={(path,options)=>request(path,{...options,token:p.token})} ui={{Input,Btn,Card,s}}/>}
 {modal.type==='slots'&&modal.coupons&&<Input label="رمز القسيمة (اختياري)" autoCapitalize="characters" value={f.coupon_code||''} onChangeText={v=>setF({...f,coupon_code:v})}/>}
 {modal.type==='slots'&&modal.slots.map(sl=><Pressable key={sl.id} onPress={()=>run(()=>createQuote(modal.addressId,sl.id,f.coupon_code||''))}><Card><Text style={s.productTitle}>{when(sl.starts_at)}</Text><Text>التوصيل {money(sl.fee_halalas)} · المتاح {sl.available}</Text></Card></Pressable>)}
 {modal.type==='quote'&&<CheckoutReview checkout={checkoutSession} state={checkoutView} call={request} onConfirmed={finishCheckout} onSignIn={()=>setModal({type:'auth'})} onReleased={()=>setModal(null)} ui={{Card,Btn,s,money,when}}/>}
 {modal.type==='done'&&<Card>{modal.cartKept&&<Text>تغيرت سلتك بعد عرض السعر، فاحتفظنا بها. راجعها قبل شراء جديد.</Text>}<Text style={s.productTitle}>تم تأكيد {modal.order.number}</Text><Text>{modal.order.delivery_code?`رمز التسليم: ${modal.order.delivery_code}`:'تابع الطلب من صفحة طلباتي.'}</Text></Card>}
 {modal.type==='password'&&<PasswordEditor onSave={changePassword} ui={{Input,Btn,s}}/>}
 {modal.type==='order'&&order&&<OrderDetails key={order.id} order={order} call={(path,options)=>request(path,{...options,token:p.token})} onRefresh={()=>openOrder(order.id)} onSupport={()=>setModal({type:'ticket',order_id:order.id})} ui={{Card,Btn,s,money,when,statusLabel}}>
  {(order.original_snapshot?.store_profile||order.snapshot?.store_profile)?.id&&<StorePolicies call={request} version={(order.original_snapshot?.store_profile||order.snapshot?.store_profile).id} ui={{Card,Btn,s,when}}/>}
  {(order.substitutions||[]).map(x=><Substitution key={x.id} sub={x} onDecision={accept=>run(()=>decide(x.id,accept,order.id))}/>)}
  <Text style={s.productTitle}>الاستردادات</Text>{(order.refunds||[]).map(r=><Card key={r.id}><Text style={s.productTitle}>{money(r.amount_halalas)} · {({requested:'قيد المراجعة',processing:'قيد المعالجة',completed:'سُجّل إرجاع المبلغ',rejected:'مرفوض',failed:'تعذر الإكمال'})[r.state]||r.state}</Text><Text>{r.reason}</Text>{!!r.decision_note&&<Text>{r.decision_note}</Text>}</Card>)}{!order.refunds?.length&&<Text>لا توجد طلبات استرداد.</Text>}
  {orderFacts(order).canRefund&&<Btn title="طلب استرداد" kind="outline" onPress={()=>setModal({type:'refund',order})}/>}
  {order.delivery_state==='delivered'&&(order.review?<Card><Text>تقييمك: {order.review.rating} / 5</Text><Text>{order.review.comment}</Text></Card>:<Btn title="تقييم الطلب" kind="outline" onPress={()=>setModal({type:'review',order})}/>)}
 </OrderDetails>}
 {modal.type==='refund'&&<><Text>هذا طلب مراجعة. لا يُعد المبلغ مستردًا حتى يؤكد فريق المالية إرجاعه.</Text><Input label="المبلغ بالريال" keyboardType="decimal-pad" value={f.amount||''} onChangeText={v=>setF({...f,amount:v})}/><Input label="السبب" value={f.reason||''} onChangeText={v=>setF({...f,reason:v})}/><Btn title="إرسال طلب الاسترداد" onPress={()=>run(()=>refund(modal.order.id,f))}/></>}
 {modal.type==='review'&&<><Input label="التقييم من 1 إلى 5" keyboardType="number-pad" value={f.rating||''} onChangeText={v=>setF({...f,rating:v})}/><Input label="التعليق" value={f.comment||''} onChangeText={v=>setF({...f,comment:v})}/><Btn title="إرسال التقييم" onPress={()=>run(()=>review(modal.order.id,f))}/></>}
 {modal.type==='ticket'&&<><Text style={s.productTitle}>نوع المساعدة</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{[['order','طلب'],['product','منتج'],['delivery','توصيل'],['refund','استرداد'],['account','حساب'],['other','أخرى']].map(([key,label])=><Btn key={key} title={label} kind={(f.category||'other')===key?'primary':'outline'} onPress={()=>setF({...f,category:key})}/>)}</View><Input label="الموضوع" value={f.subject||''} onChangeText={v=>setF({...f,subject:v})}/><Input label="الرسالة" multiline value={f.message||''} onChangeText={v=>setF({...f,message:v})}/><Btn title="فتح التذكرة" onPress={()=>run(()=>newTicket({...f,order_id:modal.order_id}))}/></>}
 {modal.type==='reply'&&<>{(modal.ticket.messages||[]).map((m,i)=><Card key={m.id||String(i)}><Text style={s.productTitle}>{m.actor==='customer'?'أنت':'خدمة العملاء'}</Text><Text>{m.text||m.message||''}</Text></Card>)}{modal.ticket.state==='closed'&&<Text>إرسال رد جديد يعيد فتح التذكرة.</Text>}<Input label="الرد" multiline value={f.message||''} onChangeText={v=>setF({...f,message:v})}/><Btn title="إرسال الرد" onPress={()=>run(()=>replyTicket(modal.ticket.id,f.message))}/></>}
 </ScrollView></View></KeyboardAvoidingView></Modal>}

const titles={password:'تغيير كلمة المرور',store:'المنشأة والسياسات',product:'تفاصيل المنتج',auth:'الدخول',addresses:'العناوين',addressEdit:'تعديل العنوان',slots:'موعد التوصيل',quote:'مراجعة الطلب',done:'تم الطلب',order:'تفاصيل الطلب',refund:'استرداد',review:'التقييم',ticket:'الدعم',reply:'رد الدعم'};
const s=StyleSheet.create({safe:{flex:1,direction:'rtl',backgroundColor:'#f7f7ef'},body:{flex:1},header:{padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderColor:'#e4e7df'},logo:{fontSize:28,fontWeight:'800',color:'#1b563d'},muted:{color:'#6f7973'},cartBadge:{padding:10,backgroundColor:'#fff',borderRadius:14},list:{padding:16,gap:10},hero:{paddingVertical:12,gap:6},eyebrow:{color:'#1b563d',fontWeight:'700'},heroTitle:{fontSize:28,fontWeight:'800'},product:{flex:1,backgroundColor:'#fff',padding:12,borderRadius:18,marginBottom:10,minHeight:210},favorite:{fontSize:24,color:'#a53737',textAlign:'left'},emoji:{fontSize:42,textAlign:'center'},productTitle:{fontSize:17,fontWeight:'700'},price:{fontWeight:'800',color:'#1b563d',fontSize:17},row:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},card:{backgroundColor:'#fff',padding:14,borderRadius:16,gap:8,marginBottom:8},btn:{backgroundColor:'#1b563d',minHeight:44,minWidth:44,paddingVertical:10,paddingHorizontal:14,borderRadius:12,alignItems:'center'},outline:{backgroundColor:'#fff',borderWidth:1,borderColor:'#1b563d'},btnText:{color:'#fff',fontWeight:'700'},outlineText:{color:'#1b563d'},nav:{flexDirection:'row',borderTopWidth:1,borderColor:'#e4e7df',backgroundColor:'#fff'},navItem:{flex:1,padding:14,alignItems:'center'},navText:{color:'#6f7973'},navActive:{color:'#1b563d',fontWeight:'800'},pageTitle:{fontSize:24,fontWeight:'800'},center:{flex:1,alignItems:'center',justifyContent:'center'},overlay:{flex:1,backgroundColor:'#0005',justifyContent:'flex-end'},sheet:{backgroundColor:'#f7f7ef',padding:18,borderTopLeftRadius:24,borderTopRightRadius:24,maxHeight:'90%'},close:{fontSize:32},field:{gap:6,marginBottom:10},label:{fontWeight:'700'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d9ddd6',borderRadius:12,padding:12},link:{textAlign:'center',padding:14,color:'#1b563d',fontWeight:'700'}});

function Substitution({sub,onDecision}){
 const t=sub.proposed||{},original=t.original_line||{},replacement=t.replacement_line||{},pending=sub.state==='pending'&&Number(sub.expires_at)>Date.now();
 const removal=t.action==='remove_line',componentSwap=t.action==='replace_component',from=t.original_component||{},to=t.replacement_component||{};
 const safeTotals=Number.isSafeInteger(t.total_halalas)&&Number.isSafeInteger(t.price_difference_halalas)&&Number.isSafeInteger(t.original_total_halalas);
 const safeComponent=componentSwap&&!!original.name&&!!replacement.name&&!!from.name&&!!to.name&&from.stock_id!==to.stock_id&&from.base_unit===to.base_unit&&Number.isSafeInteger(from.planned_base)&&Number.isSafeInteger(from.actual_base)&&from.planned_base>0&&from.actual_base>=0&&from.actual_base<from.planned_base&&from.planned_base===to.planned_base&&t.total_halalas===t.original_total_halalas&&t.price_difference_halalas===0;
 const complete=!!original.name&&safeTotals&&(componentSwap?safeComponent:removal?Number.isSafeInteger(t.subtotal_halalas)&&t.total_halalas<=t.original_total_halalas:!!replacement.name);
 const amount=v=>Number.isSafeInteger(v)?money(v):'غير مسجل';
 const components=line=>(line.components||[]).map(c=>`${c.name}: ${c.base_qty*line.qty} ${c.base_unit==='piece'?'قطعة':'جرام'}`).join('، ');
 const componentQty=c=>`${c.planned_base} ${c.base_unit==='piece'?'قطعة':'جرام'}`;
 const approveTitle=componentSwap?'أوافق على مكوّن السلة بالسعر نفسه':removal?'أوافق على حذف الصنف والإجمالي':'أوافق على البديل والإجمالي';
 const rejectTitle=componentSwap?'أرفض مكوّن السلة البديل':removal?'أرفض حذف الصنف':'أرفض البديل';
 return <Card><Text style={s.productTitle}>{componentSwap?'استبدال مكوّن في السلة':removal?'طلب حذف صنف':'اقتراح استبدال'} · {({pending:'بانتظار قرارك',accepted:'وافقت عليه',rejected:'مرفوض',expired:'انتهت المهلة'})[sub.state]||sub.state}</Text><Text>{removal?'الصنف غير المتوفر':componentSwap?'السلة':'الأصلي'}: {original.name||'تفاصيل غير متاحة'} × {original.qty}</Text><Text>{components(original)}</Text>{componentSwap?<><Text>المكوّن الناقص: {from.name||'تفاصيل غير متاحة'} — المطلوب {componentQty(from)}، والمسجل {from.actual_base} {from.base_unit==='piece'?'قطعة':'جرام'}</Text><Text>المكوّن البديل: {to.name||'تفاصيل غير متاحة'} — {componentQty(to)} من الوحدة نفسها</Text><Text>سعر السلة والإجمالي لن يتغيرا. لا يُحجز البديل إلا بعد موافقتك، ثم يعيد المجهز قياس المكونات.</Text></>:!removal&&<><Text>البديل: {replacement.name||'تفاصيل غير متاحة'} × {replacement.qty}</Text><Text>{components(replacement)}</Text>{replacement.weight_policy&&<Text>الوزن المسموح {replacement.weight_policy.min_base}–{replacement.weight_policy.max_base} جرام. النقص يخفض السعر والزيادة المسموحة مجانًا.</Text>}</>}<Text>الإجمالي السابق: {amount(t.original_total_halalas)}</Text><Text>فرق الإجمالي: {amount(t.price_difference_halalas)}</Text><Text style={s.price}>الإجمالي عند الموافقة: {amount(t.total_halalas)}</Text>{sub.state==='pending'&&<Text>المهلة: {when(sub.expires_at)}. {componentSwap?'عدم الرد لا يعني الموافقة، ويبقى النقص بحاجة إلى معالجة.':removal?'عدم الرد يبقي الصنف معلقًا ولا يعني الحذف.':'يُفحص توفر المخزون عند الموافقة. عدم الرد لا يعني الموافقة.'}</Text>}{pending&&<><Btn title={approveTitle} disabled={!complete} onPress={()=>Alert.alert(componentSwap?'تأكيد مكوّن السلة':removal?'تأكيد حذف الصنف':'تأكيد البديل',componentSwap?`هل توافق على استبدال المكوّن مع بقاء الإجمالي ${amount(t.total_halalas)}؟`:removal?`هل توافق على حذف الصنف وإجمالي ${amount(t.total_halalas)}؟`:`هل توافق على البديل بإجمالي ${amount(t.total_halalas)}؟`,[{text:'رجوع',style:'cancel'},{text:'أوافق',onPress:()=>onDecision(true)}])}/><Btn title={rejectTitle} kind="outline" onPress={()=>onDecision(false)}/></>}</Card>
}
