import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,Text,View,Switch} from 'react-native';
import {loadCatalog} from './catalog.mjs';
import {mergeSavedCart,saudiReminderDate} from './saved-cart.mjs';

export default function CustomerSaved({call,initialTab='lists',cart,onCart,onProfile,ui}){
 const {Card,Btn,Input,s,money,when}=ui;
 const [tab,setTab]=useState(initialTab),[data,setData]=useState(null),[editor,setEditor]=useState(null),[form,setForm]=useState({}),[pending,setPending]=useState(false),[error,setError]=useState('');
 async function load(){const [lists,plans,profile,addresses,catalog]=await Promise.all([call('/api/shopping-lists'),call('/api/recurring'),call('/api/profile'),call('/api/addresses'),loadCatalog(call)]);setData({lists:lists.items||[],plans:plans.items||[],profile,addresses:addresses.items||[],catalog})}
 async function run(fn){if(pending)return;setPending(true);setError('');try{await fn()}catch(e){setError(e.message||'تعذر إكمال العملية')}finally{setPending(false)}}
 useEffect(()=>{run(load)},[]);
 function begin(kind,item={}){setEditor({kind,item});setForm({name:item.name||'',items:Object.fromEntries((item.items||[]).map(x=>[x.offering_family_id,String(x.quantity)])),cadence:item.cadence||'weekly',address_id:item.address_id||data?.addresses[0]?.id||'',next_at:item.next_at?new Date(item.next_at+10800000).toISOString().slice(0,16).replace('T',' '):'',consent:false,...(kind==='profile'?{name:data.profile.name,phone:data.profile.phone||'',marketing_opt_in:data.profile.preferences?.marketing_opt_in===true}:{})})}
 const set=(k,v)=>setForm(old=>({...old,[k]:v}));
 const items=()=>Object.entries(form.items||{}).map(([offering_family_id,q])=>({offering_family_id,quantity:Number(q)})).filter(x=>x.quantity>0);
 async function save(){
  const {kind,item}=editor;
  if(kind==='profile'){const p=await call('/api/profile',{method:'PATCH',body:{name:form.name,phone:form.phone,preferences:{language:'ar',marketing_opt_in:!!form.marketing_opt_in}}});onProfile(p)}
  else if(kind==='list'){if(Object.values(form.items||{}).some(x=>!/^\d{1,2}$/.test(String(x))||Number(x)>20))throw Error('أدخل كميات صحيحة من 0 إلى 20');await call('/api/shopping-lists'+(item.id?'/'+item.id:''),{method:item.id?'PATCH':'POST',body:{name:form.name,items:items(),...(item.id?{revision:item.revision}:{})}})}
  else{if(!form.consent)throw Error('أكد رغبتك في التذكير فقط');if(!form.address_id)throw Error('أضف عنوانًا محفوظًا من صفحة الحساب أولًا');await call('/api/recurring'+(item.id?'/'+item.id:''),{method:item.id?'PATCH':'POST',body:{name:form.name,address_id:form.address_id,cadence:form.cadence,next_at:saudiReminderDate(form.next_at),state:'active',items:(item.items||[]).map(x=>({offering_family_id:x.offering_family_id,quantity:x.quantity})),...(item.id?{revision:item.revision}:{})}});setTab('plans')}
  await load();setEditor(null);
 }
 async function use(items){const r=await loadCatalog(call);onCart(mergeSavedCart(cart,items,r),r)}
 async function planState(item,state){await call('/api/recurring/'+item.id,{method:'PATCH',body:{revision:item.revision,state}});await load()}
 const summary=items=>(items||[]).map((x,i)=><Text key={x.offering_family_id||String(i)}>{x.name||'صنف محفوظ'} · {x.size_label||''} × {x.quantity} — {x.available?money(x.price_halalas):'الكمية غير متاحة الآن'}</Text>);
 const tabName={lists:'قوائم التسوق',plans:'تذكيرات التسوق',profile:'بياناتي'};
 const choices=new Map((data?.catalog||[]).map(p=>[p.family_id,{name:p.name,size_label:p.size_label}]));for(const x of editor?.item.items||[])if(!choices.has(x.offering_family_id))choices.set(x.offering_family_id,x);
 return <ScrollView contentContainerStyle={s.list}><Text style={s.pageTitle}>{editor?editor.kind==='list'?'حفظ قائمة':editor.kind==='plan'?'إعداد تذكير':'تعديل بياناتي':tabName[tab]}</Text>{error!==''&&<Card><Text accessibilityRole="alert">{error}</Text><Btn kind="outline" title="تحديث البيانات" disabled={pending} onPress={()=>run(load)}/></Card>}{pending&&<Text accessibilityLiveRegion="polite">جارٍ التنفيذ…</Text>}
 {!data&&!pending&&<Btn title="إعادة التحميل" onPress={()=>run(load)}/>}
 {data&&!editor&&<><View style={s.row}>{Object.entries(tabName).map(([k,name])=><Btn key={k} title={name} kind={tab===k?'primary':'outline'} onPress={()=>setTab(k)}/>)}</View>
 {tab==='lists'&&<><Btn title="+ قائمة جديدة" onPress={()=>begin('list')}/><Btn title="حفظ السلة في قائمة" disabled={!cart.length} kind="outline" onPress={()=>begin('list',{items:cart.map(x=>({offering_family_id:x.family_id||data.catalog.find(p=>p.id===x.offering_id)?.family_id,name:x.name,quantity:x.quantity}))})}/>{data.lists.length===0&&<Card><Text>لا توجد قوائم محفوظة.</Text></Card>}{data.lists.map(l=><Card key={l.id}><Text style={s.productTitle}>{l.name}</Text>{summary(l.items)}<Btn title="إضافة القائمة إلى السلة" disabled={pending||!l.items.length} onPress={()=>run(()=>use(l.items))}/><Btn title="تعديل الاسم والأصناف" kind="outline" onPress={()=>begin('list',l)}/><Btn title="تذكير دوري بهذه القائمة" disabled={!l.items.length} kind="outline" onPress={()=>begin('plan',{name:l.name,items:l.items})}/><Btn title="حذف القائمة" kind="outline" disabled={pending} onPress={()=>Alert.alert('حذف القائمة',l.name,[{text:'رجوع',style:'cancel'},{text:'حذف',style:'destructive',onPress:()=>run(async()=>{await call('/api/shopping-lists/'+l.id,{method:'DELETE',body:{revision:l.revision}});await load()})}])}/></Card>)}</>}
 {tab==='plans'&&<><Card><Text>التذكير داخل التطبيق فقط. لن يُنشأ طلب أو حجز أو تحصيل حتى تراجع الأسعار وموعد التوصيل وتؤكد بنفسك.</Text><Btn title="إنشاء تذكير من قائمة" onPress={()=>setTab('lists')}/></Card>{data.plans.map(p=><Card key={p.id}><Text style={s.productTitle}>{p.name}</Text><Text>{({weekly:'أسبوعيًا',fortnightly:'كل أسبوعين',monthly:'شهريًا',custom_days:'كل '+p.interval_days+' يومًا'})[p.cadence]} · {({active:'نشط',paused:'متوقف',cancelled:'ملغى'})[p.state]}</Text><Text>{when(p.next_at)} · {p.address_label}</Text>{summary(p.items)}<Btn title="مراجعة السلة الآن" disabled={pending} onPress={()=>run(()=>use(p.items))}/>{p.state!=='cancelled'&&<><Btn title="تعديل الموعد أو استئناف" kind="outline" onPress={()=>begin('plan',p)}/>{p.state==='active'&&<Btn title="إيقاف مؤقت" kind="outline" disabled={pending} onPress={()=>run(()=>planState(p,'paused'))}/>}<Btn title="إلغاء التذكير" kind="outline" disabled={pending} onPress={()=>Alert.alert('إلغاء التذكير',p.name,[{text:'رجوع',style:'cancel'},{text:'إلغاء التذكير',style:'destructive',onPress:()=>run(()=>planState(p,'cancelled'))}])}/></>}</Card>)}</>}
 {tab==='profile'&&<Card><Text style={s.productTitle}>{data.profile.name}</Text><Text>{data.profile.email}</Text><Text>{data.profile.phone||'لم يُضف رقم جوال'}</Text><Btn title="تعديل الاسم والجوال والتفضيلات" onPress={()=>begin('profile')}/></Card>}</>}
 {data&&editor&&<><Input label="الاسم" value={form.name} onChangeText={v=>set('name',v)} maxLength={100}/>
 {editor.kind==='list'&&<><Text>كمية من 0 إلى 20. الصفر يزيل الصنف. الحفظ لا يحجز المخزون.</Text>{[...choices.entries()].map(([id,p])=><Input key={id} label={p.name+' · '+(p.size_label||'')} keyboardType="number-pad" value={form.items[id]??'0'} onChangeText={v=>set('items',{...form.items,[id]:v})} maxLength={2}/>)}</>}
 {editor.kind==='profile'&&<><Input label="الجوال (اختياري)" keyboardType="phone-pad" value={form.phone} onChangeText={v=>set('phone',v)}/><Text>أوافق على العروض عند تفعيل الإشعارات التسويقية</Text><Switch accessibilityLabel="الموافقة على العروض" value={form.marketing_opt_in} onValueChange={v=>set('marketing_opt_in',v)}/></>}
 {editor.kind==='plan'&&<><Text>اختر العنوان</Text>{data.addresses.map(a=><Btn key={a.id} title={a.label} kind={form.address_id===a.id?'primary':'outline'} onPress={()=>set('address_id',a.id)}/>)}{!data.addresses.length&&<Text>أضف عنوانًا من صفحة الحساب أولًا.</Text>}<Text>التكرار</Text><View style={s.row}>{[['weekly','أسبوعي'],['fortnightly','كل أسبوعين'],['monthly','شهري']].map(([k,label])=><Btn key={k} title={label} kind={form.cadence===k?'primary':'outline'} onPress={()=>set('cadence',k)}/>)}</View><Input label="الموعد بتوقيت السعودية: سنة-شهر-يوم ساعة:دقيقة" placeholder="2026-10-15 09:00" value={form.next_at} onChangeText={v=>set('next_at',v)}/><Text>للشهري: يُستخدم آخر يوم متاح في الأشهر القصيرة. الموعد تذكير وليس حجز توصيل.</Text><Text>أريد تذكيرًا فقط وسأؤكد الطلب بنفسي</Text><Switch accessibilityLabel="الموافقة على تذكير التسوق" value={form.consent} onValueChange={v=>set('consent',v)}/></>}
 <Btn title="حفظ" disabled={pending||(editor.kind==='plan'&&!form.consent)} onPress={()=>run(save)}/><Btn title="رجوع" kind="outline" disabled={pending} onPress={()=>setEditor(null)}/></>}
 </ScrollView>
}
