from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
f=fixture(stock=1000);rows=race([quote(f,'last-stock-'+str(i)) for i in range(16)]);assert len(successful(rows))==1;assert all(r['ok'] or 'insufficient_stock' in r['error'] for r in rows);assert balance(f)['reserved']==1000;passed('16 buyers cannot oversell last stock')
f=fixture(stock=30000,capacity=1);rows=race([quote(f,'last-slot-'+str(i)) for i in range(16)]);assert len(successful(rows))==1;assert all(r['ok'] or 'slot_unavailable' in r['error'] for r in rows);assert balance(f)['booked']==1;passed('16 buyers cannot overbook last slot')
f=fixture();rows=race([quote(f,'same-quote-key')]*16);quotes=successful(rows);assert len(quotes)==16 and len({q['id'] for q in quotes})==1;assert balance(f)['reserved']==1000 and balance(f)['booked']==1;passed('16 identical quote retries reserve once')
rows=race([quote(f,'mixed-quote-key',1+i%2) for i in range(16)]);accepted=successful(rows);assert 0<len(accepted)<16;assert len({q['id'] for q in accepted})==1;assert all(r['ok'] or 'idempotency_conflict' in r['error'] for r in rows);passed('concurrent changed-body key reuse is rejected')
# Use a separate fixture for the complete delivery/COD retry journey.
f=fixture();q=val(quote(f,'fulfillment-quote'));confirm=rpc('jana_critical_write',f['t'],'same-confirm-key','order.confirm',{'quote_id':q['id']});orders=successful(race([confirm]*16));assert len(orders)==16 and all(o==orders[0] for o in orders);o=orders[0];oid=o['id'];assert val('SELECT count(*) FROM orders WHERE quote_id='+literal(q['id'])+';')==1;passed('16 confirmations create one order and replay delivery code')
val(rpc('jana_ops_transition',f['atok'],oid,'start',''))
val(rpc('jana_finalize_picking',f['atok'],oid))
val(rpc('jana_ops_transition',f['ct'],oid,'dispatch',''))
deliver=rpc('jana_critical_write',f['ct'],'same-delivery-key','order.deliver',{'order_id':oid,'code':o['delivery_code']});rows=successful(race([deliver]*16));assert len(rows)==16 and all(r==rows[0] for r in rows);assert val('SELECT collected_halalas FROM orders WHERE id='+literal(oid)+';')==0;passed('delivery retries prove delivery without collecting cash')
collect=rpc('jana_critical_write',f['ct'],'same-collect-key','cod.collect',{'order_id':oid,'amount_halalas':2000});rows=successful(race([collect]*16));assert len(rows)==16 and all(r==rows[0] for r in rows);assert val("SELECT count(*) FROM order_events WHERE event='collect' AND order_id="+literal(oid)+';')==1;passed('16 collection retries record one cash liability')
refund=rpc('jana_critical_write',f['atok'],'same-refund-key','refund.create',{'order_id':oid,'amount_halalas':100,'reason':'Disposable concurrency fixture refund','reference':'Fixture cash refund','payment_source':'courier'});rows=successful(race([refund]*16));assert len(rows)==16 and all(r==rows[0] for r in rows);assert val('SELECT refunded_halalas FROM orders WHERE id='+literal(oid)+';')==100;passed('16 refund retries create one refund')
settle=rpc('jana_critical_write',f['atok'],'same-settle-key','cod.settle',{'order_id':oid,'reference':'Disposable concurrency deposit'});rows=successful(race([settle]*16));assert len(rows)==16 and all(r==rows[0] for r in rows);assert rows[0]['settled_halalas']==1900;assert val("SELECT count(*) FROM audit_log WHERE action='cash_settled' AND entity_id="+literal(oid)+';')==1;passed('16 settlement retries settle liability once')
health=val('SELECT public.jana_deep_health()::text;');assert health['ok'],json.dumps(health);passed('database invariants survive concurrent journeys')
print(json.dumps({'passed':len(checks),'clients_per_race':16,'database':'disposable PostgreSQL/PostGIS','checks':checks}))
