from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r

def write(f,key,op,payload,token=None):return rpc('jana_customer_saved_write',token or f['t'],key,op,payload)
def lists(f):return val(rpc('jana_shopping_lists',f['t']))
def plans(f):return val(rpc('jana_recurring_list',f['t']))
def now():return val('SELECT (extract(epoch FROM clock_timestamp())*1000)::bigint;')
f=fixture();item={'offering_family_id':f['p']+'fam','quantity':1};payload={'name':'Weekly fixture','items':[item]};attempts=race([write(f,'list-create-once','list.save',payload)]*8);assert all(x['ok'] for x in attempts),attempts;rows=successful(attempts);assert len(rows)==8 and all(r==rows[0] for r in rows);l=rows[0];assert len(lists(f))==1;assert balance(f)['reserved']==0 and balance(f)['booked']==0;passed('eight list creation retries save once without reserving stock or capacity')
fails(write(f,'list-create-once','list.save',{'name':'Changed','items':[]}), 'idempotency_conflict')
for bad in [None,{},[{'offering_family_id':'unknown','quantity':1}],[{**item,'quantity':'1'}],[{**item,'quantity':0}],[{**item,'quantity':1.5}],[{**item,'quantity':21}]]:fails(write(f,'invalid-list-'+str(len(str(bad))),'list.save',{'name':'Invalid fixture','items':bad}),'invalid_list_items')
passed('saved item validation rejects unknown lineage fractional quantities and malformed input')
# Empty lists may be created and duplicate item additions normalize to one quantity.
e=val(write(f,'empty-list-create','list.save',{'name':'Empty fixture','items':[]}));d=val(write(f,'merge-item-create','list.save',{'name':'Combined fixture','items':[item,item]}));assert next(x for x in lists(f) if x['id']==d['id'])['items'][0]['quantity']==2;passed('empty lists and duplicate item quantities have explicit canonical behavior')
rows=race([write(f,'rename-a','list.save',{'list_id':l['id'],'name':'First rename','revision':1}),write(f,'rename-b','list.save',{'list_id':l['id'],'name':'Second rename','revision':1})]);assert len(successful(rows))==1 and any('saved_list_changed' in r['error'] for r in rows);l=next(x for x in lists(f) if x['id']==l['id']);assert l['revision']==2 and len(l['items'])==1;passed('concurrent renames detect stale revision rather than silently overwriting edits')
other=fixture();fails(write(other,'foreign-list-edit','list.save',{'list_id':l['id'],'name':'Unauthorized','revision':2}),'list_not_found');fails(write(other,'foreign-list-delete','list.delete',{'list_id':l['id'],'revision':2}),'list_not_found');assert lists(other)==[];fails(rpc('jana_shopping_lists',f['atok']),'forbidden');passed('customer lists are private and staff cannot use customer saved-data endpoints')
run('UPDATE offerings SET active=false WHERE id='+literal(f['p']+'off')+';');v=next(x for x in lists(f) if x['id']==l['id'])['items'][0];assert not v['available'] and v['offering_id'] is None and v['price_halalas'] is None
run("INSERT INTO offerings SELECT (jsonb_populate_record(NULL::offerings,to_jsonb(o)||jsonb_build_object('id',"+literal(f['p']+'off2')+",'version',2,'price_halalas',2500,'active',true))).* FROM offerings o WHERE id="+literal(f['p']+'off')+';');v=next(x for x in lists(f) if x['id']==l['id'])['items'][0];assert v['price_halalas']==2500 and v['offering_id']==f['p']+'off2';passed('saved lists resolve current active offering and never invent price for unavailable products')
val(write(f,'delete-list-once','list.delete',{'list_id':l['id'],'revision':2}));assert val(write(f,'delete-list-once','list.delete',{'list_id':l['id'],'revision':2}))['deleted'];assert all(x['id']!=l['id'] for x in lists(f));passed('list removal retries return the durable original result')
profile=val(write(f,'profile-save-once','profile.update',{'name':'Customer fixture','phone':'0501112233','preferences':{'language':'ar','marketing_opt_in':False},'role':'admin','verified_phone':True}));assert not profile['verified_phone'] and profile['preferences']['marketing_opt_in'] is False;assert val(rpc('jana_me',f['t']))['role']=='customer';assert 'password_hash' not in profile;fails(write(other,'duplicate-profile-phone','profile.update',{'phone':'0501112233'}),'phone_already_used');fails(write(f,'profile-invalid-pref','profile.update',{'preferences':{'language':None}}),'profile_validation');passed('customer profile preserves role and phone verification while validating unique contact and preferences')
payload={'name':'Weekly reminder fixture','address_id':f['p']+'addr','items':[item],'cadence':'weekly','next_at':now()+3600000};rows=successful(race([write(f,'reminder-create-once','recurring.save',{'changes':payload})]*8));assert len(rows)==8 and all(r==rows[0] for r in rows);plan=rows[0];assert plan['mode']=='reminder_only';assert len(plans(f))==1;assert balance(f)['reserved']==0 and val('SELECT count(*) FROM orders WHERE user_id='+literal(f['p']+'u')+';')==0;passed('recurring definition retries create one reminder plan without a quote order payment or reservation')
fails(write(other,'foreign-reminder','recurring.save',{'changes':{**payload,'address_id':f['p']+'addr','items':[{'offering_family_id':other['p']+'fam','quantity':1}]}}),'invalid_address');fails(write(f,'past-reminder','recurring.save',{'changes':{**payload,'next_at':1}}),'invalid_reminder_date');fails(write(f,'bad-cadence','recurring.save',{'changes':{**payload,'cadence':'daily-charge'}}),'invalid_recurring');passed('reminders require owned address valid future date and explicit supported cadence')
for year,day in [(2027,28),(2028,29)]:
 stamp=val("SELECT (extract(epoch FROM '"+str(year)+"-01-31 10:00:00+03'::timestamptz)*1000)::bigint;");feb=val(rpc('jana_next_reminder',stamp,'monthly',30,31));march=val(rpc('jana_next_reminder',feb,'monthly',30,31));date=val('SELECT to_jsonb(to_timestamp('+str(feb)+"/1000.0) AT TIME ZONE 'Asia/Riyadh');");assert date.startswith(str(year)+'-02-'+str(day)+'T10:00:00');date=val('SELECT to_jsonb(to_timestamp('+str(march)+"/1000.0) AT TIME ZONE 'Asia/Riyadh');");assert date.startswith(str(year)+'-03-31T10:00:00')
passed('monthly schedule preserves Saudi clock time and original month-end anchor including leap year')
run('UPDATE recurring_plans SET next_at='+str(now()-15*86400000)+' WHERE id='+literal(plan['id'])+';');results=race(['SELECT jana_recurring_reminders();']*8);assert all(r['ok'] for r in results),results
assert val("SELECT count(*) FROM notifications WHERE user_id="+literal(f['p']+'u')+" AND dedupe_key LIKE 'recurring-%';")==1;plan=plans(f)[0];assert plan['next_at']>now() and plan['last_notice_at'];assert balance(f)['reserved']==0 and balance(f)['booked']==0;assert val('SELECT count(*) FROM orders WHERE user_id='+literal(f['p']+'u')+';')==0;passed('eight reminder workers deliver one in-app reminder and skip missed cycles without reserving or ordering')
val(write(f,'pause-reminder','recurring.save',{'plan_id':plan['id'],'changes':{'state':'paused','revision':plan['revision']}}));run('UPDATE recurring_plans SET next_at=1 WHERE id='+literal(plan['id'])+';');val('SELECT jana_recurring_reminders();');assert val("SELECT count(*) FROM notifications WHERE user_id="+literal(f['p']+'u')+" AND dedupe_key LIKE 'recurring-%';")==1;plan=plans(f)[0];fails(write(f,'resume-past-reminder','recurring.save',{'plan_id':plan['id'],'changes':{'state':'active','revision':plan['revision']}}),'invalid_reminder_date');val(write(f,'cancel-reminder','recurring.save',{'plan_id':plan['id'],'changes':{'state':'cancelled','revision':plan['revision']}}));plan=plans(f)[0];fails(write(f,'revive-cancelled-reminder','recurring.save',{'plan_id':plan['id'],'changes':{'state':'active','next_at':now()+3600000,'revision':plan['revision']}}),'plan_cancelled');passed('pause and cancellation stop reminders and reactivation cannot silently use an expired schedule')
# The scheduler test changes cadence only inside the disposable localhost database.
import time
scheduled=val(write(f,'scheduled-reminder','recurring.save',{'changes':{**payload,'next_at':now()+200}}));val("SELECT cron.schedule('jana-recurring-reminders','2 seconds','SELECT public.jana_recurring_reminders();');")
deadline=time.monotonic()+12
while time.monotonic()<deadline:
 if val('SELECT count(*) FROM notifications WHERE dedupe_key LIKE '+literal('recurring-'+scheduled['id']+'-%')+';')==1:break
 time.sleep(0.5)
else:raise AssertionError('Recurring pg_cron job did not deliver the in-app reminder')
assert val("SELECT count(*) FROM cron.job_run_details d JOIN cron.job j USING(jobid) WHERE j.jobname='jana-recurring-reminders' AND d.status='succeeded';")>=1
passed('actual pg_cron execution delivers a due in-app reminder without external providers')
assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'jana_%' AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE')); ")==0;assert not val("SELECT to_jsonb(has_function_privilege('service_role','public.jana_next_reminder(bigint,text,integer,integer)','EXECUTE')); ");passed('saved-data functions and scheduler are unavailable to direct client roles')
print(json.dumps({'passed':len(checks),'checks':checks}))
