from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(query,code):
 r=run(query,False);assert not r['ok'] and code in r['error'],r

def prepared(*,stock=10000,cost=None,unknown=False,delivered=True):
 f=fixture(stock=stock);p=f['p']
 if unknown:run("UPDATE inventory_lots SET total_cost_halalas=NULL,remaining_cost_halalas=NULL,cost_basis='unknown' WHERE id="+literal(p+'l')+';')
 elif cost is not None:run('UPDATE inventory_lots SET total_cost_halalas='+str(cost)+',remaining_cost_halalas='+str(cost)+' WHERE id='+literal(p+'l')+';')
 q=val(quote(f,'return-fixture-quote'));o=val(rpc('jana_critical_write',f['t'],'return-fixture-confirm','order.confirm',{'quote_id':q['id']}));val(rpc('jana_ops_transition',f['atok'],o['id'],'start',''));val(rpc('jana_finalize_picking',f['atok'],o['id']))
 if delivered:
  val(rpc('jana_ops_transition',f['ct'],o['id'],'dispatch',''));val(rpc('jana_critical_write',f['ct'],'return-fixture-deliver','order.deliver',{'order_id':o['id'],'code':o['delivery_code']}))
 f['order']=o;f['source']=val("SELECT to_jsonb(m) FROM stock_movements m WHERE reference="+literal(o['id'])+" AND reason='order_picked';");return f

def body(f,qty=500,ref='RETURN-FIXTURE',**more):return {'source_movement_id':f['source']['id'],'quantity_base':qty,'reference':ref,'reason':'Actual returned goods fixture',**more}
def receive(f,key='receive-return-fixture',payload=None):return rpc('jana_customer_return_receive',f['atok'],key,payload or body(f))
def inspect(f,r,accepted,key='inspect-return-fixture'):return rpc('jana_customer_return_inspect',f['atok'],key,{'return_id':r['id'],'accepted_base':accepted,'note':'Recorded physical quality inspection fixture'})
def lot(f):return val('SELECT to_jsonb(l) FROM inventory_lots l WHERE id='+literal(f['p']+'l')+';')
def order_row(f):return val('SELECT to_jsonb(o) FROM orders o WHERE id='+literal(f['order']['id'])+';')
def history(f):return val(rpc('jana_customer_returns',f['atok']))

f=prepared();before=balance(f);original_order=order_row(f);rows=successful(race([receive(f)]*16));assert len(rows)==16 and all(x==rows[0] for x in rows);r=rows[0];assert balance(f)==before and order_row(f)==original_order;assert val('SELECT count(*) FROM customer_return_receipts WHERE id='+literal(r['id'])+';')==1;assert val('SELECT count(*) FROM stock_movements WHERE reference='+literal(r['id'])+" AND reason='customer_return_received' AND on_hand_delta=0 AND reserved_delta=0;")==1;passed('sixteen receive retries create one quarantined receipt without changing stock order or cash')
fails(receive(f,payload=body(f,501)),'idempotency_conflict');fails(receive(f,'same-reference-new-key'),'return_reference_exists');passed('changed request reuse and repeated physical document cannot receive goods twice')
rows=successful(race([inspect(f,r,400)]*16));assert len(rows)==16 and all(x==rows[0] for x in rows);i=rows[0];assert i['accepted_base']==400 and i['rejected_base']==100 and i['restored_cost_halalas']==40 and i['cost_basis']=='recorded';assert balance(f)['on_hand']==before['on_hand']+400 and balance(f)['reserved']==before['reserved'];assert lot(f)['remaining_cost_halalas']==940;assert order_row(f)==original_order;assert val('SELECT count(*) FROM inventory_cost_entries WHERE movement_id='+literal(i['movement_id'])+';')==1;assert val('SELECT to_jsonb(order_id::text= '+literal(f['order']['id'])+') FROM inventory_cost_entries WHERE movement_id='+literal(i['movement_id'])+';');passed('sixteen inspection retries restock accepted quantity and original cost once while rejecting the remainder')
fails(inspect(f,r,400,'different-inspection-key'),'return_already_inspected');fails(inspect(f,r,401),'idempotency_conflict');assert val(receive(f))==r;passed('completed receipt and inspection return their original idempotent results after stock changes')
for table,key in [('customer_return_receipts','id'),('customer_return_inspections','return_id')]:fails('DELETE FROM '+table+' WHERE '+key+'='+literal(r['id'])+';','append_only')
fails('UPDATE customer_return_receipts SET quantity_base=1 WHERE id='+literal(r['id'])+';','append_only');passed('receipt source terms and quality decision remain append-only')

ledger=val(rpc('jana_stock_movement_history',f['atok'],{'reference':'RETURN-FIXTURE'}));assert len(ledger['items'])==2 and all(x['document_reference']=='RETURN-FIXTURE' for x in ledger['items']);assert sum(x['on_hand_delta'] for x in ledger['items'])==400;passed('general stock history resolves the actual return document for receipt and accepted inspection movements')

f=prepared();rows=race([receive(f,'receipt-race-one',body(f,600,'FIRST')),receive(f,'receipt-race-two',body(f,600,'SECOND'))]);assert len(successful(rows))==1 and all(x['ok'] or 'return_exceeds_shipped' in x['error'] for x in rows);assert val('SELECT sum(quantity_base) FROM customer_return_receipts WHERE source_movement_id='+literal(f['source']['id'])+';')==600;passed('concurrent physical receipts cannot exceed the exact original shipped quantity')
f=prepared();r=val(receive(f));before=balance(f);rows=race([inspect(f,r,500,'quality-decision-one'),inspect(f,r,200,'quality-decision-two')]);assert len(successful(rows))==1;assert balance(f)['on_hand']==before['on_hand']+successful(rows)[0]['accepted_base'];assert all(x['ok'] or 'return_already_inspected' in x['error'] for x in rows);passed('competing inspectors cannot publish two quality decisions or duplicate stock')
f=prepared();r=val(receive(f));before=lot(f);i=val(inspect(f,r,0));assert i['accepted_base']==0 and i['rejected_base']==500 and i['restored_cost_halalas'] is None and i['cost_basis'] is None;assert lot(f)==before;assert val('SELECT count(*) FROM inventory_cost_entries WHERE movement_id='+literal(i['movement_id'])+';')==0;passed('rejected returned goods remain quarantined without usable stock or a second consumption charge')

f=prepared();bad=body(f)
for key,v in [('quantity_base',0),('quantity_base',-1),('quantity_base',1.5),('quantity_base','1'),('reference',''),('reason','x'),('actor_id','untrusted')]:fails(receive(f,'invalid-return-input',{**bad,key:v}),'return_validation')
bad_source=val('SELECT to_jsonb(m) FROM stock_movements m WHERE stock_id='+literal(f['p']+'st')+" AND on_hand_delta=0 LIMIT 1;");fails(receive(f,'non-shipped-source',{**bad,'source_movement_id':bad_source['id']}),'return_source_invalid');r=val(receive(f));fails(inspect(f,r,501),'return_validation');fails(rpc('jana_customer_return_inspect',f['atok'],'invalid-return-inspection',{'return_id':r['id'],'accepted_base':'10','note':'Invalid typed number'}),'return_validation');passed('strict canonical source quantity document and inspection input validation rejects fabricated terms')

f=prepared();r=val(receive(f));run('UPDATE inventory_lots SET expires_at=1 WHERE id='+literal(f['p']+'l')+';');before=balance(f);fails(inspect(f,r,500),'return_lot_not_restockable');assert balance(f)==before;assert val(inspect(f,r,0))['accepted_base']==0;passed('expired original lot can be rejected but never made sellable by a return')
f=prepared(unknown=True);r=val(receive(f));i=val(inspect(f,r,300));assert i['restored_cost_halalas'] is None and i['cost_basis']=='unknown';assert lot(f)['remaining_cost_halalas'] is None;passed('missing original purchase cost remains explicitly unknown on the return and pooled inventory')
f=prepared(cost=0);r=val(receive(f));i=val(inspect(f,r,300));assert i['restored_cost_halalas']==0 and i['cost_basis']=='recorded';passed('recorded zero return cost is distinct from unknown cost')
f=prepared(stock=1000,cost=1);assert lot(f)['on_hand_base']==0 and lot(f)['remaining_cost_halalas']==0;returned=0
for n,qty in enumerate([333,333,334]):
 r=val(receive(f,'rounding-receipt-'+str(n),body(f,qty,'ROUND-'+str(n))));i=val(inspect(f,r,qty,'rounding-inspection-'+str(n)));returned+=i['restored_cost_halalas'];assert returned<=1
assert returned==1 and lot(f)['on_hand_base']==1000 and lot(f)['remaining_cost_halalas']==1;assert val('SELECT sum(value_delta_halalas) FROM inventory_cost_entries WHERE order_id='+literal(f['order']['id'])+';')==0;passed('split return rounding conserves the full original shipment cost without inventing extra value')

f=prepared();r=val(receive(f));before=lot(f);run('BEGIN;'+inspect(f,r,500)+'ROLLBACK;');assert lot(f)==before and val('SELECT count(*) FROM customer_return_inspections WHERE return_id='+literal(r['id'])+';')==0;assert val(inspect(f,r,500))['accepted_base']==500;passed('inspection rollback releases every stock cost audit and idempotency change for a safe retry')
f=prepared(stock=1000);r=val(receive(f,payload=body(f,1000)));rows=race([inspect(f,r,1000),quote(f,'quote-versus-return')]);assert rows[0]['ok'] and (rows[1]['ok'] or 'insufficient' in rows[1]['error']);b=balance(f);assert b['on_hand']==1000 and b['reserved'] in (0,1000);passed('inspection and checkout share balance locks and never reserve quarantined units early')

f=prepared(delivered=False);fails(receive(f),'return_order_ineligible');fails(rpc('jana_customer_return_context',f['atok'],f['order']['number']),'return_order_ineligible');val(rpc('jana_ops_transition',f['ct'],f['order']['id'],'dispatch',''));val(rpc('jana_ops_transition',f['ct'],f['order']['id'],'fail','Customer unavailable fixture'));r=val(receive(f));fails(rpc('jana_ops_transition',f['ct'],f['order']['id'],'dispatch',''),'return_requires_resolution');assert order_row(f)['delivery_state']=='failed';passed('only delivered or failed shipments accept returns and a physically returned failed shipment cannot be redispatched')
f=prepared(delivered=False);val(rpc('jana_ops_transition',f['ct'],f['order']['id'],'dispatch',''));val(rpc('jana_ops_transition',f['ct'],f['order']['id'],'fail','Customer unavailable fixture'));rows=race([receive(f),rpc('jana_ops_transition',f['ct'],f['order']['id'],'dispatch','')]);assert len(successful(rows))==1 and all(x['ok'] or any(e in x['error'] for e in ['return_requires_resolution','return_order_ineligible']) for x in rows);passed('warehouse return receipt and courier redispatch serialize on the original order')

f=prepared();r=val(receive(f));count=val('SELECT jana_count_start('+literal(f['atok'])+','+literal('Returns physical count')+','+literal(json.dumps([f['p']+'l']))+'::jsonb)::text;');val(inspect(f,r,500));sessions=val(rpc('jana_inventory_counts',f['atok']));assert next(x for x in sessions if x['id']==count['id'])['counts'][0]['stale'];passed('restocked returned quantity invalidates an earlier physical-count baseline')
f=prepared();run('DO $batch$ BEGIN FOR i IN 1..52 LOOP PERFORM jana_customer_return_receive('+literal(f['atok'])+",'return-page-'||i,jsonb_build_object('source_movement_id',"+literal(f['source']['id'])+",'quantity_base',1,'reference','RETURN-PAGE-'||i,'reason','Return pagination fixture'));END LOOP;END $batch$;");first=history(f);assert len(first['items'])==50 and first['next'];cursor=first['next'];second=val(rpc('jana_customer_returns',f['atok'],cursor['before_at'],cursor['before_id']));assert not ({x['id'] for x in first['items']}&{x['id'] for x in second['items']});passed('return history is bounded and uses stable keyset pagination')
f=prepared();r=val(receive(f));val(inspect(f,r,100));fails(rpc('jana_customer_returns',f['t']),'forbidden');fails(rpc('jana_customer_return_receive',f['ct'],'courier-forged-return',body(f)),'forbidden');run("UPDATE users SET role='support' WHERE id="+literal(f['p']+'a')+';');item=next(x for x in history(f)['items'] if x['id']==r['id']);assert 'restored_cost_halalas' not in item['inspection'] and 'cost_basis' not in item['inspection'];assert 'recipient_phone' not in json.dumps(item);fails(receive(f),'forbidden');run("UPDATE users SET role='finance' WHERE id="+literal(f['p']+'a')+';');assert next(x for x in history(f)['items'] if x['id']==r['id'])['inspection']['restored_cost_halalas']==10;fails(inspect(f,r,100),'forbidden');passed('inventory and admin alone receive or inspect while support sees redacted status and finance sees cost evidence')
assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'jana_customer_return%' AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'));")==0;assert val("SELECT count(*) FROM pg_class WHERE relname IN ('customer_return_receipts','customer_return_inspections') AND relrowsecurity;")==2;assert val('SELECT jana_deep_health();')['ok'];passed('RLS service-only grants and existing stock slot order and cash invariants remain enforced')
print(json.dumps({'passed':len(checks),'checks':checks}))
