from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r
def write(f,key,kind,changes,id=None,revision=None,reason='مراجعة إعدادات التوصيل'):
 return rpc('jana_delivery_admin_write',f['atok'],key,kind+'.save',{'id':id,'revision':revision,'reason':reason,'changes':changes})
def slot(f):return val('SELECT to_jsonb(s) FROM delivery_slots s WHERE id='+literal(f['p']+'s')+';')
def zone(f):return val("SELECT to_jsonb(z)-'geom' FROM delivery_zones z WHERE id="+literal(f['p']+'z')+';')
polygon={'type':'Polygon','coordinates':[[[42,16],[43,16],[43,17],[42,17],[42,16]]]}
f=fixture();z=val(write(f,'create-zone','zone',{'name':'منطقة مستقبلية','polygon':polygon,'fee_halalas':500,'minimum_halalas':0,'metadata':{'city':'جازان'}}));assert len(z['id'])<=36 and z['revision']==1 and z['metadata']['city']=='جازان';same=val(write(f,'create-zone','zone',{'name':'منطقة مستقبلية','polygon':polygon,'fee_halalas':500,'minimum_halalas':0,'metadata':{'city':'جازان'}}));assert same==z;passed('zone creation fits schema and retries retain one audited result')
invalid={'type':'Polygon','coordinates':[[[42,16],[43,17],[43,16],[42,17],[42,16]]]};fails(write(f,'invalid-polygon','zone',{'polygon':invalid},z['id'],1),'invalid_delivery_polygon');fails(write(f,'invalid-money','zone',{'fee_halalas':None},z['id'],1),'delivery_validation');fails(write(f,'invalid-boolean','zone',{'active':'false'},z['id'],1),'delivery_validation');passed('invalid polygons null money and non-boolean activation are rejected')
z2=val(write(f,'zone-price-update','zone',{'fee_halalas':700,'active':False},z['id'],1));assert z2['revision']==2 and not z2['active'];fails(write(f,'stale-zone-change','zone',{'name':'تعديل قديم'},z['id'],1),'delivery_changed');assert val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(z['id'])+';')==2;passed('zone revisions reject stale edits and history records before after and reason')
f=fixture();q=val(quote(f,'old-price-quote'));z=zone(f);val(write(f,'zone-fee-after-quote','zone',{'fee_halalas':700,'minimum_halalas':100},z['id'],z['revision']));o=val(rpc('jana_confirm_order',f['t'],q['id']));assert o['total_halalas']==2000;q2=val(quote(f,'new-price-quote'));assert q2['total_halalas']==2700;passed('zone price edits affect new quotes while reserved commercial terms remain unchanged')
z=zone(f);val(write(f,'zone-deactivate','zone',{'active':False},z['id'],z['revision']));fails(quote(f,'disabled-zone-quote'),'zone_unavailable');passed('zone deactivation stops new checkout coverage without rewriting orders')
f=fixture();s=slot(f);changes={k:s[k] for k in ['zone_id','starts_at','ends_at','cutoff_at']};changes['capacity']=2;rows=successful(race([write(f,'new-slot-idempotent','slot',changes)]*8));assert len(rows)==8 and all(x==rows[0] for x in rows) and len(rows[0]['id'])<=36;passed('eight slot creation retries create one valid scheduled window')
fails(write(f,'bad-slot-window','slot',{**changes,'ends_at':changes['starts_at']}),'delivery_validation');fails(write(f,'bad-slot-capacity','slot',{**changes,'capacity':1.5}),'delivery_validation');fails(write(f,'missing-slot-time','slot',{'zone_id':s['zone_id'],'capacity':2}),'delivery_validation');passed('slot creation rejects invalid missing or fractional scheduling inputs')
f=fixture(capacity=2);s=slot(f);val(quote(f,'first-booking'));s2=slot(f);assert s2['revision']==s['revision'];r=race([quote(f,'last-booking'),write(f,'reduce-capacity','slot',{'capacity':1},s['id'],s['revision'])]);assert len(successful(r))==1;assert all(x['ok'] or any(c in x['error'] for c in ['slot_below_booked','slot_unavailable']) for x in r);assert balance(f)['booked']<=balance(f)['capacity'];passed('capacity decrease and last-slot reservation serialize without overbooking')
s=slot(f);fails(write(f,'reschedule-booked','slot',{'starts_at':s['starts_at']+60000,'ends_at':s['ends_at']+60000},s['id'],s['revision']),'slot_schedule_immutable');fails('UPDATE delivery_slots SET starts_at=starts_at+1000 WHERE id='+literal(s['id'])+';','slot_schedule_immutable');passed('historical booked schedules cannot be silently moved through RPC or direct updates')
s=slot(f);r=val(write(f,'disable-slot','slot',{'active':False},s['id'],s['revision']));assert not r['active'] and r['revision']==s['revision']+1;fails(write(f,'stale-slot-change','slot',{'capacity':20},s['id'],s['revision']),'delivery_changed');passed('slot activation is revisioned while reservation counts remain authoritative')
f=fixture();fails(rpc('jana_delivery_admin_write',f['t'],'customer-zone-write','zone.save',{'changes':{},'reason':'Unauthorized role'}),'forbidden');fails(write(f,'missing-zone-reason','zone',{},f['p']+'z',1,reason=''),'delivery_validation');assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN ('jana_save_delivery_zone','jana_save_delivery_slot','jana_delivery_admin_write','jana_slot_history_guard','jana_delivery_revision') AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'));")==0;assert val('SELECT jana_deep_health();')['ok'];passed('delivery writes remain admin-only audited and inaccessible to direct clients')
print(json.dumps({'passed':len(checks),'checks':checks}))
