from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(query,code):
 result=run(query,False);assert not result['ok'] and code in result['error'],result

def context(f):return val(rpc('jana_inventory_disposal_context',f['atok'],f['p']+'l'))
def payload(f,**changes):
 result={'lot_id':f['p']+'l','kind':'waste','quantity_base':100,'revision':context(f)['quantity_revision'],'reason':'Actual disposal fixture','reference':'FIXTURE-DISPOSAL'};result.update(changes);return result

def dispose(f,key,body):return rpc('jana_inventory_dispose',f['atok'],key,body)
def history(f):return val(rpc('jana_inventory_disposals',f['atok']))

f=fixture();before=context(f);body=payload(f,quantity_base=700);rows=successful(race([dispose(f,'same-disposal-retry',body)]*16));assert len(rows)==16 and all(x==rows[0] for x in rows);event=rows[0];assert event['after_on_hand']==9300 and event['value_halalas']==70 and event['cost_basis']=='recorded';assert balance(f)['on_hand']==9300 and context(f)['remaining_cost_halalas']==930;assert val('SELECT count(*) FROM stock_movements WHERE id='+literal(event['movement_id'])+';')==1;assert val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(event['id'])+" AND action='inventory_disposed';")==1;passed('sixteen retries record one disposal movement cost entry and audit event')
fails(dispose(f,'same-disposal-retry',{**body,'quantity_base':701}),'idempotency_conflict');fails(dispose(f,'duplicate-business-reference',payload(f,quantity_base=700)),'disposal_reference_exists');assert balance(f)['on_hand']==9300;passed('changed retry payload and duplicate lot-kind document cannot double-decrement stock')
fails('UPDATE inventory_disposals SET reason=\'changed\' WHERE id='+literal(event['id'])+';','append_only');fails('DELETE FROM inventory_disposals WHERE id='+literal(event['id'])+';','append_only');passed('disposal evidence is append-only')

f=fixture();body=payload(f);val(rpc('jana_inventory_adjust_lot',f['atok'],f['p']+'l',9999,'Intervening physical movement'));val(rpc('jana_inventory_adjust_lot',f['atok'],f['p']+'l',10000,'Restored quantity after movement'));fails(dispose(f,'stale-disposal-view',body),'disposal_stale');assert balance(f)['on_hand']==10000;passed('physical revision rejects a stale view even when quantity returns to its old value')
f=fixture(stock=1000);q=val(quote(f,'reserved-before-disposal'));fails(dispose(f,'reserved-disposal-blocked',payload(f,quantity_base=1)),'disposal_exceeds_unreserved');assert balance(f)['on_hand']==1000 and balance(f)['reserved']==1000;val(rpc('jana_cancel_quote',f['t'],q['id']));passed('disposal cannot consume already reserved inventory')
f=fixture(stock=1000);r=race([quote(f,'last-stock-disposal-race'),dispose(f,'competing-disposal',payload(f,quantity_base=1))]);assert len(successful(r))==1,r;assert all(x['ok'] or any(c in x['error'] for c in ['disposal_exceeds_unreserved','insufficient_stock']) for x in r);assert balance(f)['reserved']<=balance(f)['on_hand'];passed('last-stock checkout and physical disposal serialize against the same balance')
f=fixture(stock=1000);body=payload(f,quantity_base=700);r=race([dispose(f,'disposal-one',body),dispose(f,'disposal-two',{**body,'reference':'SECOND-FIXTURE'})]);assert len(successful(r))==1 and balance(f)['on_hand']==300;r=[x for x in r if not x['ok']];assert 'disposal_stale' in r[0]['error'];passed('two different disposal documents cannot act on the same stale physical quantity')

f=fixture();before=balance(f);base=payload(f)
for field,value in [('quantity_base',0),('quantity_base',-1),('quantity_base',1.5),('quantity_base','100'),('revision',None),('kind','receipt'),('reason','x'),('reference','')]:fails(dispose(f,'invalid-disposal-payload',{**base,field:value}),'disposal_validation')
assert balance(f)==before;passed('strictly typed quantity revision kind reason and document validation rolls back')
f=fixture();received=val(rpc('jana_inventory_write',f['atok'],'receive-disposal-fixture','lot.receive',{'stock_id':f['p']+'st','supplier_id':None,'received_base':1000,'total_cost_halalas':100,'expires_at':4102444800000,'receipt_reference':'DISPOSAL-RECEIPT'}));pending={'lot_id':received['id'],'kind':'damage','quantity_base':1,'revision':0,'reason':'Pending lot disposal fixture','reference':'PENDING-FIXTURE'};fails(dispose(f,'pending-inspection-disposal',pending),'disposal_requires_accepted_lot');val(rpc('jana_inventory_inspect_lot',f['atok'],received['id'],'rejected','Rejected fixture'));fails(dispose(f,'rejected-inspection-disposal',{**pending,'revision':1}),'disposal_requires_accepted_lot');assert balance(f)['on_hand']==10000;passed('pending and rejected receipts cannot be disposed as usable inventory')

f=fixture();run('UPDATE inventory_lots SET total_cost_halalas=NULL,remaining_cost_halalas=NULL,cost_basis=\'unknown\' WHERE id='+literal(f['p']+'l')+';');event=val(dispose(f,'unknown-cost-disposal',payload(f)));assert event['value_halalas'] is None and event['cost_basis']=='unknown' and context(f)['remaining_cost_halalas'] is None;passed('unknown purchase cost is never represented as zero loss')
f=fixture();run('UPDATE inventory_lots SET total_cost_halalas=0,remaining_cost_halalas=0,cost_basis=\'recorded\' WHERE id='+literal(f['p']+'l')+';');event=val(dispose(f,'recorded-zero-disposal',payload(f,kind='damage')));assert event['value_halalas']==0 and event['cost_basis']=='recorded';passed('recorded zero cost stays distinct from missing cost')
f=fixture();fails(dispose(f,'supplier-required-disposal',payload(f,kind='supplier_return')),'disposal_supplier_required');supplier=val(rpc('jana_admin_create_supplier',f['atok'],'Disposal fixture supplier',''));run('UPDATE inventory_lots SET supplier_id='+literal(supplier['id'])+' WHERE id='+literal(f['p']+'l')+';');event=val(dispose(f,'supplier-return-recorded',payload(f,kind='supplier_return')));assert event['kind']=='supplier_return' and event['after_on_hand']==9900;passed('supplier returns require canonical supplier linkage and only record physical outbound stock')

f=fixture();session=val('SELECT jana_count_start('+literal(f['atok'])+','+literal('Disposal concurrent count')+','+literal(json.dumps([f['p']+'l']))+'::jsonb)::text;')
counts=val(rpc('jana_inventory_counts',f['atok']));line=next(s for s in counts if s['id']==session['id'])['counts'][0];val(rpc('jana_inventory_dispose',f['atok'],'invalidate-physical-count',payload(f)));counts=val(rpc('jana_inventory_counts',f['atok']));assert next(s for s in counts if s['id']==session['id'])['counts'][0]['stale'];passed('a disposal invalidates an earlier physical count instead of silently applying its old baseline')

f=fixture();revision=context(f)['quantity_revision'];run('DO $batch$ BEGIN FOR i IN 1..52 LOOP PERFORM jana_inventory_dispose('+literal(f['atok'])+",'page-disposal-'||i,jsonb_build_object('lot_id',"+literal(f['p']+'l')+",'kind','waste','quantity_base',1,'revision',"+str(revision)+"+i-1,'reason','Pagination fixture disposal','reference','PAGE-'||i)); END LOOP;END $batch$;")
first=history(f);assert len(first['items'])==50 and first['next'];cursor=first['next'];second=val(rpc('jana_inventory_disposals',f['atok'],cursor['before_at'],cursor['before_id']));assert not ({x['id'] for x in first['items']}&{x['id'] for x in second['items']});passed('history uses bounded stable keyset pages with no duplicate event IDs')
fails(rpc('jana_inventory_disposals',f['t']),'forbidden');fails(rpc('jana_inventory_disposal_context',f['ct'],f['p']+'l'),'forbidden');fails(rpc('jana_inventory_dispose',f['t'],'customer-disposal-denied',payload(f)),'forbidden');run("UPDATE users SET role='finance' WHERE id="+literal(f['p']+'a')+';');assert history(f)['items'];fails(dispose(f,'finance-disposal-denied',{'lot_id':f['p']+'l'}),'forbidden');passed('finance can review evidence but only inventory and admin may dispose stock')
assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN ('jana_inventory_dispose','jana_inventory_disposals','jana_inventory_disposal_context') AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'));")==0;assert val('SELECT jana_deep_health();')['ok'];passed('application privileges and stock slot cash invariants remain enforced')
print(json.dumps({'passed':len(checks),'checks':checks}))
