from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r

def order(f,collect=True):
 q=val(quote(f,'finance-quote'));o=val(rpc('jana_critical_write',f['t'],'finance-confirm','order.confirm',{'quote_id':q['id']}));val(rpc('jana_ops_transition',f['atok'],o['id'],'start',''));val(rpc('jana_finalize_picking',f['atok'],o['id']));val(rpc('jana_ops_transition',f['ct'],o['id'],'dispatch',''));val(rpc('jana_critical_write',f['ct'],'finance-deliver','order.deliver',{'order_id':o['id'],'code':o['delivery_code']}))
 if collect:val(rpc('jana_critical_write',f['ct'],'finance-collect','cod.collect',{'order_id':o['id'],'amount_halalas':o['total_halalas']}))
 return o

def current(o):return val('SELECT to_jsonb(o) FROM orders o WHERE id='+literal(o['id'])+';')
def due(o):
 r=current(o);return r['collected_halalas']-r['settled_halalas']-r['courier_refunded_halalas']
def paid(f,o,key,amount,source='finance',reference=None):return rpc('jana_critical_write',f['atok'],key,'refund.create',{'order_id':o['id'],'amount_halalas':amount,'reason':'Disposable actual refund fixture','reference':reference or key+'-payment','payment_source':source})
def request(f,o,key,amount):return rpc('jana_critical_write',f['t'],key,'refund.request',{'order_id':o['id'],'component_id':None,'amount_halalas':amount,'reason':'Disposable customer refund request'})
def settle(f,o,key,amount=None):
 b={'order_id':o['id'],'reference':key+'-deposit'}
 if amount is not None:b['amount_halalas']=amount
 return rpc('jana_critical_write',f['atok'],key,'cod.settle',b)
f=fixture();o=order(f,False);assert due(o)==0 and current(o)['cash_state']=='uncollected';assert val('SELECT count(*) FROM cash_entries WHERE order_id='+literal(o['id'])+';')==0;fails(request(f,o,'refund-before-cash',100),'refund_amount_invalid');passed('delivery alone creates neither cash liability nor refundable collected money')
val(rpc('jana_critical_write',f['ct'],'finance-collect','cod.collect',{'order_id':o['id'],'amount_halalas':2000}));assert due(o)==2000;assert val('SELECT count(*) FROM cash_entries WHERE order_id='+literal(o['id'])+';')==1;passed('cash collection records one courier liability entry')
fails(rpc('jana_admin_refund',f['atok'],o['id'],100,'Missing payment proof'),'refund_reference_required');fails(rpc('jana_critical_write',f['atok'],'no-reference-refund','refund.create',{'order_id':o['id'],'amount_halalas':100,'reason':'Missing proof','payment_source':'finance'}),'refund_reference_required');passed('refund completion cannot invent its payment reference')
r=val(request(f,o,'request-money-only',100));assert current(o)['refunded_halalas']==0 and due(o)==2000;val(rpc('jana_critical_write',f['atok'],'pay-requested-refund','refund.complete',{'refund_id':r['id'],'reference':'Company paid fixture','payment_source':'finance'}));assert current(o)['refunded_halalas']==100 and due(o)==2000;passed('customer request is not payment and company-funded refund leaves courier liability unchanged')
r=val(settle(f,o,'partial-deposit',700));assert r['cash_state']=='with_courier' and r['settled_halalas']==700 and due(o)==1300;fails(settle(f,o,'excess-deposit',1301),'courier_liability_exceeded');assert due(o)==1300;passed('partial settlement reduces liability and excessive settlement rolls back')
val(paid(f,o,'cash-refund',300,'courier'));assert due(o)==1000 and current(o)['courier_refunded_halalas']==300;assert val('SELECT count(*) FROM cash_entries WHERE order_id='+literal(o['id'])+" AND kind='refund';")==1;passed('refund from courier cash reduces only that cash liability')
val(settle(f,o,'final-deposit'));assert due(o)==0 and current(o)['settled_halalas']==1700 and current(o)['cash_state']=='settled';val(paid(f,o,'refund-after-settlement',100,'finance'));assert due(o)==0 and current(o)['cash_state']=='settled';fails(paid(f,o,'cash-after-settlement',100,'courier'),'courier_liability_exceeded');passed('company refund after settlement does not reopen courier liability or consume cash twice')
f2=fixture();o2=order(f2);accepted=successful(race([request(f2,o2,'pending-refund-'+str(i),1500) for i in range(8)]));assert len(accepted)==1;rf=accepted[0];assert current(o2)['refunded_halalas']==0;passed('concurrent pending requests cannot reserve more than collected money')
val(rpc('jana_critical_write',f2['atok'],'reject-refund-key','refund.reject',{'refund_id':rf['id'],'reason':'Disposable rejection'}));newrf=val(request(f2,o2,'refund-after-rejection',1800));fails(rpc('jana_critical_write',f2['atok'],'complete-rejected-key','refund.complete',{'refund_id':rf['id'],'reference':'Invalid completion','payment_source':'finance'}),'invalid_refund_state');passed('rejection releases requested amount and cannot later be completed')
completed=successful(race([rpc('jana_critical_write',f2['atok'],'same-refund-complete','refund.complete',{'refund_id':newrf['id'],'reference':'Actual company fixture','payment_source':'finance'})]*16));assert len(completed)==16 and all(x==completed[0] for x in completed);assert current(o2)['refunded_halalas']==1800 and due(o2)==2000;passed('sixteen completion retries record one refund and preserve correct cash source')
f3=fixture();o3=order(f3);results=successful(race([settle(f3,o3,'deposit-race-'+str(i),1500) for i in range(8)]));assert len(results)==1 and due(o3)==500;passed('concurrent partial settlements cannot exceed the last courier balance')
f4=fixture();o4=order(f4);rf=val(request(f4,o4,'refund-settlement-request',1000));results=successful(race([settle(f4,o4,'refund-settlement-deposit',1500),rpc('jana_critical_write',f4['atok'],'refund-settlement-payment','refund.complete',{'refund_id':rf['id'],'reference':'Courier cash fixture','payment_source':'courier'})]));assert len(results)==1 and due(o4) in (500,1000);passed('courier refund and settlement race serialize against the same liability')
f5=fixture();o5=order(f5);val(paid(f5,o5,'reference-once-a',100,'finance','Same payment receipt'));fails(paid(f5,o5,'reference-once-b',100,'finance','Same payment receipt'),'duplicate key');assert current(o5)['refunded_halalas']==100;passed('same payment reference cannot be recorded twice for one order')
val(settle(f5,o5,'same-deposit-reference',100));fails(rpc('jana_critical_write',f5['atok'],'different-deposit-key','cod.settle',{'order_id':o5['id'],'amount_halalas':100,'reference':'same-deposit-reference-deposit'}),'duplicate key');assert due(o5)==1900;passed('duplicate settlement reference with a new key rolls back account and ledger together')
fails('UPDATE orders SET settled_halalas=settled_halalas+1 WHERE id='+literal(o5['id'])+';','cash_ledger_mismatch');fails('UPDATE cash_entries SET amount_halalas=1 WHERE order_id='+literal(o5['id'])+';','append_only_ledger');fails('UPDATE refunds SET amount_halalas=1 WHERE order_id='+literal(o5['id'])+" AND state='completed';",'immutable_refund_history');passed('deferred reconciliation prevents unjournaled balance changes and immutable records preserve history')
fails(rpc('jana_critical_write',f5['ct'],'courier-refund-denied','refund.create',{'order_id':o5['id'],'amount_halalas':100,'reason':'No authority','reference':'No authority','payment_source':'finance'}),'forbidden');fails(rpc('jana_finance_overview',f5['t']),'forbidden');assert val("SELECT count(*) FROM information_schema.role_table_grants WHERE table_name='cash_entries' AND grantee IN ('anon','authenticated','PUBLIC');")==0;passed('courier cannot issue refunds and customer cannot read financial ledger')
health=val('SELECT jana_deep_health();');assert health['ok'] and health['cash_ledger_mismatches']==0;overview=val(rpc('jana_finance_overview',f5['atok']));reports=val(rpc('jana_admin_reports',f5['atok']));assert sum(x['liability_halalas'] for x in overview['couriers'])==reports['cash_unsettled_halalas'];passed('financial overview reports and all ledgers reconcile after concurrent journeys')
print(json.dumps({'passed':len(checks),'checks':checks}))
