from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r
def write(f,key,operation,payload):return rpc('jana_inventory_write',f['atok'],key,operation,payload)
def detail(f,s):return next(x for x in val(rpc('jana_inventory_counts',f['atok'])) if x['id']==s['id'])
def start(f,key='count-start'):return val(write(f,key,'count.start',{'location':'مستودع الاختبار — الرف الأول','lot_ids':[f['p']+'l']}))
def submit(f,s,quantity,key='count-submit'):
 c=detail(f,s)['counts'][0];return val(write(f,key,'count.submit',{'session_id':s['id'],'counts':[{'id':c['id'],'observed_base':quantity}],'note':'جرد فعلي في قاعدة الاختبار'}))
def decide(f,s,accept=True,key='count-approve'):
 c=detail(f,s)['counts'][0];return write(f,key,'count.decide',{'count_id':c['id'],'approve':accept,'reason':'مراجعة واعتماد الجرد الفعلي'})
def lot(f):return val('SELECT to_jsonb(l) FROM inventory_lots l WHERE id='+literal(f['p']+'l')+';')

f=fixture();s=start(f);d=detail(f,s);assert d['state']=='open' and d['counts'][0]['expected_base']==10000 and balance(f)['on_hand']==10000;submit(f,s,9700);d=detail(f,s);assert d['state']=='submitted' and d['counts'][0]['observed_base']==9700 and balance(f)['on_hand']==10000;passed('count start and submission preserve baseline and never silently overwrite usable stock')
rows=successful(race([decide(f,s)]*16));assert len(rows)==16 and all(x==rows[0] for x in rows);assert balance(f)['on_hand']==9700 and lot(f)['remaining_cost_halalas']==970;d=detail(f,s);assert d['state']=='closed' and d['counts'][0]['state']=='approved' and d['counts'][0]['movement_id'];assert val('SELECT count(*) FROM stock_movements WHERE reference='+literal(d['counts'][0]['id'])+';')==1;passed('sixteen approval retries produce one documented adjustment and proportional cost entry')
fails('UPDATE count_requests SET observed_base=1 WHERE id='+literal(d['counts'][0]['id'])+';','immutable_count_history');fails('DELETE FROM count_requests WHERE id='+literal(d['counts'][0]['id'])+';','immutable_count_history');passed('approved count history cannot be rewritten or deleted')

f=fixture();s=start(f);submit(f,s,9900);val(rpc('jana_inventory_adjust_lot',f['atok'],f['p']+'l',9990,'Audited intervening movement'));fails(decide(f,s),'count_stale');assert balance(f)['on_hand']==9990 and detail(f,s)['counts'][0]['stale'];val(decide(f,s,False,'reject-stale'));assert balance(f)['on_hand']==9990;passed('intervening physical movement requires recount and rejection never alters current stock')
f=fixture();s=start(f);submit(f,s,9900);val(rpc('jana_inventory_adjust_lot',f['atok'],f['p']+'l',9990,'Temporary counted movement'));val(rpc('jana_inventory_adjust_lot',f['atok'],f['p']+'l',10000,'Quantity returned after movement'));fails(decide(f,s),'count_stale');passed('quantity revision detects movement even when on-hand returns to the original number')

f=fixture(stock=1000);s=start(f);submit(f,s,500);q=val(quote(f,'stock-reserved-after-count'));fails(decide(f,s),'count_below_reserved');assert balance(f)['reserved']==1000 and balance(f)['on_hand']==1000;val(rpc('jana_cancel_quote',f['t'],q['id']));val(decide(f,s));assert balance(f)['on_hand']==500;passed('approval cannot reduce physical stock below current reservations')
f=fixture(stock=1000);s=start(f);submit(f,s,500);r=race([quote(f,'count-quote-race'),decide(f,s)]);assert len(successful(r))==1;assert all(x['ok'] or any(c in x['error'] for c in ['count_below_reserved','insufficient_stock']) for x in r);assert balance(f)['reserved']<=balance(f)['on_hand'];passed('checkout and count approval serialize safely against the same stock balance')

f=fixture();s=start(f);submit(f,s,10000);val(decide(f,s));assert detail(f,s)['counts'][0]['movement_id'] is None;assert balance(f)['on_hand']==10000;passed('a matching count closes with approval but creates no invented stock movement')
f=fixture();s=start(f);val(write(f,'cancel-count-session','count.cancel',{'session_id':s['id'],'reason':'إلغاء لبدء عد جديد'}));assert detail(f,s)['state']=='cancelled' and detail(f,s)['counts'][0]['state']=='cancelled';assert balance(f)['on_hand']==10000;passed('cancelled count retains evidence without changing inventory')

f=fixture();fails(write(f,'bad-count-missing','count.start',{'location':'رف الاختبار','lot_ids':['missing-lot']}),'lot_not_found');fails(write(f,'duplicate-count-lot','count.start',{'location':'رف الاختبار','lot_ids':[f['p']+'l']*2}),'count_validation');s=start(f);c=detail(f,s)['counts'][0];fails(write(f,'fraction-count','count.submit',{'session_id':s['id'],'counts':[{'id':c['id'],'observed_base':1.5}],'note':'Invalid fractional base quantity'}),'count_validation');assert detail(f,s)['state']=='open';passed('invalid missing duplicate or fractional count inputs roll back')

f=fixture();payload={'stock_id':f['p']+'st','supplier_id':None,'received_base':1000,'total_cost_halalas':None,'expires_at':4102444800000,'receipt_reference':'Receiving fixture reference'};rows=successful(race([write(f,'receipt-same-key','lot.receive',payload)]*8));assert len(rows)==8 and len({x['id'] for x in rows})==1;l=rows[0];assert balance(f)['on_hand']==10000;assert val('SELECT count(*) FROM stock_movements WHERE lot_id='+literal(l['id'])+" AND reason='receipt_pending_inspection';")==1;val(write(f,'reject-received-lot','lot.inspect',{'lot_id':l['id'],'state':'rejected','note':'رفض بعد الفحص'}));assert balance(f)['on_hand']==10000;assert val('SELECT count(*) FROM stock_movements WHERE lot_id='+literal(l['id'])+" AND reason='inspection_rejected';")==1;passed('idempotent receiving and rejection each record a movement without adding usable stock')
fails(write(f,'count-rejected-lot','count.start',{'location':'رف الاختبار','lot_ids':[l['id']]}),'count_requires_accepted_lot');passed('pending or rejected lots cannot enter a usable-stock count session')

f=fixture();val(write(f,'stock-threshold-update','stock.update',{'stock_id':f['p']+'st','changes':{'name_en':'Fixture stock','category':'fruit','reorder_base':12000}}));c=val(rpc('jana_admin_catalog',f['atok']));st=next(x for x in c['stock'] if x['id']==f['p']+'st');assert st['stock_status']=='low' and st['available_base']==10000;val(write(f,'stock-threshold-lower','stock.update',{'stock_id':st['id'],'changes':{'reorder_base':500}}));st=next(x for x in val(rpc('jana_admin_catalog',f['atok']))['stock'] if x['id']==st['id']);assert st['stock_status']=='normal';fails(write(f,'stock-unit-denied','stock.update',{'stock_id':st['id'],'changes':{'base_unit':'piece'}}),'stock_unit_immutable');passed('stock-specific reorder levels govern low-stock status while base units stay immutable')

supplier=val(rpc('jana_admin_create_supplier',f['atok'],'مورد الاختبار',''));assert val('SELECT to_jsonb(created_at IS NOT NULL) FROM suppliers WHERE id='+literal(supplier['id'])+';');r=val(write(f,'supplier-details','supplier.update',{'supplier_id':supplier['id'],'changes':{'email':'fixture@example.invalid','notes':'Supplier fixture note','active':False}}));assert not r['active'] and r['email']=='fixture@example.invalid';fails(write(f,'supplier-invalid-email','supplier.update',{'supplier_id':supplier['id'],'changes':{'email':'invalid'}}),'supplier_validation');passed('supplier contact notes and deactivation are validated and audited')

f=fixture();batch={'schema_version':1,'items':[{'name':'تفاح مخزون مستورد','name_en':'Imported apples','category':'fruit','base_unit':'gram','reorder_base':1500},{'name':'صندوق مخزون مستورد','name_en':'','category':'packaging','base_unit':'piece','reorder_base':None}]};before={'stock':val('SELECT count(*) FROM stock_items;'),'lots':val('SELECT count(*) FROM inventory_lots;'),'movements':val('SELECT count(*) FROM stock_movements;')};imported=val(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-safe-key',batch));assert imported['imported_count']==2 and len(imported['items'])==2;ids=[x['id'] for x in imported['items']];rows=val('SELECT jsonb_agg(to_jsonb(x) ORDER BY id) FROM (SELECT s.id,s.active,s.base_unit,s.reorder_base,b.on_hand_base,b.reserved_base FROM stock_items s JOIN stock_balances b ON b.stock_id=s.id WHERE s.id=ANY('+literal('{'+','.join(ids)+'}')+'::text[]))x;');assert len(rows)==2 and all(not x['active'] and x['on_hand_base']==0 and x['reserved_base']==0 for x in rows);assert val('SELECT count(*) FROM inventory_lots;')==before['lots'] and val('SELECT count(*) FROM stock_movements;')==before['movements'];passed('one owner stock file atomically creates inactive definitions with zero balances and no lots or movements')
retry=val(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-safe-key',batch));assert retry==imported and val('SELECT count(*) FROM stock_items;')==before['stock']+2;changed={'schema_version':1,'items':[dict(batch['items'][0],name='اسم متغير')]};fails(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-safe-key',changed),'idempotency_conflict');passed('stock import retries return the exact definitions and changed key reuse is rejected')
duplicate={'schema_version':1,'items':[dict(batch['items'][0],name='اسم مكرر للمخزون'),dict(batch['items'][1],name='  اسم   مكرر   للمخزون  ')]};fails(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-duplicate-key',duplicate),'invalid_stock_import_duplicate_name');existing={'schema_version':1,'items':[dict(batch['items'][0],name=' تفاح   مخزون مستورد ')]};fails(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-existing-key',existing),'invalid_stock_import_existing_name');invalid={'schema_version':1,'items':[dict(batch['items'][0],name='صنف صالح قبل التراجع'),dict(batch['items'][1],name='صنف بوحدة خاطئة',base_unit='kg')]};count=val('SELECT count(*) FROM stock_items;');fails(rpc('jana_inventory_import_stock_master',f['atok'],'stock-import-rollback-key',invalid),'stock_import_validation');assert val('SELECT count(*) FROM stock_items;')==count;passed('duplicate existing and invalid stock rows are rejected without partial definitions')
r=race([rpc('jana_inventory_import_stock_master',f['atok'],'stock-race-key-one',{'schema_version':1,'items':[dict(batch['items'][0],name='صنف متزامن وحيد')]}),rpc('jana_inventory_import_stock_master',f['atok'],'stock-race-key-two',{'schema_version':1,'items':[dict(batch['items'][0],name='  صنف   متزامن وحيد ')]})]);assert len(successful(r))==1 and any('invalid_stock_import_existing_name' in x.get('error','') for x in r if not x['ok']);assert val("SELECT count(*) FROM stock_items WHERE lower(regexp_replace(trim(name),'\\s+',' ','g'))='صنف متزامن وحيد';")==1;passed('concurrent stock files cannot create the same normalized name twice')

fails(rpc('jana_inventory_counts',f['t']),'forbidden');fails(rpc('jana_inventory_import_stock_master',f['t'],'customer-stock-import',batch),'forbidden');fails(rpc('jana_inventory_write',f['ct'],'courier-count-denied','count.start',{'location':'Unauthorized count','lot_ids':[f['p']+'l']}),'forbidden');assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname IN ('jana_count_start','jana_count_submit','jana_count_decide','jana_inventory_write','jana_stock_health','jana_inventory_import_stock_master') AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'));")==0;assert val('SELECT jana_deep_health();')['ok'];passed('warehouse operations remain role-restricted and stock slot cash invariants hold')
f=fixture();run("UPDATE users SET role='inventory' WHERE id="+literal(f['p']+'a')+';')
payload={'name':'مورد موظف المستودع','phone':''};rows=successful(race([write(f,'inventory-create-supplier','supplier.create',payload)]*8));assert len(rows)==8 and all(r==rows[0] for r in rows);sid=rows[0]['id'];assert val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(sid)+" AND action='supplier_created';")==1;passed('inventory role can create a supplier through eight retries with one audited result')
fails(write(f,'inventory-create-supplier','supplier.create',{'name':'Changed supplier','phone':''}),'idempotency_conflict');fails(rpc('jana_inventory_write',f['t'],'customer-create-supplier','supplier.create',payload),'forbidden');fails(rpc('jana_inventory_write',f['ct'],'courier-create-supplier','supplier.create',payload),'forbidden');fails(write(f,'invalid-create-supplier','supplier.create',{'name':'x','phone':''}),'invalid_supplier');passed('supplier creation retains role validation and rejects altered retry payloads')
print(json.dumps({'passed':len(checks),'checks':checks}))
