import test from 'node:test';import assert from 'node:assert/strict';
import {createApiClient,restoreSession,ApiError} from '../mobile/api.mjs';
function store(){const m=new Map();return{getItemAsync:async k=>m.get(k)||null,setItemAsync:async(k,v)=>m.set(k,v),deleteItemAsync:async k=>m.delete(k)}}
const base='https://jana-fresh-app.onrender.com';
test('uncertain quote retry survives client restart with same key',async()=>{const storage=store();let key;const one=createApiClient({base,storage,fetchImpl:async(u,i)=>{key=i.headers['idempotency-key'];throw Error('offline')}});const opts={method:'POST',token:'fixture',body:{lines:[]}};await assert.rejects(one('/api/quotes',opts),e=>e.code==='NETWORK_UNKNOWN');const two=createApiClient({base,storage,fetchImpl:async(u,i)=>{assert.equal(i.headers['idempotency-key'],key);return Response.json({id:'quote'})}});assert.equal((await two('/api/quotes',opts)).id,'quote')});
test('retry metadata is isolated by session',async()=>{const storage=store(),keys=[];let counter=0;const request=createApiClient({base,storage,newKey:()=>String(++counter),fetchImpl:async(u,i)=>{keys.push(i.headers['idempotency-key']);throw Error('offline')}});for(const token of ['customer-one','customer-two'])await assert.rejects(request('/api/orders',{method:'POST',token,body:{quote_id:'same'}}));assert.notEqual(keys[0],keys[1])});
test('successful completed intent obtains a new key next time',async()=>{const storage=store(),keys=[];let counter=0;const request=createApiClient({base,storage,newKey:()=>String(++counter),fetchImpl:async(u,i)=>{keys.push(i.headers['idempotency-key']);return Response.json({ok:true})}});const opts={method:'POST',token:'fixture',body:{}};await request('/api/quotes',opts);await request('/api/quotes',opts);assert.notEqual(keys[0],keys[1])});
test('GET retries a transient server failure once',async()=>{let n=0;const request=createApiClient({base,storage:store(),fetchImpl:async()=>++n===1?Response.json({error:{code:'BUSY'}},{status:503}):Response.json({items:[]})});assert.deepEqual(await request('/api/catalog'),{items:[]});assert.equal(n,2)});
test('mutation timeout is explicit and not automatically retried',async()=>{let n=0;const request=createApiClient({base,storage:store(),timeoutMs:5,fetchImpl:async(u,i)=>{n++;return new Promise((resolve,reject)=>i.signal.addEventListener('abort',()=>reject(Error('timeout'))))}});await assert.rejects(request('/api/orders',{method:'POST',token:'fixture',body:{}}),e=>e.code==='NETWORK_UNKNOWN');assert.equal(n,1)});
test('network outage never deletes stored session',async()=>{const storage=store();await storage.setItemAsync('token','fixture');await assert.rejects(restoreSession({storage,key:'token',request:async()=>{throw new ApiError('offline','NETWORK_UNKNOWN')}}));assert.equal(await storage.getItemAsync('token'),'fixture')});
test('expired session is cleared only on authentication rejection',async()=>{const storage=store();await storage.setItemAsync('token','fixture');assert.deepEqual(await restoreSession({storage,key:'token',request:async()=>{throw new ApiError('expired','AUTH_REQUIRED',401)}}),{token:null,user:null});assert.equal(await storage.getItemAsync('token'),null)});
test('customer substitution approval retry survives restart with its original decision key',async()=>{
 const storage=store();let original;const path='/api/substitutions/sub-fixture/decision',options={method:'POST',token:'fixture',body:{accept:true}};
 const one=createApiClient({base,storage,fetchImpl:async(u,i)=>{original=i.headers['idempotency-key'];throw Error('offline after decision')}});await assert.rejects(one(path,options),e=>e.code==='NETWORK_UNKNOWN');
 const two=createApiClient({base,storage,fetchImpl:async(u,i)=>{assert.equal(i.headers['idempotency-key'],original);return Response.json({state:'accepted'})}});assert.equal((await two(path,options)).state,'accepted');
});
