from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(query,code):
 r=run(query,False);assert not r['ok'] and code in r['error'],r

def reset():run("UPDATE notification_outbox SET state='cancelled',lease_id=NULL,lease_until=NULL;UPDATE notification_channels SET enabled=false;")
def destination(f):run("INSERT INTO notification_destinations(user_id,channel,recipient,verified_at,verification_reference,consent_at,active) VALUES("+literal(f['p']+'u')+",'email','fixture@example.invalid',1,'VERIFIED-TEST-FIXTURE',1,true);")
def enqueue(f,event='outbox-fixture'):return rpc('jana_notification_insert_once',event,f['p']+'u','عنوان الاختبار','رسالة الاختبار')
def claim():return val(rpc('jana_notification_claim','email','resend','a'*64))
def finish(j,**changes):
 result={'outcome':'submitted','retryable':False,'provider_id':'provider-fixture'};result.update(changes);return rpc('jana_notification_finish',j['id'],j['lease_id'],result)
def setup():
 reset();f=fixture();destination(f);run("UPDATE notification_channels SET provider_scope=repeat('a',64),enabled=true,max_attempts=8 WHERE channel='email';");val(enqueue(f));return f

def due(j):run("UPDATE notification_outbox SET next_attempt_at=0 WHERE id="+literal(j['id'])+';')
reset();f=fixture();destination(f);val(enqueue(f));assert val('SELECT count(*) FROM notification_outbox;')==0;assert claim() is None;passed('disabled channels store in-app events without external jobs')
run("UPDATE notification_channels SET provider_scope=repeat('a',64),enabled=true WHERE channel='email';");g=fixture();val(enqueue(g));assert val('SELECT count(*) FROM notification_outbox;')==0;passed('an unverified destination is never derived from account email')
reset();f=fixture();destination(f);run("UPDATE notification_channels SET provider_scope=repeat('a',64),enabled=true WHERE channel='email';");rows=successful(race([enqueue(f,'one-event-retry')]*12));assert len(rows)==12 and all(x==rows[0] for x in rows);assert val('SELECT count(*) FROM notification_outbox;')==1;fails(rpc('jana_notification_insert_once','one-event-retry',f['p']+'u','changed','رسالة الاختبار'),'idempotency_conflict');passed('concurrent in-app producer retries persist one immutable event and one channel job')
jobs=successful(race([rpc('jana_notification_claim','email','resend','a'*64)]*12));jobs=[x for x in jobs if x];assert len(jobs)==1;j=jobs[0];assert j['attempt']==1;passed('parallel workers cannot lease the same due job')
r=val(finish(j));assert r['state']=='submitted';assert val(finish(j))==r;fails(finish(j,provider_id='changed-provider-id'),'idempotency_conflict');assert claim() is None;assert val("SELECT count(*) FROM notification_attempts WHERE job_id="+literal(j['id'])+" AND event='finished';")==1;passed('acknowledgement retries return the durable result without duplicating delivery attempts')
fails('UPDATE notification_outbox SET recipient=\'another@example.invalid\' WHERE id='+literal(j['id'])+';','notification_payload_immutable');fails('DELETE FROM notification_attempts WHERE job_id='+literal(j['id'])+';','append_only');passed('delivery payloads and attempt evidence cannot be silently rewritten')
f=setup();assert val(rpc('jana_notification_claim','email','resend','b'*64)) is None;run("UPDATE notification_channels SET provider_scope=repeat('b',64) WHERE channel='email';");assert val(rpc('jana_notification_claim','email','resend','b'*64)) is None;run("UPDATE notification_channels SET provider_scope=repeat('a',64) WHERE channel='email';");j=claim();assert j['attempt']==1;val(finish(j));passed('sender scope changes cannot silently move an old job to another sending identity')
f=setup();j=claim();retry={'outcome':'unknown','retryable':True,'error_code':'PROVIDER_UNAVAILABLE'};r=val(rpc('jana_notification_finish',j['id'],j['lease_id'],retry));assert r['state']=='retry';assert claim() is None;due(j);second=claim();assert second['id']==j['id'] and second['idempotency_key']==j['idempotency_key'] and second['lease_id']!=j['lease_id'];assert second['attempt']==2;assert val(rpc('jana_notification_finish',j['id'],j['lease_id'],retry))==r;val(finish(second));passed('unknown outcomes use delayed bounded retry with the same provider key and replay old acknowledgements')
f=setup();j=claim();run('UPDATE notification_outbox SET lease_until=0 WHERE id='+literal(j['id'])+';');second=claim();assert second['idempotency_key']==j['idempotency_key'] and second['attempt']==2;fails(finish(j),'notification_lease_stale');assert val("SELECT count(*) FROM notification_attempts WHERE job_id="+literal(j['id'])+" AND event='lease_expired' AND outcome='unknown';")==1;val(finish(second));passed('crashed worker leases expire into recorded uncertainty and fence stale acknowledgements')
f=setup();j=claim();run("UPDATE notification_outbox SET lease_until=0,attempt_count=max_attempts WHERE id="+literal(j['id'])+';');assert claim() is None;assert val('SELECT to_jsonb(state) FROM notification_outbox WHERE id='+literal(j['id'])+';')=='reconcile';passed('exhausted uncertain attempts require reconciliation instead of unbounded resend')
f=setup();j=claim();r=val(rpc('jana_notification_finish',j['id'],j['lease_id'],{'outcome':'not_submitted','retryable':False,'error_code':'EMAIL_DOMAIN_NOT_VERIFIED'}));assert r['state']=='dead_letter';passed('known unsent permanent failure remains visible without claiming success')
f=setup();j=claim();val(rpc('jana_notification_finish',j['id'],j['lease_id'],retry));due(j);second=claim();r=val(rpc('jana_notification_finish',second['id'],second['lease_id'],{'outcome':'not_submitted','retryable':False,'error_code':'EMAIL_DOMAIN_NOT_VERIFIED'}));assert r['state']=='reconcile';passed('a later known rejection cannot erase an earlier unknown delivery outcome')
f=setup();run("UPDATE notification_outbox SET state='cancelled';");run("INSERT INTO notifications(id,user_id,dedupe_key,title,body,is_read,created_at) VALUES("+literal(f['p']+'old')+','+literal(f['p']+'u')+','+literal(f['p']+'old-event')+",'Old fixture','Old fixture',false,(extract(epoch from clock_timestamp())*1000)::bigint-86400000);");assert claim() is None;assert val('SELECT to_jsonb(state) FROM notification_outbox WHERE notification_id='+literal(f['p']+'old')+';')=='dead_letter';passed('unattempted jobs outside the immutable provider window are never sent')
f=setup();run('UPDATE notification_destinations SET active=false WHERE user_id='+literal(f['p']+'u')+';');assert claim() is None;assert val('SELECT to_jsonb(state) FROM notification_outbox ORDER BY created_at DESC LIMIT 1;')=='cancelled';passed('revoked destinations prevent a first outbound attempt')
f=setup();j=claim()
for result in [{},{'outcome':None,'retryable':False},{'outcome':'submitted','retryable':False},{'outcome':'submitted','retryable':False,'provider_id':'ok','error_code':'PRIVATE'},{'outcome':'unknown','retryable':False,'error_code':'recipient@example.invalid'}]:fails(rpc('jana_notification_finish',j['id'],j['lease_id'],result),'notification_result_invalid')
val(finish(j));passed('invalid results and private free-text errors cannot enter the delivery audit')
f=setup();r=run('BEGIN;'+enqueue(f,'rolled-back-event')+'ROLLBACK;');assert r['ok'];assert val("SELECT count(*) FROM notifications WHERE dedupe_key='adapter:'||encode(digest(jsonb_build_array('rolled-back-event',"+literal(f['p']+'u')+")::text,'sha256'),'hex');")==0;passed('outer business transaction rollback also removes queued channel jobs')
overview=val(rpc('jana_notification_overview',f['atok']));assert len(overview['items'])<=50;assert all(not {'recipient','title','body','user_id','lease_id'}&set(x) for x in overview['items']);fails(rpc('jana_notification_overview',f['t']),'forbidden');run("UPDATE users SET role='support' WHERE id="+literal(f['p']+'a')+';');assert val(rpc('jana_notification_overview',f['atok']))['channels'];passed('support sees bounded operational states without recipient content or worker leases')
assert val("SELECT count(*) FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'jana_notification_%' AND (has_function_privilege('anon',oid,'EXECUTE') OR has_function_privilege('authenticated',oid,'EXECUTE'));")==0;assert val('SELECT jana_deep_health();')['ok'];reset();passed('worker functions remain service-only and commerce invariants unchanged')
print(json.dumps({'passed':len(checks),'scope':'notification outbox'}))
