from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r

def write(f,key,op,payload,token=None):return rpc('jana_staff_write',token or f['atok'],key,op,payload)
def create(f,key,role='picker'):
 return write(f,key,'staff.create',{'email':key+'-'+f['p']+'@example.invalid','name':'Disposable staff','password':'Fixture-only-password-12!','role':role})
def change(f,uid,key,changes,token=None):return write(f,key,'staff.update',{'user_id':uid,'changes':changes,'reason':'Disposable documented staff change'},token)
def assign(f,oid,key,values):return write(f,key,'order.assign',{'order_id':oid,'assignments':values,'reason':'Disposable staff assignment'})
def token(uid):
 t=secrets.token_hex(32);run("INSERT INTO sessions(token_hash,user_id,csrf_hash,expires_at,created_at) VALUES(encode(extensions.digest("+literal(t)+",'sha256'),'hex'),"+literal(uid)+",'unused',(extract(epoch from clock_timestamp())*1000)::bigint+300000,0);");return t

def order(f):
 q=val(quote(f,'staff-quote'));return val(rpc('jana_critical_write',f['t'],'staff-confirm','order.confirm',{'quote_id':q['id']}))
f=fixture();rows=successful(race([create(f,'staff-concurrent')]*8));assert len(rows)==8 and all(r==rows[0] for r in rows);s=rows[0];assert set(s)=={'id','name','email','phone','role','active','created_at'};assert val("SELECT count(*) FROM audit_log WHERE action='staff_created' AND entity_id="+literal(s['id'])+';')==1;passed('eight creation retries create one sanitized staff account and one audit event')
fails(write(f,'staff-concurrent','staff.create',{'email':'changed@example.invalid'}),'idempotency_conflict');fails(write(f,'customer-creates-staff','staff.create',{},f['t']),'forbidden');fails(rpc('jana_list_staff',f['ct']),'forbidden');passed('staff management enforces admin role before returning idempotent results')
for password in ['short','ع'*40,None]:fails(write(f,'weak-staff-'+str(len(str(password))),'staff.create',{'email':'invalid-'+f['p']+'@example.invalid','name':'Invalid fixture','password':password,'role':'inventory'}),'weak_password')
fails(create(f,'invalid-role','customer'),'invalid_role');passed('password character and bcrypt byte limits and operational roles are validated')
st=token(s['id']);r=val(change(f,s['id'],'staff-contact',{'name':'Warehouse colleague','phone':'0500000000','role':'inventory'}));assert r['role']=='inventory';fails(rpc('jana_me',st),'unauthorized');assert val("SELECT to_jsonb(password_hash LIKE '$2a$12$%') FROM users WHERE id="+literal(s['id'])+';');passed('role changes revoke existing sessions and retain a properly hashed password')
fails(change(f,s['id'],'invalid-phone',{'phone':'123'}),'staff_validation');fails(change(f,f['p']+'u','customer-target',{'role':'admin'}),'staff_not_found');fails(change(f,s['id'],'invalid-active',{'active':'false'}),'staff_validation');passed('staff updates cannot edit customer membership or accept malformed contact and active values')
# Assigned work prevents role removal; reassignment retains order event history.
picker=val(create(f,'assigned-picker'));pt=token(picker['id']);o=order(f);rows=successful(race([assign(f,o['id'],'same-assignment',{'picker_id':picker['id']})]*8));assert len(rows)==8;fails(change(f,picker['id'],'disable-assigned',{'active':False}),'staff_has_active_orders');fails(rpc('jana_ops_transition',f['ct'],o['id'],'start',''),'invalid_transition');val(rpc('jana_ops_transition',pt,o['id'],'start',''));passed('assignment is idempotent and active picker work blocks deactivation')
other=val(create(f,'replacement-picker'));val(assign(f,o['id'],'reassign-picker',{'picker_id':other['id']}));val(change(f,picker['id'],'disable-reassigned',{'active':False}));assert val("SELECT count(*) FROM order_events WHERE order_id="+literal(o['id'])+" AND event='staff_assigned';")==2;passed('reassignment releases former staff while preserving assignment history')
val(rpc('jana_finalize_picking',f['atok'],o['id']));fails(rpc('jana_ops_transition',f['atok'],o['id'],'dispatch',''),'courier_assignment_invalid');val(assign(f,o['id'],'assign-courier',{'courier_id':f['p']+'c'}));fails(assign(f,o['id'],'wrong-courier-role',{'courier_id':s['id']}),'courier_assignment_invalid');val(rpc('jana_ops_transition',f['ct'],o['id'],'dispatch',''));fails(assign(f,o['id'],'moving-order',{'courier_id':f['p']+'d'}),'courier_assignment_invalid');passed('courier assignment requires active courier and cannot change during delivery')
val(rpc('jana_critical_write',f['ct'],'staff-delivery','order.deliver',{'order_id':o['id'],'code':o['delivery_code']}));fails(change(f,f['p']+'c','disable-uncollected',{'active':False}),'staff_has_uncollected_orders');val(rpc('jana_critical_write',f['ct'],'staff-collection','cod.collect',{'order_id':o['id'],'amount_halalas':2000}));fails(change(f,f['p']+'c','disable-cash',{'active':False}),'staff_has_cash_liability');val(rpc('jana_critical_write',f['atok'],'staff-settlement','cod.settle',{'order_id':o['id'],'reference':'Disposable actual staff deposit'}));val(change(f,f['p']+'c','disable-cleared-courier',{'active':False}));passed('delivered uncollected orders and cash liability both block courier deactivation until reconciled')
# Real multi-connection race: either claim wins and disable fails, or disable wins and claim fails.
for i in range(6):
 ff=fixture();p=val(create(ff,'race-picker'));t=token(p['id']);oo=order(ff);rows=race([rpc('jana_ops_transition',t,oo['id'],'start',''),change(ff,p['id'],'race-deactivation',{'active':False})]);assert len(successful(rows))==1,rows
 state=val("SELECT jsonb_build_object('active',u.active,'picker_id',o.picker_id) FROM users u CROSS JOIN orders o WHERE u.id="+literal(p['id'])+' AND o.id='+literal(oo['id'])+';');assert state['active'] or state['picker_id'] is None
passed('six concurrent picker claims and deactivations leave no order assigned to disabled staff')
# Open support tickets must also be reassigned before staff removal.
support=val(create(f,'support-assigned','support'));ticket=val(rpc('jana_ticket_write',f['t'],'staff-support-ticket','ticket.create',{'subject':'Fixture support assignment','message':'Disposable support assignment test','category':'other'}));val(rpc('jana_ticket_write',f['atok'],'assign-support-ticket','ticket.update',{'ticket_id':ticket['id'],'assigned_to':support['id']}));fails(change(f,support['id'],'disable-support',{'active':False}),'staff_has_open_tickets');passed('open support assignments prevent stranded tickets on disabled accounts')
# Last-admin test isolates membership inside this disposable database, then restores fixture admins.
active=val("SELECT jsonb_agg(id) FROM users WHERE active AND role='admin';");a=fixture();b=fixture();run("UPDATE users SET active=false WHERE role='admin' AND id NOT IN ("+literal(a['p']+'a')+','+literal(b['p']+'a')+');');rows=race([change(a,a['p']+'a','self-disable-admin-a',{'active':False}),change(b,b['p']+'a','self-disable-admin-b',{'active':False})]);assert len(successful(rows))==1,rows;assert val("SELECT count(*) FROM users WHERE active AND role='admin';")==1;assert any('last_active_admin' in r['error'] for r in rows);run('UPDATE users SET active=true WHERE id IN ('+','.join(map(literal,active))+');');passed('two administrators cannot concurrently disable the final active administrator')
# Audit cursor includes tie-breaker and recursively excludes credential fields.
run("INSERT INTO audit_log(id,actor_id,action,entity_id,detail,created_at) SELECT 'aud-'||replace(gen_random_uuid()::text,'-',''),"+literal(f['p']+'a')+",'staff_page_fixture','fixture',jsonb_build_object('after',jsonb_build_object('password_hash','must not return','safe','kept'),'tokens',jsonb_build_array(jsonb_build_object('access_token','must not return'))),4102444800000 FROM generate_series(1,60);")
page=val("SELECT jana_audit_page("+literal(f['atok'])+",NULL,NULL,'staff_page_fixture');");assert len(page['items'])==50 and 'must not return' not in json.dumps(page);cursor=page['next'];nextpage=val(rpc('jana_audit_page',f['atok'],cursor['before_at'],cursor['before_id'],'staff_page_fixture'));assert len(nextpage['items'])==10 and not nextpage['next'];assert not {x['id'] for x in page['items']} & {x['id'] for x in nextpage['items']};fails(rpc('jana_audit_page',f['t']),'forbidden');passed('keyset audit pagination preserves equal-timestamp records and recursively excludes credentials')
assert val("SELECT count(*) FROM pg_proc p WHERE pronamespace='public'::regnamespace AND proname LIKE 'jana_%' AND (has_function_privilege('anon',p.oid,'EXECUTE') OR has_function_privilege('authenticated',p.oid,'EXECUTE'));")==0;assert not val("SELECT to_jsonb(has_function_privilege('service_role','public.jana_ops_transition_finance_base(text,text,text,text)','EXECUTE')); ");assert val("SELECT count(*) FROM idempotency_records WHERE scope LIKE 'staff:%' AND response::text LIKE '%Fixture-only-password%';")==0;passed('staff RPC grants private transition helper and durable responses preserve security boundaries')
print(json.dumps({'passed':len(checks),'checks':checks}))
