from database_support import *
checks=[]
def passed(name):checks.append(name);print('PASS '+name,flush=True)
def fails(q,code):
 r=run(q,False);assert not r['ok'] and code in r['error'],r
f=fixture();foreign=fixture();support_id=val('SELECT to_jsonb((jana_auth_user('+literal(f['ct'])+')).id);')
run('UPDATE users SET role=\'support\' WHERE id='+literal(support_id)+';')
def write(token,key,op,payload):return rpc('jana_ticket_write',token,key,op,payload)
def mine(token=f['t']):return val(rpc('jana_my_tickets',token))
def staff():return val(rpc('jana_support_tickets',f['ct']))
def ticket(tid):return next(x for x in mine() if x['id']==tid)
payload={'subject':'مشكلة في التوصيل','message':'رسالة العميل الأولى','category':'delivery'}
results=successful(race([write(f['t'],'same-ticket-key','ticket.create',payload)]*8));assert len(results)==8 and all(x==results[0] for x in results);t=results[0];assert len([x for x in mine() if x['id']==t['id']])==1;passed('concurrent create retries yield one ticket and one initial message')
fails(write(f['t'],'same-ticket-key','ticket.create',{**payload,'message':'Different body'}),'idempotency_conflict');passed('same ticket key with changed request is rejected')
for invalid in [dict(subject=None,message='message'),dict(subject='Subject',message=None),dict(subject='Subject',message=''),dict(subject='Subject',message='ok',category='invalid')]:fails(write(f['t'],str(uuid.uuid4()),'ticket.create',invalid),'invalid_ticket')
fails(write(f['t'],'foreign-order-key','ticket.create',{**payload,'order_id':'not-owned-order'}),'order_not_found');passed('required content category and order ownership are validated')
q=val(quote(f,'support-order-quote'));o=val(rpc('jana_critical_write',f['t'],'support-order-confirm','order.confirm',{'quote_id':q['id']}));linked=val(write(f['t'],'linked-ticket-key','ticket.create',{**payload,'order_id':o['id']}));assert ticket(linked['id'])['order_id']==o['id'];fails(write(foreign['t'],'foreign-owner-key','ticket.create',{**payload,'order_id':o['id']}),'order_not_found');passed('ticket can link to its customers order only')
val(write(f['ct'],'staff-first-reply','ticket.update',{'ticket_id':t['id'],'message':'يرجى تأكيد الموقع','state':'pending_customer','priority':'high','assigned_to':support_id}));r=ticket(t['id']);assert r['state']=='pending_customer' and r['messages'][-1]['text']=='يرجى تأكيد الموقع' and r['messages'][-1]['actor']=='support';assert next(x for x in staff() if x['id']==t['id'])['assigned_to']==support_id;passed('support replies assigns priority and waits for customer')
fail_count=val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(t['id'])+';');fails(write(f['ct'],'bad-assignment-key','ticket.update',{'ticket_id':t['id'],'assigned_to':f['p']+'u'}),'invalid_support_assignee');assert val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(t['id'])+';')==fail_count;passed('assignment to non-support account rolls back without a false audit event')
fails(write(foreign['t'],'not-owner-reply','ticket.reply',{'ticket_id':t['id'],'message':'not mine'}),'ticket_not_found');fails(write(f['t'],'not-staff-update','ticket.update',{'ticket_id':t['id'],'state':'closed'}),'forbidden');fails(rpc('jana_support_tickets',f['t']),'forbidden');passed('customers cannot read staff views update ticket state or reply to another customer')
replies=successful(race([write(f['t'],'duplicate-reply-key','ticket.reply',{'ticket_id':t['id'],'message':'موقعي محدث'})]*8));assert len(replies)==8;assert len(ticket(t['id'])['messages'])==3 and ticket(t['id'])['state']=='open';passed('customer reply reopens ticket and retries append once')
val(write(f['ct'],'close-ticket-key','ticket.update',{'ticket_id':t['id'],'state':'closed'}));before=ticket(t['id']);assert len(before['messages'])==3;val(write(f['t'],'reopen-ticket-key','ticket.reply',{'ticket_id':t['id'],'message':'أحتاج مساعدة إضافية'}));assert ticket(t['id'])['state']=='open';passed('closing adds no empty message and customer can reopen with a reply')
res=successful(race([write(f['ct'],'concurrent-staff-key','ticket.update',{'ticket_id':t['id'],'message':'رد الدعم المتزامن'}),write(f['t'],'concurrent-customer-key','ticket.reply',{'ticket_id':t['id'],'message':'رد العميل المتزامن'})]));assert len(res)==2;messages=ticket(t['id'])['messages'];assert len(messages)==6 and {m['text'] for m in messages[-2:]}=={'رد الدعم المتزامن','رد العميل المتزامن'};passed('concurrent customer and staff responses retain both messages')
val(write(f['ct'],'unassign-ticket-key','ticket.update',{'ticket_id':t['id'],'assigned_to':None}));assert next(x for x in staff() if x['id']==t['id'])['assigned_to'] is None;passed('authorized staff can explicitly unassign a ticket')
fails('UPDATE tickets SET messages=\'[]\'::json WHERE id='+literal(t['id'])+';','immutable_ticket_history');fails('DELETE FROM tickets WHERE id='+literal(t['id'])+';','immutable_ticket_history');assert val('SELECT count(*) FROM audit_log WHERE entity_id='+literal(t['id'])+';')>=7;passed('conversation history and operational changes retain audit evidence')
legacy=val("SELECT jana_ticket_messages('[{\"by\":\"support\",\"message\":\"Old reply\",\"at\":1},{\"actor\":\"customer\",\"text\":\"New reply\",\"at\":2}]'::jsonb);");assert [x['text'] for x in legacy]==['Old reply','New reply'];assert legacy[0]['actor']=='support';passed('legacy message formats remain readable without rewriting history')
val(rpc('jana_customer_ticket_reply',f['t'],t['id'],'Legacy client reply'));val(rpc('jana_support_reply',f['ct'],t['id'],'Legacy staff reply','pending_customer','normal'));assert ticket(t['id'])['state']=='pending_customer';assert len(ticket(t['id'])['messages'])==8;passed('legacy trusted RPCs use the repaired message and state workflow')
assert val("SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('jana_ticket_write','jana_support_roster','jana_my_tickets','jana_support_tickets','jana_ticket_messages') AND (has_function_privilege('anon',p.oid,'EXECUTE') OR has_function_privilege('authenticated',p.oid,'EXECUTE')); ")==0;roster=val(rpc('jana_support_roster',f['ct']));assert all(set(x)=={'id','name','role'} for x in roster);passed('support RPC grants and minimal staff roster remain restricted')
print(json.dumps({'passed':len(checks),'checks':checks}))
