import { guard, safeCookies, rpcBusinessResult, requiredIdempotency, quoteRpcInput, couponFeature } from "./http.ts";
const SB = Deno.env.get('SUPABASE_URL')!;
const KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const baseHeaders = {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'same-origin'};
function json(data:any,status=200,extra:any={}){const {__cookies=[],...rest}=extra;const headers=new Headers({...baseHeaders,...rest});for(const cookie of __cookies)headers.append('set-cookie',cookie);return new Response(JSON.stringify(data),{status,headers})}
function cookies(req:Request){return safeCookies(req)}
function session(req:Request){const a=req.headers.get('authorization')||'';if(a.startsWith('Bearer '))return a.slice(7).trim();return cookies(req).jana_session||''}
function usingCookie(req:Request){return !((req.headers.get('authorization')||'').startsWith('Bearer ')) && !!cookies(req).jana_session}
function requireCsrf(req:Request){if(!usingCookie(req))return;const c=cookies(req).jana_csrf||'',h=req.headers.get('x-csrf-token')||'';if(!c||!h||c!==h)throw Object.assign(new Error('csrf_required'),{status:403})}
function setSessionHeaders(token:string,csrf:string){return {__cookies:[`jana_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`,`jana_csrf=${encodeURIComponent(csrf)}; Path=/; Secure; SameSite=Strict; Max-Age=2592000`]}}
function clearSessionHeaders(){return {__cookies:['jana_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0','jana_csrf=; Path=/; Secure; SameSite=Strict; Max-Age=0']}}
async function sb(path:string,init:RequestInit={}){const h=new Headers(init.headers||{});h.set('apikey',KEY);h.set('authorization',`Bearer ${KEY}`);if(init.body&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(`${SB}${path}`,{...init,headers:h});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok){const e:any=new Error(data?.message||data?.error||'database_error');e.status=r.status;e.details=data;throw e}return rpcBusinessResult(data)}
async function rpc(name:string,args:Record<string,any>={}){return sb(`/rest/v1/rpc/${name}`,{method:'POST',body:JSON.stringify(args)})}
async function body(req:Request){if(!req.body)return {};try{return await req.json()}catch{throw Object.assign(new Error('invalid_json'),{status:422})}}
async function currentUser(token:string){if(!token)throw Object.assign(new Error('auth_required'),{status:401});return rpc('jana_me',{p_token:token})}
async function role(token:string,roles:string[]){const u=await currentUser(token);if(!roles.includes(u.role))throw Object.assign(new Error('forbidden'),{status:403});return u}
function page(items:any[],u:URL){const offset=Math.max(0,Number(u.searchParams.get('offset')||0)||0),limit=Math.min(100,Math.max(1,Number(u.searchParams.get('limit')||50)||50));return {items:items.slice(offset,offset+limit),next_offset:offset+limit<items.length?offset+limit:null}}
function errPayload(e:any){const raw=String(e?.message||'internal');const map:Record<string,[number,string,string]>={feature_unavailable:[409,'FEATURE_UNAVAILABLE','القسائم غير متاحة لهذا الحساب حاليًا'],invalid_cart:[422,'INVALID_CART','راجع الأصناف والكميات'],invalid_coupon:[422,'INVALID_COUPON','رمز القسيمة غير صحيح'],coupon_unavailable:[409,'COUPON_UNAVAILABLE','القسيمة غير متاحة'],coupon_expired:[409,'COUPON_EXPIRED','انتهت صلاحية القسيمة'],coupon_exhausted:[409,'COUPON_EXHAUSTED','اكتمل الحد المسموح لاستخدام القسيمة'],coupon_minimum:[409,'COUPON_MINIMUM','الطلب أقل من الحد الأدنى للقسيمة'],invalid_delivery_code:[409,'INVALID_DELIVERY_CODE','رمز التسليم غير صحيح'],delivery_code_locked:[429,'DELIVERY_CODE_LOCKED','تجاوزت محاولات رمز التسليم المسموح بها'],invalid_idempotency_key:[422,'IDEMPOTENCY_REQUIRED','مفتاح منع التكرار مطلوب'],idempotency_conflict:[409,'IDEMPOTENCY_CONFLICT','مفتاح إعادة المحاولة استُخدم لطلب مختلف'],unauthorized:[401,'AUTH_REQUIRED','سجّل الدخول للمتابعة'],auth_required:[401,'AUTH_REQUIRED','سجّل الدخول للمتابعة'],invalid_credentials:[401,'INVALID_LOGIN','بيانات الدخول غير صحيحة'],too_many_attempts:[429,'RATE_LIMIT','محاولات كثيرة. حاول لاحقًا'],email_exists:[409,'ACCOUNT_EXISTS','البريد مستخدم. سجّل الدخول'],invalid_email:[422,'VALIDATION','البريد الإلكتروني غير صحيح'],weak_password:[422,'VALIDATION','كلمة المرور لا تحقق الحد الأدنى'],invalid_name:[422,'VALIDATION','راجع الاسم'],csrf_required:[403,'CSRF','أعد تحميل الصفحة ثم حاول مجددًا'],forbidden:[403,'FORBIDDEN','ليس لديك صلاحية لهذا الإجراء'],invalid_address:[404,'ADDRESS_NOT_FOUND','العنوان غير موجود'],outside_zone:[409,'OUTSIDE_COVERAGE','العنوان خارج نطاق التغطية'],slot_unavailable:[409,'SLOT_UNAVAILABLE','الموعد لم يعد متاحًا'],insufficient_stock:[409,'OUT_OF_STOCK','الكمية لم تعد متوفرة'],insufficient_lot_stock:[409,'OUT_OF_STOCK','الكمية لم تعد متوفرة'],below_minimum:[409,'BELOW_MINIMUM','الطلب أقل من الحد الأدنى للتوصيل'],quote_expired:[409,'QUOTE_EXPIRED','انتهى حجز السعر والمخزون'],quote_not_found:[404,'QUOTE_NOT_FOUND','عرض السعر غير موجود'],order_not_found:[404,'ORDER_NOT_FOUND','الطلب غير موجود'],not_delivered:[409,'ORDER_NOT_DELIVERED','الطلب لم يُسلّم بعد'],refund_amount_invalid:[409,'REFUND_AMOUNT','مبلغ الاسترداد يتجاوز المتاح'],phone_not_configured:[503,'NOT_CONFIGURED','خدمة الرسائل غير مفعلة حاليًا']};for(const [k,v] of Object.entries(map))if(raw.toLowerCase().includes(k))return {status:v[0],data:{error:{code:v[1],message:v[2]}}};return {status:e?.status&&e.status<500?e.status:500,data:{error:{code:'INTERNAL',message:'تعذر إكمال العملية بأمان'}}}}
async function tableGet(table:string,query:string){return sb(`/rest/v1/${table}?${query}`,{headers:{prefer:'count=none'}})}

Deno.serve(guard(async(req:Request)=>{const requestId=crypto.randomUUID();try{
 const url=new URL(req.url);const marker='/jana-api';const i=url.pathname.indexOf(marker);let p=i>=0?url.pathname.slice(i+marker.length):url.pathname;if(!p)p='/';const m=req.method.toUpperCase();const token=session(req);const isMutation=!['GET','HEAD','OPTIONS'].includes(m);
 if(p==='/health'&&m==='GET'){const h=await rpc('jana_deep_health');return json({...h,service:'jana-api',version:10,integrations:{sms:'not_configured',payment:'cod_only',storage:'database_only'}},200,{'x-request-id':requestId})}
 if(p==='/api/features'&&m==='GET')return json({coupons:await couponFeature(token)},200,{'x-request-id':requestId});
 if(p==='/api/config'&&m==='GET'){const rows=await tableGet('settings','key=eq.public&select=value');return json({brand:'جَنى',currency:'SAR',timezone:'Asia/Riyadh',demo:true,sms_configured:false,payment_methods:['cod'],sales_modes:['individual','basket','sized','custom','usage','bulk','recurring','gift'],policies:rows?.[0]?.value||{},weight_policy:'سعر العرض حد أعلى. نقص الوزن الفردي يخفض المبلغ نسبيًا؛ الزيادة حتى 10% مجانية. السلة الناقصة تتطلب موافقة على بديل أو تزال كاملة.'},200,{'x-request-id':requestId})}
 if(p==='/api/catalog'&&m==='GET'){let items=await rpc('jana_public_catalog');const q=(url.searchParams.get('q')||'').trim(),cat=url.searchParams.get('category')||'';if(q)items=items.filter((x:any)=>String(x.name||'').includes(q));if(cat)items=items.filter((x:any)=>x.category===cat);return json(page(items,url),200,{'x-request-id':requestId})}
 if(p==='/api/reviews'&&m==='GET'){const rows=await tableGet('reviews','select=rating,comment,created_at&order=created_at.desc&limit=100');return json(page((rows||[]).map((x:any)=>({...x,verified_purchase:true})),url),200,{'x-request-id':requestId})}
 if(p==='/api/coverage-zones'&&m==='GET'){const rows=await tableGet('delivery_zones','active=eq.true&select=id,name,polygon,fee_halalas,minimum_halalas,active&order=name');return json({items:rows||[]},200,{'x-request-id':requestId})}

 if(p==='/api/auth/register'&&m==='POST'){const b=await body(req);const r=await rpc('jana_register',{p_email:b.email,p_name:b.name,p_password:b.password,p_phone:b.phone||null});await rpc('jana_logout',{p_token:r.token}).catch(()=>{});return json({user:r.user},201,{'x-request-id':requestId})}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(req);const r=await rpc('jana_login',{p_email:b.email,p_password:b.password});if(b.mode==='mobile')return json({user:r.user,access_token:r.token,expires_in:2592000},200,{'x-request-id':requestId});return json({user:r.user,csrf_token:r.csrf},200,{...setSessionHeaders(r.token,r.csrf),'x-request-id':requestId})}
 if(p==='/api/auth/me'&&m==='GET'){const u=await currentUser(token);return json({user:u},200,{'x-request-id':requestId})}
 if(p==='/api/auth/logout'&&m==='POST'){if(token){requireCsrf(req);await rpc('jana_logout',{p_token:token}).catch(()=>{})}return json({ok:true},200,{...clearSessionHeaders(),'x-request-id':requestId})}
 if(p==='/api/auth/password'&&m==='POST'){requireCsrf(req);const b=await body(req);await rpc('jana_change_password',{p_token:token,p_current:b.current_password,p_new:b.new_password});return json({ok:true,sign_in_again:true},200,{...clearSessionHeaders(),'x-request-id':requestId})}
 if((p==='/api/auth/phone/start'||p==='/api/auth/phone/verify')&&m==='POST')return json({error:{code:'NOT_CONFIGURED',message:'خدمة الرسائل غير مفعلة حاليًا'}},503,{'x-request-id':requestId});
 if(p==='/api/auth/account'&&m==='DELETE'){requireCsrf(req);const r=await rpc('jana_anonymize_account',{p_token:token});return json(r,200,{...clearSessionHeaders(),'x-request-id':requestId})}

 if(p==='/api/addresses'&&m==='GET'){const r=await rpc('jana_list_addresses',{p_token:token});return json({items:r},200,{'x-request-id':requestId})}
 if(p==='/api/addresses'&&m==='POST'){requireCsrf(req);const b=await body(req);const r=await rpc('jana_add_address',{p_token:token,p_label:b.label,p_details:b.details,p_latitude:String(b.latitude),p_longitude:String(b.longitude),p_recipient_name:b.recipient_name,p_recipient_phone:b.recipient_phone,p_default:Boolean(b.is_default)});return json(r,201,{'x-request-id':requestId})}
 let mm=p.match(/^\/api\/addresses\/([^/]+)$/);if(mm&&m==='PATCH'){requireCsrf(req);const b=await body(req);const all=await rpc('jana_list_addresses',{p_token:token});const a=all.find((x:any)=>x.id===mm[1]);if(!a)throw Object.assign(new Error('invalid_address'),{status:404});const r=await rpc('jana_update_address',{p_token:token,p_address_id:mm[1],p_label:b.label??a.label,p_details:b.details??a.details,p_latitude:String(b.latitude??a.latitude),p_longitude:String(b.longitude??a.longitude),p_recipient_name:b.recipient_name??a.recipient_name,p_recipient_phone:b.recipient_phone??a.recipient_phone,p_default:Boolean(b.is_default??a.is_default)});return json(r,200,{'x-request-id':requestId})}
 if(mm&&m==='DELETE'){requireCsrf(req);const r=await rpc('jana_delete_address',{p_token:token,p_address_id:mm[1]});return json(r,200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/addresses\/([^/]+)\/default$/);if(mm&&m==='PATCH'){requireCsrf(req);const all=await rpc('jana_list_addresses',{p_token:token});const a=all.find((x:any)=>x.id===mm[1]);if(!a)throw Object.assign(new Error('invalid_address'),{status:404});const r=await rpc('jana_update_address',{p_token:token,p_address_id:mm[1],p_label:a.label,p_details:a.details,p_latitude:String(a.latitude),p_longitude:String(a.longitude),p_recipient_name:a.recipient_name,p_recipient_phone:a.recipient_phone,p_default:true});return json(r,200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/coverage\/([^/]+)$/);if(mm&&m==='GET'){const r=await rpc('jana_customer_coverage',{p_token:token,p_address_id:mm[1]});return json(r,200,{'x-request-id':requestId})}

 if(p==='/api/favorites'&&m==='GET'){const fav=await rpc('jana_my_favorites',{p_token:token}),cat=await rpc('jana_public_catalog');const by=new Map(cat.map((x:any)=>[x.family_id,x]));return json({items:fav.map((f:any)=>({offering_family_id:f.family_id,created_at:f.created_at,offering:by.get(f.family_id)||null})).filter((x:any)=>x.offering)},200,{'x-request-id':requestId})}
 if(p==='/api/favorites'&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_set_favorite',{p_token:token,p_family_id:b.offering_family_id,p_present:true}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/favorites\/([^/]+)$/);if(mm&&m==='DELETE'){requireCsrf(req);return json(await rpc('jana_set_favorite',{p_token:token,p_family_id:mm[1],p_present:false}),200,{'x-request-id':requestId})}

 if(p==='/api/shopping-lists'&&m==='GET')return json({items:await rpc('jana_shopping_lists',{p_token:token})},200,{'x-request-id':requestId});
 if(p==='/api/shopping-lists'&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_create_shopping_list',{p_token:token,p_name:b.name,p_items:b.items}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/shopping-lists\/([^/]+)$/);if(mm&&m==='DELETE'){requireCsrf(req);return json(await rpc('jana_delete_shopping_list',{p_token:token,p_list_id:mm[1]}),200,{'x-request-id':requestId})}

 if(p==='/api/recurring'&&m==='GET')return json({items:await rpc('jana_recurring_list',{p_token:token})},200,{'x-request-id':requestId});
 if(p==='/api/recurring'&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_recurring_create',{p_token:token,p_address_id:b.address_id,p_cart:b.lines,p_interval_days:Number(b.interval_days),p_next_at:Number(b.next_at)*1000}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/recurring\/([^/]+)$/);if(mm&&m==='PATCH'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_recurring_update',{p_token:token,p_plan_id:mm[1],p_state:b.state}),200,{'x-request-id':requestId})}

 if(p==='/api/quotes'&&m==='POST'){requireCsrf(req);const b=await body(req);const idem=requiredIdempotency(req);const call=await quoteRpcInput(b,token,idem);return json(await rpc(call.name,call.args),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/quotes\/([^/]+)$/);if(mm&&m==='GET')return json(await rpc('jana_quote_detail',{p_token:token,p_quote_id:mm[1]}),200,{'x-request-id':requestId});
 if(mm&&m==='DELETE'){requireCsrf(req);return json(await rpc('jana_cancel_quote',{p_token:token,p_quote_id:mm[1]}),200,{'x-request-id':requestId})}

 if(p==='/api/orders'&&m==='GET'){const r=await rpc('jana_my_orders',{p_token:token});return json(page(r,url),200,{'x-request-id':requestId})}
 if(p==='/api/orders'&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_critical_write',{p_token:token,p_key:requiredIdempotency(req),p_operation:'order.confirm',p_payload:{quote_id:b.quote_id}}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)$/);if(mm&&m==='GET'){const d=await rpc('jana_order_detail',{p_token:token,p_order_id:mm[1]});d.substitutions=await rpc('jana_my_substitutions',{p_token:token,p_order_id:mm[1]});const refs=await tableGet('refunds',`order_id=eq.${encodeURIComponent(mm[1])}&select=id,component_id,amount_halalas,reason,state,created_at&order=created_at.desc`);d.refunds=refs||[];const rev=await tableGet('reviews',`order_id=eq.${encodeURIComponent(mm[1])}&select=rating,comment,created_at&limit=1`);d.review=rev?.[0]||null;return json(d,200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)\/cancel$/);if(mm&&m==='POST'){requireCsrf(req);return json(await rpc('jana_cancel_order',{p_token:token,p_order_id:mm[1]}),200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)\/delivery-code$/);if(mm&&m==='POST'){requireCsrf(req);return json(await rpc('jana_rotate_delivery_code',{p_token:token,p_order_id:mm[1]}),200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)\/refunds$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_request_refund',{p_token:token,p_order_id:mm[1],p_component_id:b.component_id,p_amount_halalas:Number(b.amount_halalas),p_reason:b.reason}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)\/review$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_review_order',{p_token:token,p_order_id:mm[1],p_rating:Number(b.rating),p_comment:b.comment}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/orders\/([^/]+)\/tracking$/);if(mm&&m==='GET')return json(await rpc('jana_customer_tracking',{p_token:token,p_order_id:mm[1]}),200,{'x-request-id':requestId});

 mm=p.match(/^\/api\/substitutions\/([^/]+)\/decision$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_decide_substitution',{p_token:token,p_substitution_id:mm[1],p_accept:Boolean(b.accept)}),200,{'x-request-id':requestId})}
 if(p==='/api/notifications'&&m==='GET')return json({items:await rpc('jana_customer_notifications',{p_token:token})},200,{'x-request-id':requestId});
 mm=p.match(/^\/api\/notifications\/([^/]+)\/read$/);if(mm&&m==='POST'){requireCsrf(req);return json(await rpc('jana_mark_notification_read',{p_token:token,p_notification_id:mm[1]}),200,{'x-request-id':requestId})}
 if(p==='/api/tickets'&&m==='GET')return json({items:await rpc('jana_my_tickets',{p_token:token})},200,{'x-request-id':requestId});
 if(p==='/api/tickets'&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_create_ticket',{p_token:token,p_order_id:b.order_id||null,p_subject:b.subject,p_message:b.message}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/tickets\/([^/]+)\/reply$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_customer_ticket_reply',{p_token:token,p_ticket_id:mm[1],p_message:b.message}),200,{'x-request-id':requestId})}

 if(p==='/api/ops/orders'&&m==='GET'){const u=await currentUser(token);if(!['admin','picker','courier','inventory','finance','support'].includes(u.role))throw Object.assign(new Error('forbidden'),{status:403});const r=u.role==='admin'||u.role==='finance'||u.role==='support'?await rpc('jana_admin_orders',{p_token:token}):await rpc('jana_ops_orders',{p_token:token,p_role:u.role});return json(page(r,url),200,{'x-request-id':requestId})}
 if(p==='/api/ops/reports'&&m==='GET'){await role(token,['admin','finance']);return json(await rpc('jana_admin_reports',{p_token:token}),200,{'x-request-id':requestId})}
 if(p==='/api/ops/staff'&&m==='POST'){requireCsrf(req);await role(token,['admin']);const b=await body(req);return json(await rpc('jana_create_staff',{p_token:token,p_email:b.email,p_name:b.name,p_password:b.password,p_role:b.role}),201,{'x-request-id':requestId})}
 if(p==='/api/ops/staff'&&m==='GET'){await role(token,['admin']);const rows=await tableGet('users',`role=neq.customer&select=id,email,name,role,active,created_at&order=created_at.desc`);return json({items:rows||[]},200,{'x-request-id':requestId})}
 if(p==='/api/ops/support'&&m==='GET'){await role(token,['admin','support']);return json({items:await rpc('jana_support_tickets',{p_token:token})},200,{'x-request-id':requestId})}
 if(p==='/api/ops/deep-health'&&m==='GET'){await role(token,['admin']);return json(await rpc('jana_admin_deep_health',{p_token:token}),200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/ops\/orders\/([^/]+)\/(claim|start|ready|dispatch|deliver|fail)$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);const action=mm[2];return json(action==='deliver'?await rpc('jana_critical_write',{p_token:token,p_key:requiredIdempotency(req),p_operation:'order.deliver',p_payload:{order_id:mm[1],code:b.code}}):await rpc('jana_ops_transition',{p_token:token,p_order_id:mm[1],p_action:action,p_code:action==='fail'?(b.reason||b.code||null):(b.code||null)}),200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/ops\/orders\/([^/]+)\/actual$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_picker_record_actual',{p_token:token,p_order_id:mm[1],p_line_id:b.line_id,p_actual_base:Number(b.actual_base)}),200,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/ops\/orders\/([^/]+)\/substitution$/);if(mm&&m==='POST'){requireCsrf(req);const b=await body(req);return json(await rpc('jana_propose_substitution',{p_token:token,p_order_id:mm[1],p_line_id:b.line_id,p_offering_id:b.offering_id,p_qty:Number(b.qty)}),201,{'x-request-id':requestId})}
 mm=p.match(/^\/api\/ops\/orders\/([^/]+)\/finalize$/);if(mm&&m==='POST'){requireCsrf(req);return json(await rpc('jana_finalize_picking',{p_token:token,p_order_id:mm[1]}),200,{'x-request-id':requestId})}

 return json({error:{code:'NOT_FOUND',message:'المسار غير موجود'}},404,{'x-request-id':requestId});
}catch(e){console.error('jana_api_error',requestId,String((e as any)?.message||e));const o=errPayload(e);return json(o.data,o.status,{'x-request-id':requestId})}}));
