-- JANA 0.1.0 initial PostgreSQL schema. Money = integer halalas; dates = epoch seconds.

CREATE TABLE coupons (
 id VARCHAR(36) NOT NULL,
 code VARCHAR(30) NOT NULL,
 amount_halalas BIGINT NOT NULL,
 minimum_halalas BIGINT NOT NULL,
 max_uses INTEGER NOT NULL,
 reserved INTEGER NOT NULL,
 redeemed INTEGER NOT NULL,
 expires_at BIGINT NOT NULL,
 active BOOLEAN NOT NULL,
 PRIMARY KEY (id),
 CONSTRAINT coupon_amount CHECK (amount_halalas > 0 AND minimum_halalas >= 0),
 CONSTRAINT coupon_cap CHECK (reserved >= 0 AND redeemed >= 0 AND reserved + redeemed <= max_uses),
 UNIQUE (code)
);
CREATE TABLE delivery_zones (id VARCHAR(36) NOT NULL,name VARCHAR(100) NOT NULL,polygon JSON NOT NULL,fee_halalas BIGINT NOT NULL,minimum_halalas BIGINT NOT NULL,active BOOLEAN NOT NULL,PRIMARY KEY (id),CONSTRAINT zone_amounts CHECK (fee_halalas >= 0 AND minimum_halalas >= 0));
CREATE TABLE offerings (id VARCHAR(36) NOT NULL,family_id VARCHAR(36) NOT NULL,version INTEGER NOT NULL,kind VARCHAR(20) NOT NULL,name VARCHAR(140) NOT NULL,description TEXT NOT NULL,category VARCHAR(40) NOT NULL,size_label VARCHAR(40) NOT NULL,emoji VARCHAR(20) NOT NULL,image_url VARCHAR(300) NOT NULL,sale_unit VARCHAR(20) NOT NULL,price_halalas BIGINT NOT NULL,components JSON NOT NULL,active BOOLEAN NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT offering_version_unique UNIQUE (family_id, version),CONSTRAINT price_positive CHECK (price_halalas > 0 AND price_halalas <= 9000000000000),CONSTRAINT offering_kind CHECK (kind IN ('individual','basket','sized','usage','bulk','gift')));
CREATE TABLE provider_events (id VARCHAR(36) NOT NULL,provider VARCHAR(30) NOT NULL,provider_event_id VARCHAR(160) NOT NULL,payload_hash VARCHAR(64) NOT NULL,state VARCHAR(30) NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT provider_event_once UNIQUE (provider, provider_event_id));
CREATE TABLE rate_windows (key VARCHAR(80) NOT NULL,count INTEGER NOT NULL,expires_at BIGINT NOT NULL,PRIMARY KEY (key));
CREATE TABLE settings (key VARCHAR(80) NOT NULL,value JSON NOT NULL,PRIMARY KEY (key));
CREATE TABLE stock_items (id VARCHAR(36) NOT NULL,name VARCHAR(140) NOT NULL,base_unit VARCHAR(10) NOT NULL,active BOOLEAN NOT NULL,PRIMARY KEY (id),CONSTRAINT stock_base_unit CHECK (base_unit IN ('gram','piece')));
CREATE TABLE suppliers (id VARCHAR(36) NOT NULL,name VARCHAR(140) NOT NULL,phone VARCHAR(30) NOT NULL,active BOOLEAN NOT NULL,PRIMARY KEY (id));
CREATE TABLE users (id VARCHAR(36) NOT NULL,email VARCHAR(254) NOT NULL,phone VARCHAR(20),name VARCHAR(100) NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(24) NOT NULL,verified_phone BOOLEAN NOT NULL,active BOOLEAN NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT valid_role CHECK (role IN ('customer','admin','picker','courier','inventory','finance','support')),UNIQUE (email),UNIQUE (phone));
CREATE TABLE worker_runs (name VARCHAR(50) NOT NULL,last_success_at BIGINT NOT NULL,detail JSON NOT NULL,PRIMARY KEY (name));
CREATE TABLE addresses (id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,label VARCHAR(80) NOT NULL,details TEXT NOT NULL,latitude VARCHAR(30) NOT NULL,longitude VARCHAR(30) NOT NULL,recipient_name VARCHAR(100) NOT NULL,recipient_phone VARCHAR(20) NOT NULL,PRIMARY KEY (id),FOREIGN KEY(user_id) REFERENCES users (id));
CREATE TABLE audit_log (id VARCHAR(36) NOT NULL,actor_id VARCHAR(36),action VARCHAR(100) NOT NULL,entity_id VARCHAR(80) NOT NULL,detail JSON NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),FOREIGN KEY(actor_id) REFERENCES users (id));
CREATE TABLE delivery_slots (id VARCHAR(36) NOT NULL,zone_id VARCHAR(36) NOT NULL,starts_at BIGINT NOT NULL,ends_at BIGINT NOT NULL,cutoff_at BIGINT NOT NULL,capacity INTEGER NOT NULL,booked INTEGER NOT NULL,active BOOLEAN NOT NULL,PRIMARY KEY (id),CONSTRAINT slot_capacity CHECK (booked >= 0 AND booked <= capacity AND capacity > 0),CONSTRAINT slot_time_range CHECK (ends_at > starts_at AND cutoff_at <= starts_at),CONSTRAINT slot_zone_start_unique UNIQUE (zone_id, starts_at),FOREIGN KEY(zone_id) REFERENCES delivery_zones (id));
CREATE TABLE idempotency_records (scope VARCHAR(240) NOT NULL,user_id VARCHAR(36) NOT NULL,key VARCHAR(128) NOT NULL,request_hash VARCHAR(64) NOT NULL,response JSON NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (scope),FOREIGN KEY(user_id) REFERENCES users (id));
CREATE TABLE inventory_lots (id VARCHAR(36) NOT NULL,stock_id VARCHAR(36) NOT NULL,supplier_id VARCHAR(36),received_base BIGINT NOT NULL,on_hand_base BIGINT NOT NULL,reserved_base BIGINT NOT NULL,total_cost_halalas BIGINT,remaining_cost_halalas BIGINT,expires_at BIGINT NOT NULL,inspection_state VARCHAR(20) NOT NULL,received_by VARCHAR(36) NOT NULL,inspected_by VARCHAR(36),inspection_note TEXT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT lot_balance_valid CHECK (received_base > 0 AND on_hand_base >= 0 AND reserved_base >= 0 AND on_hand_base >= reserved_base),CONSTRAINT lot_cost_valid CHECK (total_cost_halalas IS NULL OR total_cost_halalas >= 0),CONSTRAINT lot_inspection_state CHECK (inspection_state IN ('pending','accepted','rejected')),FOREIGN KEY(stock_id) REFERENCES stock_items (id),FOREIGN KEY(supplier_id) REFERENCES suppliers (id),FOREIGN KEY(received_by) REFERENCES users (id),FOREIGN KEY(inspected_by) REFERENCES users (id));
CREATE TABLE sessions (token_hash VARCHAR(64) NOT NULL,user_id VARCHAR(36) NOT NULL,csrf_hash VARCHAR(64) NOT NULL,expires_at BIGINT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (token_hash),FOREIGN KEY(user_id) REFERENCES users (id));
CREATE TABLE stock_balances (stock_id VARCHAR(36) NOT NULL,on_hand_base BIGINT NOT NULL,reserved_base BIGINT NOT NULL,PRIMARY KEY (stock_id),CONSTRAINT no_negative_stock CHECK (on_hand_base >= 0 AND reserved_base >= 0 AND on_hand_base - reserved_base >= 0),FOREIGN KEY(stock_id) REFERENCES stock_items (id));
CREATE TABLE count_requests (id VARCHAR(36) NOT NULL,lot_id VARCHAR(36) NOT NULL,observed_base BIGINT NOT NULL,expected_base BIGINT NOT NULL,submitted_by VARCHAR(36) NOT NULL,approved_by VARCHAR(36),state VARCHAR(20) NOT NULL,reason TEXT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT count_nonnegative CHECK (observed_base >= 0 AND expected_base >= 0),FOREIGN KEY(lot_id) REFERENCES inventory_lots (id),FOREIGN KEY(submitted_by) REFERENCES users (id),FOREIGN KEY(approved_by) REFERENCES users (id));
CREATE TABLE quotes (id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,slot_id VARCHAR(36) NOT NULL,coupon_id VARCHAR(36),snapshot JSON NOT NULL,state VARCHAR(20) NOT NULL,expires_at BIGINT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT quote_state CHECK (state IN ('active','converted','expired','cancelled')),FOREIGN KEY(user_id) REFERENCES users (id),FOREIGN KEY(slot_id) REFERENCES delivery_slots (id),FOREIGN KEY(coupon_id) REFERENCES coupons (id));
CREATE TABLE recurring_plans (id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,address_id VARCHAR(36) NOT NULL,cart JSON NOT NULL,interval_days INTEGER NOT NULL,next_at BIGINT NOT NULL,state VARCHAR(24) NOT NULL,last_notice_at BIGINT,PRIMARY KEY (id),CONSTRAINT recurring_interval CHECK (interval_days BETWEEN 1 AND 90),FOREIGN KEY(user_id) REFERENCES users (id),FOREIGN KEY(address_id) REFERENCES addresses (id));
CREATE TABLE stock_movements (id VARCHAR(36) NOT NULL,stock_id VARCHAR(36) NOT NULL,lot_id VARCHAR(36),on_hand_delta BIGINT NOT NULL,reserved_delta BIGINT NOT NULL,reason VARCHAR(180) NOT NULL,reference VARCHAR(80) NOT NULL,actor_id VARCHAR(36),created_at BIGINT NOT NULL,PRIMARY KEY (id),FOREIGN KEY(stock_id) REFERENCES stock_items (id),FOREIGN KEY(lot_id) REFERENCES inventory_lots (id),FOREIGN KEY(actor_id) REFERENCES users (id));
CREATE TABLE orders (id VARCHAR(36) NOT NULL,number VARCHAR(24) NOT NULL,quote_id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,slot_id VARCHAR(36) NOT NULL,status VARCHAR(24) NOT NULL,payment_state VARCHAR(32) NOT NULL,fulfillment_state VARCHAR(24) NOT NULL,delivery_state VARCHAR(24) NOT NULL,snapshot JSON NOT NULL,original_snapshot JSON NOT NULL,total_halalas BIGINT NOT NULL,collected_halalas BIGINT NOT NULL,refunded_halalas BIGINT NOT NULL,cash_state VARCHAR(24) NOT NULL,picker_id VARCHAR(36),courier_id VARCHAR(36),code_cipher TEXT,code_hash VARCHAR(64),code_attempts INTEGER NOT NULL,code_expires_at BIGINT,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT order_financial_bounds CHECK (total_halalas >= 0 AND collected_halalas >= 0 AND collected_halalas <= total_halalas AND refunded_halalas >= 0 AND refunded_halalas <= collected_halalas),CONSTRAINT order_status CHECK (status IN ('active','completed','cancelled')),CONSTRAINT fulfillment_state CHECK (fulfillment_state IN ('queued','picking','awaiting_customer','ready','cancelled')),CONSTRAINT delivery_state CHECK (delivery_state IN ('unassigned','assigned','out_for_delivery','delivered','failed','cancelled')),CONSTRAINT payment_state CHECK (payment_state IN ('awaiting_collection','collected','partially_refunded','refunded','cancelled')),UNIQUE (number),UNIQUE (quote_id),FOREIGN KEY(quote_id) REFERENCES quotes (id),FOREIGN KEY(user_id) REFERENCES users (id),FOREIGN KEY(slot_id) REFERENCES delivery_slots (id),FOREIGN KEY(picker_id) REFERENCES users (id),FOREIGN KEY(courier_id) REFERENCES users (id));
CREATE TABLE notifications (id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,dedupe_key VARCHAR(160) NOT NULL,title VARCHAR(140) NOT NULL,body TEXT NOT NULL,order_id VARCHAR(36),is_read BOOLEAN NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),FOREIGN KEY(user_id) REFERENCES users (id),UNIQUE (dedupe_key),FOREIGN KEY(order_id) REFERENCES orders (id));
CREATE TABLE order_costs (id VARCHAR(36) NOT NULL,order_id VARCHAR(36) NOT NULL,kind VARCHAR(20) NOT NULL,amount_halalas BIGINT NOT NULL,actor_id VARCHAR(36) NOT NULL,reference VARCHAR(180) NOT NULL,PRIMARY KEY (id),CONSTRAINT one_direct_cost_per_kind UNIQUE (order_id, kind),CONSTRAINT nonnegative_direct_cost CHECK (amount_halalas >= 0),CONSTRAINT direct_cost_kind CHECK (kind IN ('delivery','packaging','other')),FOREIGN KEY(order_id) REFERENCES orders (id),FOREIGN KEY(actor_id) REFERENCES users (id));
CREATE TABLE order_events (id VARCHAR(36) NOT NULL,order_id VARCHAR(36) NOT NULL,actor_id VARCHAR(36),event VARCHAR(60) NOT NULL,reason TEXT NOT NULL,states JSON NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),FOREIGN KEY(order_id) REFERENCES orders (id),FOREIGN KEY(actor_id) REFERENCES users (id));
CREATE TABLE refunds (id VARCHAR(36) NOT NULL,order_id VARCHAR(36) NOT NULL,component_id VARCHAR(36) NOT NULL,amount_halalas BIGINT NOT NULL,reason TEXT NOT NULL,state VARCHAR(24) NOT NULL,requested_by VARCHAR(36) NOT NULL,approved_by VARCHAR(36),reference VARCHAR(180) NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT refund_amount_positive CHECK (amount_halalas > 0),CONSTRAINT refund_state CHECK (state IN ('requested','processing','completed','failed','rejected')),FOREIGN KEY(order_id) REFERENCES orders (id),FOREIGN KEY(requested_by) REFERENCES users (id),FOREIGN KEY(approved_by) REFERENCES users (id));
CREATE TABLE reviews (id VARCHAR(36) NOT NULL,order_id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,rating INTEGER NOT NULL,comment VARCHAR(1000) NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT review_rating_range CHECK (rating BETWEEN 1 AND 5),UNIQUE (order_id),FOREIGN KEY(order_id) REFERENCES orders (id),FOREIGN KEY(user_id) REFERENCES users (id));
CREATE TABLE substitutions (id VARCHAR(36) NOT NULL,order_id VARCHAR(36) NOT NULL,line_id VARCHAR(36) NOT NULL,component_id VARCHAR(36) NOT NULL,proposed JSON NOT NULL,default_action VARCHAR(30) NOT NULL,state VARCHAR(20) NOT NULL,expires_at BIGINT NOT NULL,actor_id VARCHAR(36) NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),CONSTRAINT no_implicit_consent CHECK (default_action = 'remove_entire_line'),FOREIGN KEY(order_id) REFERENCES orders (id),FOREIGN KEY(actor_id) REFERENCES users (id));
CREATE TABLE tickets (id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,order_id VARCHAR(36),subject VARCHAR(160) NOT NULL,state VARCHAR(20) NOT NULL,messages JSON NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY (id),FOREIGN KEY(user_id) REFERENCES users (id),FOREIGN KEY(order_id) REFERENCES orders (id));
CREATE INDEX ix_offerings_family_id ON offerings (family_id);CREATE INDEX ix_rate_windows_expires_at ON rate_windows (expires_at);CREATE INDEX ix_addresses_user_id ON addresses (user_id);CREATE INDEX ix_audit_log_action ON audit_log (action);CREATE INDEX ix_delivery_slots_starts_at ON delivery_slots (starts_at);CREATE INDEX ix_delivery_slots_zone_id ON delivery_slots (zone_id);CREATE INDEX ix_idempotency_records_key ON idempotency_records (key);CREATE INDEX ix_idempotency_records_user_id ON idempotency_records (user_id);CREATE INDEX ix_inventory_lots_expires_at ON inventory_lots (expires_at);CREATE INDEX ix_inventory_lots_stock_id ON inventory_lots (stock_id);CREATE INDEX ix_sessions_expires_at ON sessions (expires_at);CREATE INDEX ix_sessions_user_id ON sessions (user_id);CREATE INDEX ix_quotes_expires_at ON quotes (expires_at);CREATE INDEX ix_quotes_slot_id ON quotes (slot_id);CREATE INDEX ix_quotes_user_id ON quotes (user_id);CREATE INDEX ix_recurring_plans_next_at ON recurring_plans (next_at);CREATE INDEX ix_recurring_plans_user_id ON recurring_plans (user_id);CREATE INDEX ix_stock_movements_stock_id ON stock_movements (stock_id);CREATE INDEX ix_orders_courier_id ON orders (courier_id);CREATE INDEX ix_orders_created_at ON orders (created_at);CREATE INDEX ix_orders_picker_id ON orders (picker_id);CREATE INDEX ix_orders_slot_id ON orders (slot_id);CREATE INDEX ix_orders_user_id ON orders (user_id);CREATE INDEX ix_notifications_user_id ON notifications (user_id);CREATE INDEX ix_order_costs_order_id ON order_costs (order_id);CREATE INDEX ix_order_events_order_id ON order_events (order_id);CREATE INDEX ix_refunds_order_id ON refunds (order_id);CREATE INDEX ix_substitutions_expires_at ON substitutions (expires_at);CREATE INDEX ix_substitutions_order_id ON substitutions (order_id);CREATE INDEX ix_tickets_user_id ON tickets (user_id);