import { guard, safeCookies, rpcBusinessResult, requiredIdempotency } from "./http.ts";
const SB=Deno.env.get('SUPABASE_URL')!;const KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
function cookies(req:Request){return safeCookies(req)}
function token(req:Request){const a=req.headers.get('authorization')||'';return a.startsWith('Bearer ')?a.slice(7).trim():(cookies(req).jana_session||'')}
function json(data:any,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
async function rpc(name:string,args:any){const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(args)});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Object.assign(new Error(d?.message||'rpc_error'),{status:r.status});return rpcBusinessResult(d)}
Deno.serve(guard(async(req)=>{try{const u=new URL(req.url),p=u.pathname.split('/jana-ops-extra')[1]||'/';if(req.method==='GET'&&p==='/health')return json({ok:true,service:'jana-ops-extra',version:8});const t=token(req);if(!t)return json({error:{code:'AUTH_REQUIRED',message:'سجّل الدخول'}},401);
let m=p.match(/^\/api\/ops\/orders\/([^/]+)\/collect$/);if(m&&req.method==='POST'){const b=await req.json();const amount=Number(b.amount_halalas);if(!Number.isSafeInteger(amount)||amount<0)return json({error:{code:'VALIDATION',message:'مبلغ التحصيل غير صحيح'}},422);return json(await rpc('jana_critical_write',{p_token:t,p_key:requiredIdempotency(req),p_operation:'cod.collect',p_payload:{order_id:m[1],amount_halalas:amount}}));}
m=p.match(/^\/api\/ops\/orders\/([^/]+)\/settle$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_critical_write',{p_token:t,p_key:requiredIdempotency(req),p_operation:'cod.settle',p_payload:{order_id:m[1],reference:String(b.reference||''),...(Object.hasOwn(b,'amount_halalas')?{amount_halalas:b.amount_halalas==null?null:Number(b.amount_halalas)}:{})}}));}
if(p==='/api/ops/finance'&&req.method==='GET')return json(await rpc('jana_finance_overview',{p_token:t}));
m=p.match(/^\/api\/ops\/orders\/([^/]+)\/refunds$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_critical_write',{p_token:t,p_key:requiredIdempotency(req),p_operation:'refund.create',p_payload:{order_id:m[1],amount_halalas:Number(b.amount_halalas),reason:String(b.reason||''),reference:String(b.reference||''),payment_source:String(b.payment_source||'')}}),201);}
m=p.match(/^\/api\/ops\/refunds\/([^/]+)\/(complete|reject)$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_critical_write',{p_token:t,p_key:requiredIdempotency(req),p_operation:m[2]==='complete'?'refund.complete':'refund.reject',p_payload:m[2]==='complete'?{refund_id:m[1],reference:String(b.reference||''),payment_source:String(b.payment_source||'')}:{refund_id:m[1],reason:String(b.reason||'')}}));}
if(p==='/api/ops/catalog'&&req.method==='GET')return json(await rpc('jana_admin_catalog',{p_token:t}));
if(p==='/api/ops/products'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_create_product_version',{p_token:t,p_family_id:b.family_id||null,p_payload:b}),201);}
m=p.match(/^\/api\/ops\/product-versions\/([^/]+)\/activate$/);if(m&&req.method==='POST')return json(await rpc('jana_admin_activate_product_version',{p_token:t,p_version_id:m[1]}));
if(p==='/api/ops/suppliers'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_create_supplier',{p_token:t,p_name:String(b.name||''),p_phone:String(b.phone||'')}),201);}
if(p==='/api/ops/coupons'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_create_coupon_v2',{p_token:t,p_code:String(b.code||''),p_amount_halalas:Number(b.amount_halalas),p_minimum_halalas:Number(b.minimum_halalas),p_max_uses:Number(b.max_uses),p_expires_at:Number(b.expires_at),p_discount_type:b.discount_type||'fixed',p_percentage_bps:b.percentage_bps??null}),201);}
if(p==='/api/ops/slots'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_create_slot',{p_token:t,p_zone_id:String(b.zone_id||''),p_starts_at:Number(b.starts_at),p_ends_at:Number(b.ends_at),p_cutoff_at:Number(b.cutoff_at),p_capacity:Number(b.capacity)}),201);}
if(p==='/api/ops/stock'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_inventory_create_stock',{p_token:t,p_name:String(b.name||''),p_base_unit:String(b.base_unit||'')}),201);}
if(p==='/api/ops/lots'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_inventory_receive_lot',{p_token:t,p_stock_id:String(b.stock_id||''),p_supplier_id:b.supplier_id?String(b.supplier_id):null,p_received_base:Number(b.received_base),p_total_cost_halalas:b.total_cost_halalas==null?null:Number(b.total_cost_halalas),p_expires_at:Number(b.expires_at)}),201);}
m=p.match(/^\/api\/ops\/lots\/([^/]+)\/inspect$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_inventory_inspect_lot',{p_token:t,p_lot_id:m[1],p_state:String(b.state||''),p_note:String(b.note||'')}));}
m=p.match(/^\/api\/ops\/lots\/([^/]+)\/adjust$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_inventory_adjust_lot',{p_token:t,p_lot_id:m[1],p_new_on_hand:Number(b.new_on_hand),p_reason:String(b.reason||'')}));}
m=p.match(/^\/api\/ops\/families\/([^/]+)\/versions$/);if(m&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_new_offering_version',{p_token:t,p_family_id:m[1],p_payload:b}),201);}
if(p==='/api/ops/zones'&&req.method==='POST'){const b=await req.json();return json(await rpc('jana_admin_create_zone',{p_token:t,p_name:String(b.name||''),p_polygon:b.polygon,p_fee_halalas:Number(b.fee_halalas),p_minimum_halalas:Number(b.minimum_halalas)}),201);}
m=p.match(/^\/api\/ops\/offerings\/([^/]+)\/active$/);if(m&&req.method==='PATCH'){const b=await req.json();return json(await rpc('jana_admin_set_offering_active',{p_token:t,p_offering_id:m[1],p_active:Boolean(b.active)}));}
m=p.match(/^\/api\/ops\/coupons\/([^/]+)\/active$/);if(m&&req.method==='PATCH'){const b=await req.json();return json(await rpc('jana_admin_set_coupon_active',{p_token:t,p_coupon_id:m[1],p_active:Boolean(b.active)}));}
m=p.match(/^\/api\/ops\/slots\/([^/]+)\/active$/);if(m&&req.method==='PATCH'){const b=await req.json();return json(await rpc('jana_admin_set_slot_active',{p_token:t,p_slot_id:m[1],p_active:Boolean(b.active)}));}
return json({error:{code:'NOT_FOUND',message:'المسار غير موجود'}},404)}catch(e){const raw=String((e as any)?.message||'internal');const status=raw.includes('idempotency_conflict')?409:raw.includes('invalid_idempotency_key')?422:raw.includes('unauthorized')||raw.includes('forbidden')?403:raw.includes('not_found')?404:raw.includes('validation')||raw.includes('invalid_component')?422:raw.includes('invalid_')||raw.includes('already_')||raw.includes('duplicate key')?409:((e as any)?.status&&((e as any).status<500)?(e as any).status:500);return json({error:{code:raw.includes('invalid_idempotency_key')?'IDEMPOTENCY_REQUIRED':raw.includes('idempotency_conflict')?'IDEMPOTENCY_CONFLICT':status===403?'FORBIDDEN':status===422?'VALIDATION':'OPERATION_FAILED',message:'تعذر تنفيذ العملية بأمان'}},status)}}));
